### ISSUE TITLE
signMessage verifyMessage do not seem to work

### ISSUE THREAD

**Issue by romerun** [bitpay/bitcore#1002]
Hi, I'm playing with bitcore 0.1.41.

var bitcore = require('bitcore');
var message = "mymessage";
var privkey = "KyDgVU7tH5DvZMyMtc4xZyfGDfXXZix27QVx1UNB7EBoLGcA2Zwt";
var walletKey = new bitcore.WalletKey({});

walletKey.fromObj({priv:privkey});

var address = walletKey.storeObj().addr;
console.log(address);

var signature = bitcore.Message.signMessage(message, walletKey.privKey);
console.log(signature.toString('base64'));

var result = bitcore.Message.verifyMessage(address, message, signature);
console.log(result);

The result is false.
Not sure if I did something wrong, or it's a bug.

**Comment by eordano** [comment]
This is a known issue with 0.1

Our current rewrite of the library (0.8 and 0.9) has no support for messages. We are going to eventually write a `bitcore-messages` library. You can take a look at fullnode's implementation, which is correct:

https://github.com/ryanxcharles/fullnode/blob/master/lib/bsm.js

**Comment by thofmann** [comment]
@romerun They're currently working on the `bitcore-message` library. You can watch for it here: https://github.com/bitpay/bitcore-message
