### ISSUE TITLE
Add full support for standard Multisig inputs and outputs

### ISSUE THREAD

**Issue by eordano** [bitpay/bitcore#1007]
Currently, the only two fully supported types of inputs and outputs are P2SH and P2PKH. We could (should we?) add support for standard multisig and maybe add support for Pay To Public Key.

**Comment by maraoz** [comment]
I'd like @jgarzik's opinion on this. Should bitcore support "old" standards like creating regular (non-p2sh) multisig inputs, and p2pubkey inputs?

**Comment by braydonf** [comment]
I was able to construct a multisig transaction (not p2sh) so I think it's supported, but it's just more cumbersome, which is understandable.

**Comment by maraoz** [comment]
@braydonf if I'm not mistaken, you can create a pay2multisig output, but not SPEND it easily using bitcore. I'm talking about creating a multisig *input* script (scriptSig)

**Comment by braydonf** [comment]
You may be right there. An equivalent `buildMultisigIn` for the `buildMultisigOut` would probably be useful there.

**Comment by porkchop** [comment]
Has there been any progress on spending non-p2sh multisig outputs or examples of brute forcing it with the current bitcore?

**Comment by maraoz** [comment]
@porkchop no progress yet. If you need that, I'd recommend you look at [how we do it for p2sh and p2pkh inputs](https://github.com/bitpay/bitcore/tree/master/lib/transaction/input), and try to imitate it. a PR implementing this would be MUCH appreciated! :)

**Comment by porkchop** [comment]
Thanks @maraoz I'm looking into it :)

**Comment by braydonf** [comment]
Support was added in: https://github.com/bitpay/bitcore-lib/pull/12
