### ISSUE TITLE
Add a convenient way to query about UTXOs using bitcore-p2p

### ISSUE THREAD

**Issue by eordano** [bitpay/bitcore#1008]

**Comment by braydonf** [comment]
Additionally to broadcast a transaction.

**Comment by eordano** [comment]
Broadcasting a transaction is fine, but querying about UTXOs... I don't think this is possible -- unless you're talking against a bitcoinXT instance -- https://github.com/bitcoinxt/bitcoinxt

**Comment by braydonf** [comment]
This may be more relevant for bitcore-node/insight, since this won't be possible without keeping a database, which is outside the scope of bitcore-p2p.
