### ISSUE TITLE
add link to bitpay labs in bitcore.io

### ISSUE THREAD

**Issue by maraoz** [bitpay/bitcore#1017]
http://bitpaylabs.com/c/bitcore

**Comment by marianorod** [comment]
![bitcoreio-header-nav-option](https://cloud.githubusercontent.com/assets/4934213/5976349/809e8c14-a86b-11e4-8adc-bea3d1e1b939.png)
Please advice on the order according to importance. Check the suggestion atached

**Comment by maraoz** [comment]
LGTM
