### ISSUE TITLE
Comments in HDPublicKey incorrectly referring to private keys

### ISSUE THREAD

**Issue by thofmann** [bitpay/bitcore#1035]
Looks like these were missed when copying and editing from HDPrivateKey:

https://github.com/bitpay/bitcore/blob/master/lib/hdpublickey.js#L92

https://github.com/bitpay/bitcore/blob/master/lib/hdpublickey.js#L168

https://github.com/bitpay/bitcore/blob/master/lib/hdpublickey.js#L171

https://github.com/bitpay/bitcore/blob/master/lib/hdpublickey.js#L181

https://github.com/bitpay/bitcore/blob/master/lib/hdpublickey.js#L184

**Comment by maraoz** [comment]
thanks for the heads up!
