### ISSUE TITLE
expose lodash dependency for submodules to use

### ISSUE THREAD

**Issue by maraoz** [bitpay/bitcore#1039]
This will reduce the submodule file sizes for the browser

**Comment by maraoz** [comment]
Let's close this when submodules use this

**Comment by eordano** [comment]
Associated PRs (all blocked on releasing 0.9.6)
* [ ] p2p: https://github.com/bitpay/bitcore-p2p/pull/30
* [ ] explorers: https://github.com/bitpay/bitcore-explorers/pull/8
* [ ] mnemonic: https://github.com/bitpay/bitcore-payment-protocol/pull/8
