### ISSUE TITLE
PrivateKey isValid returns true when called with empty string

### ISSUE THREAD

**Issue by eordano** [bitpay/bitcore#1051]
This is because it's implemented as `try { new PrivateKey(something); return true; } catch (e) { return false; }` and it will fall into `new PrivateKey(undefined)` if `something` is `undefined`, which is interpreted as `new PrivateKey()` and it generates a new private key.

**Comment by braydonf** [comment]
Fixed in: https://github.com/bitpay/bitcore/commit/9409698e0687e23bd2e2f9656c3bbea5d11e970e
