### ISSUE TITLE
Multisig transaction documentation

### ISSUE THREAD

**Issue by thofmann** [bitpay/bitcore#1052]
https://github.com/bitpay/bitcore/blob/master/docs/transaction.md

The documentation shows how to serialize and pass transactions between parties, but it is not particularly useful without a demonstration of verifying new signatures in a transaction.

For example, Alice creates a transaction redeeming a 2-of-2 P2SH output and signs it:

```javascript
  var multiSigTx = new Transaction()
      .from(utxo, publicKeys, threshold)
      .to(destination, amount)
      .change(address)
      .sign(privateA);
  var serialized = multiSigTx.toObject();
```

Alice then sends this serialized transaction to Bob, who agrees and signs it:

```javascript
  var multiSigTx = new Transaction(serialized)
      .sign(privateB);
 var newSerialized = multiSigTx.toObject();
```

After sending the newSerialized transaction back, how can Alice easily add the new signature to the original transaction (or verify that the new transaction is the same as the original, only with more signatures)? I am guessing the approach should be something like this.

```javascript
  var newMultiSigTx = new Transaction(newSerialized);
  var signatures = newMultiSigTx.getSignatures();
  for (var i in signatures){
    multiSigTx.applySignature(signatures[i]);
  }
  var fullySigned = multiSigTx.isFullySigned():
```

Would this be correct? Perhaps a 'merge' method could be added to Transaction, so that incorporating the new signatures could be as simple as:

```javascript
  var newMultiSigTx = new Transaction(newSerialized);
  multiSigTx.merge(newMultiSigTx);
  var fullySigned = multiSigTx.isFullySigned();
```

I would be happy to add to the documentation, or implement a 'merge' method. I'm just looking for initial feedback first.

**Comment by thofmann** [comment]
Looking closer at `getSIgnatures`, it looks like this is used for creating new signatures with a given private key rather than retrieving the transaction's existing signatures. Maybe this method should be be a private `_getSignatures`?

**Comment by eordano** [comment]
Can you please review this PR with updated documentation? the `merge` method could be an alias of `applySignatures`.

**Comment by thofmann** [comment]
The PR is a definite improvement to the documentation, but merging signatures from two transactions is still not addressed. I commented on one typo in the PR as well.

Maybe I am approaching the problem wrong. Rather than signing the transaction and sending the entire serialized transaction back, the second party should only use the `getSignatures` method and send back the Signature itself.

**Comment by eordano** [comment]
https://github.com/bitpay/bitcore/pull/1062

**Comment by eordano** [comment]
@thofmann did #1062 fixed this?

**Comment by thofmann** [comment]
Yes, this commit helps very much. I also think the recent changes in serializing/parsing transactions/outputs fix some of the problems I was having.

It seems that the best approach is returning the result of `getSignatures`.

Thanks!
