### ISSUE TITLE
Provide signed releases for bitcore

### ISSUE THREAD

**Issue by dskloet** [bitpay/bitcore#1077]
I made this simple web app and posted about it on Reddit. (http://dskl.net/bitcoin/coldspend/online.html)
Somebody pointed out that there was minified code in my app and that makes it hard to trust. I didn't write minified code but I served the bitcore library (unchanged) which is minified code.
I think people would find it easier to trust if they saw that bitcore was served directly from BitPay or some other known and trustable location like the github repo.

**Comment by eordano** [comment]
You can get these files from our tag releases:

https://github.com/bitpay/bitcore/blob/v0.10.3/bitcore.min.js

I'll change the title to provide signed releases for these files.

**Comment by dskloet** [comment]
Great! How come I don't see that blob directory from https://github.com/bitpay/bitcore/ ?

**Comment by eordano** [comment]
We don't commit the built files into the main repository, just in commits that branch out of `master` and are tagged as releases

**Comment by dskloet** [comment]
Is there some way to browser through these directories so that I can see what else is there and find new versions when they are available?

**Comment by eordano** [comment]
https://github.com/bitpay/bitcore/releases

**Comment by eordano** [comment]
the only extra files are `bitcore.min.js` (not minified) and `bitcore.min.js`. Our build process is specified here: https://github.com/bitpay/bitcore-build/blob/master/index.js

**Comment by dskloet** [comment]
> https://github.com/bitpay/bitcore/releases

That link shows the latest release as 0.10.0?

**Comment by eordano** [comment]
For some reason it got bumped to top. There are other releases in there below, I'm not sure why

**Comment by dskloet** [comment]
OK, I found https://github.com/bitpay/bitcore/releases/tag/v0.10.3
But I still don't see how I could browse from there to https://github.com/bitpay/bitcore/blob/v0.10.3/bitcore.min.js

**Comment by dskloet** [comment]
Actually, I can't even use https://github.com/bitpay/bitcore/blob/v0.10.3/bitcore.min.js from my web app because https://raw.githubusercontent.com/bitpay/bitcore-explorers/v0.10.0/bitcore-explorers.min.js is served with MIME type text/plain and Chrome refuses to execute it.

**Comment by dskloet** [comment]
By the way, do you realize that https://github.com/bitpay/bitcore/blob/v0.10.3/bitcore.min.js reports itself as version 0.10.2? Not 0.10.3.

**Comment by eordano** [comment]
I'll release a new version now. Thanks!

**Comment by dskloet** [comment]
Did you release a new version?

**Comment by eordano** [comment]
We'll release one now, sorry I've been away the past few days.

**Comment by dskloet** [comment]
Why was this closed? Are signed release binaries served for use directly in web apps? What is the URL?

**Comment by eordano** [comment]
I closed the issue as the `bitcore-build` PR was merged. We're prepping out today's release; it will be signed by @maraoz

Regarding your initial request about serving this file ourselves, that will probably be when we move the hosting for `bitcore.io` to our own servers. For the time being you can use the files served by `npm` or `bower`.

**Comment by dskloet** [comment]
I'm confused. I filed this issue, but you changed it to mean something else and closed it.
Is there another issue to track serving the JS binaries or should I file it again?

**Comment by maraoz** [comment]
@dskloet Minified JS browser bundles are already served via github (see https://raw.githubusercontent.com/bitpay/bitcore/cdb1804184f760db0de15a94fbb20e1b79de352b/bitcore.min.js). Signed files will be served from today's release onwards, after https://github.com/bitpay/bitcore-build/pull/22.

We're not planning to serve the files on our own servers for now, given github already does that and anyone can verify the integrity using the PGP signatures.
Does this solve your issue? If not, please feel free to open a new issue and explain :)

**Comment by eordano** [comment]
@dskloet you can also use the one deployed for the bitcore playground (served with the correct MIME type): https://bitpay.github.io/bitcore.io/playground/bower_components/bitcore/bitcore.min.js

I'm sorry that you feel that we used this issue for another thing. We weren't planning to serve these files for the time being.

**Comment by dskloet** [comment]
I'm not saying an issue has to be fixed immediately. But it could at least stay open until it's fixed :)

I didn't know the bitpay.github.io link. Thanks. I think that will work.

**Comment by dskloet** [comment]
Will the version served from the playground continue to be 0.10.2 or will it be updated as well?

**Comment by eordano** [comment]
https://github.com/bitpay/bitcore/releases/download/v0.10.4/bitcore.min.js

**Comment by dskloet** [comment]
Can this issue be renamed to my original title?
Can BitPay serve the bitcore versions so they can be used in web apps directly?
