### ISSUE TITLE
Add MerkleBlock constructor

### ISSUE THREAD

**Issue by braydonf** [bitpay/bitcore#1082]
As part of BIP37, add a MerkleBlock constructor as is needed for a bitcore-p2p "merkleblock" message type. We can add it in bitcore-p2p, though it may make sense to have it in Bitcore along with Block and BlockHeader.

**Comment by maraoz** [comment]
+1, maybe put this inside a `lib/block/` folder?

**Comment by throughnothing** [comment]
It seems like just `lib/merkleblock.js` would be fine since there is `lib/blockheader.js` and `lib/block.js`, but either way works.
