### ISSUE TITLE
make istanbul/coveralls ignore .md files for coverage

### ISSUE THREAD

**Issue by maraoz** [bitpay/bitcore#1088]
Seems like istanbul is considering markdown files as lines of code.
See: https://github.com/bitpay/bitcore/pull/1073#issuecomment-74878761, and check the files updated in the PR

**Comment by braydonf** [comment]
I think this is related to how it's comparing, since it's based on the last build, and not related to the markdown files.

**Comment by eordano** [comment]
Seems likely, as the files are not listed in coveralls, see https://coveralls.io/builds/1949209 for example
