### ISSUE TITLE
Command Line QRCode Address Enhancement 

### ISSUE THREAD

**Issue by braydonf** [bitpay/bitcore#1097]
This library (or a similar library) will create qrcodes that can be displayed in a terminal: https://www.npmjs.com/package/qrcode-console (edit: https://www.npmjs.com/package/qrcode-terminal)

The inspect method of address could use this to display a qrcode (or some similar method).

Another option would be to have `address.toQRCode()` method.

**Comment by maraoz** [comment]
haha, this would be very cool :+1:

**Comment by braydonf** [comment]
Closing, as more relevant for apps (and not bitcore itself).
