### ISSUE TITLE
Change address check should only apply if there is change.

### ISSUE THREAD

**Issue by braydonf** [bitpay/bitcore#1101]
If the amount in outputs matches the amount in the utxos, should this check apply?

```javascript
/node_modules/bitcore/lib/transaction/transaction.js:130
    throw new errors.Transaction.ChangeAddressMissing();
          ^
Change address is missing
```

**Comment by maraoz** [comment]
can you share the full code example? `ChangeAddressMissing` will appear if there was a problem with the fees and there is no change address. I don't know if that's what we want, and may be the problem here

**Comment by braydonf** [comment]
The total amount of the utxos was specified in a "to" address, so there may have been a problem with the fees. Don't have the code available anymore (will save for the next time).

**Comment by eordano** [comment]
I think this is because an equal "input amount" and "output amount" would be incorrect -- so 0 fee is not a valid fee amount? I'll review that logic now

**Comment by eordano** [comment]
I think this is clearer now: "Change address missing" happens when the fee is too small. See:
https://github.com/bitpay/bitcore/blob/master/lib/transaction/transaction.js#L155 and the following 5 lines

Can you close this issue?
