### ISSUE TITLE
add MerkleBlock to developer guide

### ISSUE THREAD

**Issue by maraoz** [bitpay/bitcore#1117]

**Comment by throughnothing** [comment]
@maraoz happy to help with this, is this just adding an appropriate .md under `docs/merkleblock.js`?

**Comment by maraoz** [comment]
Docs don't have much structure yet, so whatever seems best. I personally would add it to `docs/block.md`, but it may well be worth a new doc page. @braydonf thoughts?

**Comment by braydonf** [comment]
Moved to: https://github.com/bitpay/bitcore-lib/issues/69
