### ISSUE TITLE
add isAddressUsed to bitcore-explorers

### ISSUE THREAD

**Issue by maraoz** [bitpay/bitcore#1120]
See: https://labs.bitpay.com/t/how-to-get-utxos-for-an-hd-wallet/369

`isAddressUsed` should receive an address and return true if the address ever received a transaction

**Comment by dskloet** [comment]
Thanks!

Something more advanced to support HD wallets would be great as well. For example giving a window size of addresses to generate from an extended public key and finding all the unspent outputs from that, increasing the window as long as used addresses continue to be found.

**Comment by dskloet** [comment]
I just noticed that 3 days earlier Insight.address() was added which can tell the total amount received on an address.

https://github.com/bitpay/bitcore-explorers/commit/05dd58a4c5bf5a069dcc64f76665fee855fe9699

The function name isn't super clear but it should do the trick for checking if an address is used.

**Comment by dskloet** [comment]
Unfortunately that code is broken. Issue 1175.

**Comment by maraoz** [comment]
should be fixed with https://github.com/bitpay/bitcore-explorers, can you review it?

**Comment by dskloet** [comment]
I think I've reviewed it. Can you see the comments I left or do I need to send them out or something?

**Comment by braydonf** [comment]
Moved to: https://github.com/bitpay/bitcore-explorers/issues/32
