### ISSUE TITLE
BIP43+BIP44+BIP45 submodule?

### ISSUE THREAD

**Issue by maraoz** [bitpay/bitcore#1121]
Spawned from this discussion: https://labs.bitpay.com/t/does-mnemonic-implement-bip39/356/10?u=maraoz

Should we create a module to allow easier use of this path schemes? How should we call it? 
Maybe `bitcore-paths`... I'm not too happy about that

**Comment by eordano** [comment]
-1 because I think it's too simple for this to be a submodule.

**Comment by braydonf** [comment]
As similar with https://github.com/bitpay/bitcore/issues/73 and https://github.com/bitpay/bitcore/issues/74, possible paths forward (and not directly related with this repo):

- Additional service for bitcore-node (https://github.com/bitpay/bitcore-node)
- BIP44/BIP45 are supported with bitcore-wallet-service (https://github.com/bitpay/bitcore-wallet-service)
