### ISSUE TITLE
Improve Block and BlockHeader arguments

### ISSUE THREAD

**Issue by eordano** [bitpay/bitcore#1125]
Reading a block from RPC, and building a `Block` from the data returned doesn't yield the expected `hash` property. It may be an error of the transformation of the JSON response into a bitcore object (which I had to do manually), but it seems more likely that the underlying issue is a lack of validation that could make me realise where the block instantiation is faulty.

**Comment by braydonf** [comment]
What was the unexpected result for BlockHeader?

**Comment by braydonf** [comment]
Getting the block as hexa from RPC should work (passing false as the second argument), as the JSON formats are likely going to differ.

**Comment by braydonf** [comment]
Just checked an this is working correctly:

```js
var Client = require('bitcoind-rpc');
var bitcore = require('bitcore');

var config = {
  protocol: 'https',
  user: 'user',
  pass: 'password',
  host: '127.0.0.1',
  port: '18332',
  rejectUnauthorized: false
};

var rpc = new Client(config);

rpc.getBlock('00000000df9952ea8ed4ba4561bf67f2e895c51aed7fb44bda5f39b42ea5a5ad', false, function(err, data) {
  var block = new bitcore.Block.fromString(data.result);
  console.log(block.hash);
  // 00000000df9952ea8ed4ba4561bf67f2e895c51aed7fb44bda5f39b42ea5a5ad
});
```
