### ISSUE TITLE
`new Address(inputScript)` doesn't work as expected

### ISSUE THREAD

**Issue by eordano** [bitpay/bitcore#1128]
As an scriptSig most times has enough information to build the address, `new Address(inputScript)` should return the address associated with the output that this input is signing.

**Comment by maraoz** [comment]
+1!

**Comment by braydonf** [comment]
What about `script.toAddress()` ?

**Comment by eordano** [comment]
Closing this issue, `script.toAddress()` works and I don't want to add another reason to have `Address` depend on `Script`.
