### ISSUE TITLE
Build with only URI?

### ISSUE THREAD

**Issue by JustinDrake** [bitpay/bitcore#1132]
I'm looking for a build of Bitcoin which only has `Bitcoin.URI`. (I'm including bitcore.js in an app, and 1.2MB is too large.)

How can I make custom builds?

**Comment by maraoz** [comment]
Please check our developer guide: http://bitcore.io/guide/browser.html

If you need further help, please ask in our community forums: https://labs.bitpay.com/c/bitcore

**Comment by JustinDrake** [comment]
Ok, I must have tried 10 different custom builds (with browserify), and each time I end up with 40K+ lines of code. :(

**Comment by eordano** [comment]
Hmm, yes, I see there are some issues with the dependencies between packages. `URI` requires `Address`, `Address` requires `Script`, and `Script` requires pretty much everything in bitcore...

Maybe we could cut the dependency against `Script`...

**Comment by maraoz** [comment]
I'll close the issue for now, @JustinDrake let us know if you made any progress on this for future reference.

**Comment by JustinDrake** [comment]
No progress. It seems Bitcore's dependency chain is badly engineered for custom builds.

**Comment by maraoz** [comment]
Well, it was optimized for convenience and not for browser bundle size.
I recommend you use the full bitcore bundle while you develop, and then you can manually extract the code you use and use that for production.
In the meantime, thanks for the feedback, I've created an issue to optimize browser builds: https://github.com/bitpay/bitcore/issues/1138

**Comment by JustinDrake** [comment]
> you can manually extract the code you use

I haven't found a clean way of doing that. I'll keep you posted if I do.
