### ISSUE TITLE
Error system

### ISSUE THREAD

**Issue by fanatid** [bitpay/bitcore#1133]
Bitcore error system looks great. But what do you think about split it separate npm package?
It would be good for those who want create own error types without bitcore as dependencies.
Similar package already exists -- [node-errno](https://github.com/rvagg/node-errno), but the alternative is always good :)

**Comment by maraoz** [comment]
Good idea. +1

**Comment by fanatid** [comment]
So, I created [error-system](https://github.com/fanatid/error-system)
differences compared to `bitcore`:
 * Uses `captureStackTrace` if available
 * `createError` function
 * unlimited number of arguments for message {0}, ..., {n}

**Comment by maraoz** [comment]
Thanks for doing that! :)
We'll probably take our own spin at this and create a `bitcore-error` or something. You're welcome to collaborate (we'll let you know)
