### ISSUE TITLE
optimize browser builds

### ISSUE THREAD

**Issue by maraoz** [bitpay/bitcore#1138]
See: https://github.com/bitpay/bitcore/issues/1132

We should remove unnecessary dependencies, maybe by splitting some files into more files. More ideas on how to optimize custom browser bundles are welcome

**Comment by braydonf** [comment]
What about a small library that only does address validation, as well as URI handling?

**Comment by braydonf** [comment]
Bitcore bundled is pretty small and especially when gzipped, don't think this is still relevant.
