### ISSUE TITLE
*.fromBuffer() and Transaction.fromBuffer() is finished check

### ISSUE THREAD

**Issue by braydonf** [bitpay/bitcore#1139]
Currently if transaction.fromBuffer is used with a buffer that has a transaction buffer plus additional data, it will silently ignore the rest of the buffer. A check that the buffer is finished may be useful.

**Comment by maraoz** [comment]
Yes, but we should be careful to contemplate the case of being parsing a transaction inside a block

**Comment by braydonf** [comment]
True, the buffer in that case wouldn't be finished.
