### ISSUE TITLE
bitcore.io SEO changes

### ISSUE THREAD

**Issue by maraoz** [bitpay/bitcore#1142]
- [ ] Change Main features into Bitcore features or Bitcore main features + make it H1 tag
- [ ] Change getting started into getting started with the/our bitcoin api + make it H1 tag
- [ ] Change payment protocol support  to bitcoin payment protocol support 
- [ ] Change Read the docs or visit our community forum  to Read the docs, view our bitcoin api or visit our community forum
- [ ] Change all the core bitcoin functionality to all the bitcoin core functionality
- [ ] Subtitle build great blockchain applications on a powerful bitcoin api
- [ ] Add an extra section on the homepage that explains bitcore with important keywords: Title: a powerful bitcoin library to build apps on the Bitcoin blockchain. Content: The decentralized nature of the Bitcoin network allows for highly resilient bitcoin infrastructure, and the developer community needs reliable open-source tools to implement bitcoin apps and services. Bitcore has a reliable and secure blockchain API for javascript apps that need to interface with Bitcoin. Maintain a wallet, send and receive transactions without needing a local copy of Bitcoin Core, and use many advanced features like payment protocol, payment channels, OP_RETURN, ECIES, wallet seed mnemonics, and more.

**Comment by marianorod** [comment]
Comments about 2 of the reuests: 
<ul>
<li><b>About the first point</b> On Bitcore is our brand so we obviosly rank first in Google, so I don´t really see the need of adding the word "bitcore" in different places on bitcore.io and on the other hand, having a title saying "Bitcore main features" is kind of redundant in a context that all is bitcore.</li>
<li><b>About the last point</b> The title of the text section is too similar to the subtitle requested in the previous point. We need to have something different or have the text with no title</li>
</ul>

**Comment by braydonf** [comment]
Archiving, we can revisit later.
