### ISSUE TITLE
Custom networks not available with Networks.get when using `npm link` or with different versions of bitcore

### ISSUE THREAD

**Issue by braydonf** [bitpay/bitcore#1144]
When adding networks via `Networks.add` the network will not be available with `Networks.get` if different locations that bitcore are used, for example if using `npm link` the dependencies would look like this:

`node_modules/bitcore`
`node_modules/bitcore-p2p/node_modules/bitcore`

`Networks.get` will then return `undefined`, and a network that has been added wouldn't be available and it would use the `defaultNetwork` instead. 

A solution here may be to have a `Networks.isNetwork` method that would check that the argument is a network:

```javascript
var networks;
if (Networks.isNetwork(argument) {
  network = network
} else {
  network = Networks.get(argument) || Networks.defaultNetwork;
}
```

**Comment by braydonf** [comment]
We ran into another issue with Networks where `Networks.get` is returning the incorrect network when custom networks have been added.

**Comment by braydonf** [comment]
The only solution I can think to solve this is to use a common configuration file for the networks, so even if there were multiple versions, the would load the same config.

**Comment by eordano** [comment]
I'd like to fail instantiation of bitcore if another version is found. What do you think of adding a line like this to `index.js`?

```javascript
var inBrowser = typeof process === 'undefined' || typeof process.versions === 'undefined';
if ((inBrowser && window._bitcore) || (!inBrowser && global._bitcore)) {
  throw new Error('More than one instance of bitcore found');
} 
if (inBrowser) {
  window._bitcore = true;
} else {
  global._bitcore = true;
}

```

**Comment by eordano** [comment]
Almost everyone that used bitcore complained of an issue regarding multiple versions of bitcore. The other solution is to make all classes compatible with instantiating from a "sister" class from another bitcore instance.

**Comment by braydonf** [comment]
The versionGuard ( https://github.com/bitpay/bitcore-lib/blob/master/index.js#L7 ) has reduced problems encountered here.
