### ISSUE TITLE
Performance issue at HD Private Key

### ISSUE THREAD

**Issue by matiu** [bitpay/bitcore#1147]
Precalculating HDPublicKey on `.derive` that HDPrivate key
(https://github.com/bitpay/bitcore/blob/master/lib/hdprivatekey.js#L426)
makes the derivation ~60% slower (10s vs. 24s in my systems for 1000 priv key derivations).

Maybe those fields could be calculated on request (there are not always needed)

Here is the test code:
``` js
#!/usr/bin/env node

var b = require('./index');

var i = 0,
  n = 1000;

console.log('Starting'); //TODO
console.time('s');
var h = new b.HDPrivateKey();
while (i++ < n) {
  h.derive('m/' + i);
  if (!(i % 50)) console.log(i);
};

console.timeEnd('s');
```

**Comment by maraoz** [comment]
https://github.com/bitpay/bitcore/pull/1149 fixes this and improves performance from 10 seconds to 4 seconds with the given code
