### ISSUE TITLE
Performance issue at Public Key

### ISSUE THREAD

**Issue by matiu** [bitpay/bitcore#1148]
https://github.com/bitpay/bitcore/blob/master/lib/publickey.js#L56

Using `JSUtil.defineImmutable` makes initialising `PublicKey` much slower, for example this reflects, in this case: Deriving 1000 HDPub keys takes 21% more time because for `JSUtil.defineImmutable`

**Comment by braydonf** [comment]
More time in comparison to using this?
```js
this.point = info.point
```

**Comment by braydonf** [comment]
I ran benchmarks for `defineImmutable` using `Object.defineProperty()` vs. `this.property = someValue` and using `Object.defineProperty()` was around 1/3 the speed. I think the advantages of immutability, in this case, outweigh the performance gain. If there is a specific need?

**Comment by matiu** [comment]
Afaik, not at all.

**Comment by matiu** [comment]
My initial comments was because deriving HD keys in bitcore is really slow, so I had try many ways to make it faster.

**Comment by braydonf** [comment]
Moved to: https://github.com/bitpay/bitcore-lib/issues/70
