### ISSUE TITLE
New class: Chain

### ISSUE THREAD

**Issue by carnesen** [bitpay/bitcore#1150]
It'd be nice if bitcore had a Chain class with attributes like height, bestBlockHash, status, branchLength, ..., and methods like setTip like in Bitcoin Core https://github.com/bitcoin/bitcoin/blob/f914f1a746d7f91951c1da262a4a749dd3ebfa71/src/chain.cpp . The two use cases I have in mind are https://github.com/bitpay/bitcore-node and bitcore-rpc (a bitcore-ified version of https://github.com/bitpay/bitcoind-rpc) for calls like getChainTips and getBlockChainInfo.

**Comment by throughnothing** [comment]
I was thinking the same thing, that a `Chain` class should be included in bitcore somewhere...maybe even `bitcore-chain` if you wanted to keep it separate for those that don't need it.  Anyone developing a full or spv node (as I'm trying to do here (major WIP): [bitcoin-spv](https://github.com/throughnothing/bitcore-spv)) will just be re-implementing this.

**Comment by martindale** [comment]
+1, great idea.  We're going to look at implementing this.

**Comment by maraoz** [comment]
+1!

**Comment by braydonf** [comment]
The new database service in [bitcore-node](https://github.com/bitpay/bitcore-node) has similar functionality: https://github.com/bitpay/bitcore-node/blob/master/lib/services/db.js
