### ISSUE TITLE
Networks.get maps to many network properties.

### ISSUE THREAD

**Issue by braydonf** [bitpay/bitcore#1155]
Network properties are currently grouped into one reverse map. Looking up the network for an address version byte is currently written as:
```javascript
var network = Networks.get(buffer[0]); // the first byte of an address
```

Having more granularity to specify which property would be useful to avoid potential collisions:
```javascript
var network = Networks.address.get(buffer[0]); 
```
The above would only lookup based on the "pubkeyhash" and "scripthash" network properties.

**Comment by eordano** [comment]
You can use https://github.com/bitpay/bitcore/blob/6fa7e7603a0a1adb3b84cc5067fc9bb324a4733a/lib/networks.js#L25 for this. I'd be wary of adding too many properties to the `Networks` namespace.

**Comment by braydonf** [comment]
We may want to do that for these cases: 
- https://github.com/bitpay/bitcore/blob/6fa7e7603a0a1adb3b84cc5067fc9bb324a4733a/lib/hdprivatekey.js#L471
- https://github.com/bitpay/bitcore/blob/6fa7e7603a0a1adb3b84cc5067fc9bb324a4733a/lib/address.js#L164

Similar to:
- https://github.com/bitpay/bitcore/blob/6fa7e7603a0a1adb3b84cc5067fc9bb324a4733a/lib/privatekey.js#L163

And in cases when checking that an argument is a network use an `isNetwork` method:
https://github.com/bitpay/bitcore/blob/6fa7e7603a0a1adb3b84cc5067fc9bb324a4733a/lib/privatekey.js#L100

**Comment by braydonf** [comment]
An address there are two possibilities "pubkeyhash" and "scripthash", so we may need this?

```js
var network = Networks.get(buffer[0], ['pubkeyhash', 'scripthash'])
```

**Comment by eordano** [comment]
+1

**Comment by eordano** [comment]
https://github.com/bitpay/bitcore/pull/1163

**Comment by maraoz** [comment]
#1163 merged, can we close this @braydonf ?

**Comment by braydonf** [comment]
And also fixed in: https://github.com/bitpay/bitcore/pull/1161
