### ISSUE TITLE
Deserialize inputs into the correct subclasses when possible

### ISSUE THREAD

**Issue by eordano** [bitpay/bitcore#1156]
This includes:

* [ ] Deserialize Multisig P2SH inputs and extract threshold and pubkey list correctly
* [ ] Detect present and missing signatures from deserialization.
* [ ] See if it is possible to validate signatures
* [ ] Deserialize P2PKH inputs -- extract signature and public key
* [ ] Serialize correctly inputs so they look like `OP_0 OP_0 OP_0 2-of-3-redeemScript` for partially signed transactions

**Comment by maraoz** [comment]
+1!
