### ISSUE TITLE
RequireJS does not play well with Bitcore

### ISSUE THREAD

**Issue by meinharrd** [bitpay/bitcore#1160]
When trying to load bitcore.js via requirejs I am getting an odd error:

"bitcore.js:3109 Uncaught TypeError: undefined is not a function"

The line is using lodash: ```_.each(childDefinitions, function(childDefinition) {```

My code:
```js
requirejs(['bower_components/bitcore/bitcore'], function () {
  var bitcore = require('bitcore');
});
```

I assume this has to do with the redeclaration of require(). Have you successfully tested bitcore via requirejs? Am I missing something?

**Comment by eordano** [comment]
Hi there,

I agree with you that it must be the redefinition of require. You can create a custom bundle for `bitcore` using: `browserify -s -r index.js` from the main bitcore repo. Sorry I'm not familiar with using `require.js` with browserified modules, but I think this will do the trick. I'll leave this issue open so we can discuss changing `bitcore-build` to use the standalone `-s` option for browserifying. (@maraoz @braydonf)

**Comment by meinharrd** [comment]
hi esteban,

thanks for your feedback. sounds like a "wontfix". ;)

i worked around this with a d.i.y. script loader for now and will get back to it if we decide we need require.js.

**Comment by eordano** [comment]
Hehe, it's not a wontfix :)

I just don't know if it's worth the change for people already using the library. But after talking with @maraoz we decided we'll go ahead and make this change, as it would be more standard. "Better is better".

**Comment by meinharrd** [comment]
awesome! :)

**Comment by braydonf** [comment]
Moved to: https://github.com/bitpay/bitcore/issues/1160
