### ISSUE TITLE
bitcore-mnemonic (probably also other submodules)

### ISSUE THREAD

**Issue by fanatid** [bitpay/bitcore#1164]
```js
$ node
> Mnemonic = require('bitcore-mnemonic')
> bitcore = require('bitcore')
> pubKey = Mnemonic().toHDPrivateKey().publicKey
> address = bitcore.Address.fromPublicKey(pubKey)
TypeError: Address must be an instance of PublicKey.
> address = new bitcore.Address(pubKey)
Invalid Argument: Must provide a `hash` or `hashBuffer` property
```
If second error yet looks normal, first very confusing
`bitcore.Address` not recognized `PublicKey` because `bitcore-mnemonic` used own `bitcore` module...

Probably it's unsolvable problem and I think better way will be add information about this behaviour to `bitcore-mnemonic`

**Comment by braydonf** [comment]
Something along the lines of "unexpected bitcore version detected" may be a better error if multiple bitcore versions are used.  This should be fixed with: https://github.com/bitpay/bitcore-mnemonic/pull/21 (as the versions of bitcore should match).

**Comment by maraoz** [comment]
@fanatid thanks for reporting this in detail. Many developers found this problem (even internally at bitpay) and it's really annoying. We're working on a solution to better report this situation and try to minimize it's occurrence.

**Comment by maraoz** [comment]
should be good to go if you use latest npm versions of both modules (released today). Error messages were improved too. Let me know if the problem persists.

**Comment by fanatid** [comment]
Yes, now all good. Thanks!
