### ISSUE TITLE
Bitcore not working when included in a web worker

### ISSUE THREAD

**Issue by ppratscher** [bitpay/bitcore#1168]
Bitcore does not seem to work when it is included in a web worker.

I am using the following code to initialize bitcore in the worker:
```javascript
var Window = function(){};
var window = new Window();
var Object = function(){};
var object = new Window();
importScripts('bitcore.js');
bitcore = require('bitcore');
```

This throws the following error:
Uncaught TypeError: Cannot read property 'prototype' of undefined on line 36565 in bitcore.js.

I am using version 0.11.5 of bitcore (installed via bower install bitcore)

**Comment by maraoz** [comment]
Thanks for reporting. Seems related to https://github.com/bitpay/bitcore/issues/1160

**Comment by ppratscher** [comment]
Thanks for the comment. Even if I built as standalone using browserify (browserify -s bitcore index.js > bitcore.js) as suggested in the other thread I get the same error.

**Comment by eordano** [comment]
Out of curiosity, the rationale of 
```
var Window = function(){};
var window = new Window();
var Object = function(){};
var object = new Window();
```
is to prevent visibility of Object? What does `importScripts` do?

**Comment by ppratscher** [comment]
Hi, importScripts is used to import external scripts in a webworker environment. The other lines are tries to define the "window" and "object" object AS those standard object are not directly available in a webworker context.

**Comment by eordano** [comment]
I see. We may use a number of methods and functions like `Object.defineProperty` through the code, so maybe this is the root of this issue?

**Comment by eordano** [comment]
Just got it working with this web worker:

```onmessage = function(e) {
  window = {};
  window.Object = Object;
  window.String = String;
  window.RegExp = RegExp;
  window.Math = Math;
  window.Function = Function;
  window.Array = Array;
  window.Date = Date;
  window.parseInt = parseInt;
  window.parseFloat = parseFloat;
  window.crypto = crypto;

  importScripts('bitcore.js');
  var bitcore = require('bitcore');
  console.log(new bitcore.PrivateKey());
}
```

**Comment by maraoz** [comment]
:rocket:

**Comment by eordano** [comment]
I've never worked with WebWorkers, sorry about that code, feels kind of a hacky solution. I hope it's enough to fix your problem, but please reopen this issue if you have any further problems.

**Comment by ppratscher** [comment]
super, that did the trick, thanks a lot!
