### ISSUE TITLE
network immutable

### ISSUE THREAD

**Issue by fanatid** [bitpay/bitcore#1171]
Probably [defineImmutable](https://github.com/bitpay/bitcore/blob/0938eadab5466b73de12bb020fb6a942934cef8f/lib/util/js.js#L62) will better than [_.extend](https://lodash.com/docs#assign) in [addNetwork](https://github.com/bitpay/bitcore/blob/4f4b2b93fbcbd71882bdc3ebd9f6278c487d1894/lib/networks.js#L67) ?

**Comment by maraoz** [comment]
+1
