### ISSUE TITLE
tx.verify() returns true but tx.serialize() throws an exception

### ISSUE THREAD

**Issue by dskloet** [bitpay/bitcore#1172]
I put a fee of 10 bits. Apparently bitcore thinks this is dust (even though several Android wallets have this as a standard fee). But that's fine since I can disable the small fees check.

The problem is that tx.verify() returns true for the same transaction. Is that right? Did I misunderstand what tx.verify() should do?

**Comment by dskloet** [comment]
Sorry, the "dust" error came from me specifying a change address (see issue 1173) but the problem remains that I got an exception even though tx.verify() returned true.

**Comment by dskloet** [comment]
Should this be fixed or does verify() have specific semantics that I missed?
The method has a comment saying

> This function contains the same logic as CheckTransaction in bitcoin core.

Is that so important that the method can't be improved because it would make the comment not true? Or can the comment be removed (or moved to a separate method)?

**Comment by braydonf** [comment]
Yep, `verify()` has a different purpose. `getSerializationError()` will verify the transaction as relevant for `serialize()`
