### ISSUE TITLE
ignore change address when all satoshis are accounted for

### ISSUE THREAD

**Issue by dskloet** [bitpay/bitcore#1173]
If I create a transaction with 2 mBTC input and 1.9 mBTC output and 0.1 mBTC fee and I also specify a change address, tx.serialize() throws an exception saying that there are dust outputs because it thinks I'm sending 9.313225746154785e-10 (rounding error?) satoshis to the change address.

Can it just ignore the change address if the entire amount is sent already?

**Comment by maraoz** [comment]
thanks for reporting. This indeed seems like a rounding error, and should behave as you suggested

**Comment by braydonf** [comment]
Is this still an issue? I just checked this an it works as described:

```js
// total input = 2513795456
// to amount: 2513700000
// fee: 95456

> var tx = bitcore.Transaction();
> tx.from({...});
> tx.to('15vkcKf7gB23wLAnZLmbVuMiiVDc1Nm4a2', 2513700000);
> tx.fee(95456);
> tx.change('15vkcKf7gB23wLAnZLmbVuMiiVDc1Nm4a2');
> tx.serialize({disableIsFullySigned: true});
// no error reported (and only one output)
```

**Comment by braydonf** [comment]
Please reopen if still an issue.

**Comment by dskloet** [comment]
I think this was fixed when it stopped accepting non-integer satoshi amounts.
