### ISSUE TITLE
Insight.address() doesn't work

### ISSUE THREAD

**Issue by dskloet** [bitpay/bitcore#1175]
See https://github.com/bitpay/bitcore-explorers/commit/05dd58a4c5bf5a069dcc64f76665fee855fe9699

The string response body from the XHR is passed to AddressInfo.fromInsight() which expects an object and not a string.

Maybe if AddressInfo had proper type annotations, the compiler would have warned about this?

**Comment by maraoz** [comment]
oh my, you're right. I just wrote a simple example and it fails. We'll submit a fix soon

**Comment by maraoz** [comment]
just released [bitcore-explorers v0.10.4](https://github.com/bitpay/bitcore-explorers/releases/tag/v0.10.4) with this issue fixed
