### ISSUE TITLE
Block.toObject() has prevHash and merkleRoot reversed of what they should be

### ISSUE THREAD

**Issue by pnagurny** [bitpay/bitcore#1180]
For example, Block 1 on testnet: https://test-insight.bitpay.com/block/00000000b873e79784647a6c82962c70d228557d24a747ea4d1b8bbe878e1206

The prevHash should be 000000000933ea01ad0ee984209779baaec3ced90fa3f408719526f8d77f4943.
The merkleRoot should be 4a5e1e4baab89f3a32518a88c31bc87f618f76673e2cc77ab2127b7afdeda33b.

Instead it is coming out as:
prevHash: 43497fd7f826957108f4a30fd9cec3aeba79972084e90ead01ea330900000000
merkleRoot: bac8b0fa927c0ac8234287e33c5f74d38d354820e24756ad709d7038fc5f31f0

The reason it's doing this is because prevHash and merkleRoot are serialized in bitcoin's "hash byte order" which writes the bytes in reverse.

What Braydon and I are doing in ChainDB is instead of keeping prevHash and merkleRoot as Buffers, we convert them to strings in fromBuffer(). Then we convert them to buffers again in toBuffer().

**Comment by maraoz** [comment]
ACK
