### ISSUE TITLE
transaction.to() allows NaN for amount, sending all inputs as mining fee

### ISSUE THREAD

**Issue by karlkeefer** [bitpay/bitcore#1183]
We managed to create and sign transactions with bitcore that had a NaN output.
Below is the decoded transaction that was created and broadcast on testnet.

Maybe there should be some extra input validation, or some other tests to block transactions with outputs of 0, or a check against outrageous fees?

http://tbtc.blockr.io/tx/info/12358fdfc00ad9820ad71e09d5b28ebc33e4f32990c6e6288297fd23624e2e77
````json
{
    "total": 0, 
    "double_spend": false, 
    "received": "2015-04-10T21:04:17.065780211Z", 
    "block_height": -1, 
    "preference": "high", 
    "inputs": [
        {
            "script_type": "pay-to-pubkey-hash", 
            "script": "473044022071b83b7f40431b1f66ce1be8be95e9007d492ab23e8ac5df272a04a19667f2a202205006365a2a1d3e98e5e91079a5fd06b94cf753f1948cd618947f3bbad2f4891b01210235776478c45ba4fdb7ff0e25d278d6fb25d2418a4cbcab43d635c22d526a0384", 
            "output_value": 5770020, 
            "prev_hash": "e050a38bd2ae913cab9828fcaa099bd3452a5b10edacbd1725963268a128cd8a", 
            "age": 5, 
            "output_index": 1, 
            "sequence": 4294967295, 
            "addresses": [
                "mjvYvguEB5K2MicKdxwwgtaBLZ2mfuMtS8"
            ]
        }
    ], 
    "addresses": [
        "mjvYvguEB5K2MicKdxwwgtaBLZ2mfuMtS8", 
        "mhCXGeqpKwkUNH4B4LuafCU1QzfAuYpE3x"
    ], 
    "ver": 1, 
    "lock_time": 0, 
    "fees": 5770020, 
    "relayed_by": "54.82.229.14", 
    "vin_sz": 1, 
    "confirmations": 0, 
    "outputs": [
        {
            "script_type": "pay-to-pubkey-hash", 
            "script": "76a9141273e00991886890d60409c468810f73c4425cf288ac", 
            "value": 0, 
            "addresses": [
                "mhCXGeqpKwkUNH4B4LuafCU1QzfAuYpE3x"
            ], 
            "spent_by": "c6f415181734d96ba8a80a619b1e514e85ef112099eb5d077de7fe6f1d123d27"
        }
    ], 
    "vout_sz": 1, 
    "hash": "12358fdfc00ad9820ad71e09d5b28ebc33e4f32990c6e6288297fd23624e2e77"
}
```

**Comment by braydonf** [comment]
How was the NaN output produced in bitcore?

**Comment by martindale** [comment]
We might also want to add a parameter that is required to be true (default false) if a transaction is being constructed that has > 50% fee, or some threshold.  `allowExpensiveTransactions` or something.

**Comment by karlkeefer** [comment]
The NaN was actually passed into bitcore.transaction.to('publicAddress', NaN). Does that answer your question?

**Comment by porkchop** [comment]
Guys it was created like so:
tx.to('mhCXGeqpKwkUNH4B4LuafCU1QzfAuYpE3x', NaN);

**Comment by braydonf** [comment]
I believe there are checks in transaction.serialize() for this type of behavior. However there may be an issue with NaN specifically not being caught.

In general, `lodash.isNumber` is used for validation in many places, using `utils.isPositiveInteger` may be more precise since: `lodash.isNumber(NaN) === true`

Thanks for reporting.

**Comment by karlkeefer** [comment]
_.isFinite() seems to behave similarly to isNumber without returning true for NaN and Infinity --- not sure how it compares beyond those.

**Comment by braydonf** [comment]
This should help in the situation that `NaN` is passed into `tx.to()` as an amount: https://github.com/bitpay/bitcore/pull/1184

We may want to include this validation in more places, and in output directly to catch other scenarios.
