### ISSUE TITLE
Make sighash more useful?

### ISSUE THREAD

**Issue by dskloet** [bitpay/bitcore#1187]
I'm working on a multisig wallet where the idea is that friends or family members provide some of the signatures for transactions to remove any single point of failure. Since they don't need to know the specifics of my transaction (just that it's really me who made it) I thought I could only send the sighash to them and have them send back the signature, which I then apply to the transaction.

Do you think it makes sense to add some functions to Transaction to make it easier to extract a sighash and apply its signature?

**Comment by maraoz** [comment]
I agree about adding functions to Transaction to extract a sighash and add a signature to it. 
That said, I don't know if it's a good idea to sign a sighash without checking the Transaction. In general, it's generally not a good idea in cryptography to sign some data without knowing what you're signing.

**Comment by dskloet** [comment]
This is for multisig. I will sign the transaction myself but will also ask someone else to sign it on my behalf with a key that I gave them earlier.
