### ISSUE TITLE
Regtest network not listed in lib/networks.js

### ISSUE THREAD

**Issue by olalonde** [bitpay/bitcore#1190]
Bitcore should support the regtest network which is used to create self contained blockchains for testing.

I've tried connecting to a regtest node using bitcore.Peer and my bitcoind regtest node gives me this error:

```
testnetbox_1 | 2015-04-17 04:29:38 PROCESSMESSAGE: INVALID MESSAGESTART version peer=2
testnetbox_1 | 2015-04-17 04:30:35 Adding fixed seed nodes as DNS doesn't seem to be available.
testnetbox_1 | 2015-04-17 04:30:40 PROCESSMESSAGE: INVALID MESSAGESTART version peer=3
testnetbox_1 | 2015-04-17 04:32:56 PROCESSMESSAGE: INVALID MESSAGESTART version peer=4
testnetbox_1 | 2015-04-17 04:33:58 PROCESSMESSAGE: INVALID MESSAGESTART version peer=5
testnetbox_1 | 2015-04-17 04:39:56 PROCESSMESSAGE: INVALID MESSAGESTART version peer=6
testnetbox_1 | 2015-04-17 04:40:58 PROCESSMESSAGE: INVALID MESSAGESTART version peer=7
```

**Comment by olalonde** [comment]
From bitcoin-ruby https://github.com/lian/bitcoin-ruby/blob/ddfb82148914247aaeec7cd4e9cd63d8f3eb129d/lib/bitcoin.rb#L603:

```ruby
  NETWORKS[:regtest] = NETWORKS[:testnet].merge({
      default_port: 18444,
      genesis_hash: "0f9188f13cb7b2c71f2a335e3a4fc328bf5beb436012afca590b1a11466e2206",
      proof_of_work_limit: (1 << 255) - 1,
    })
```

**Comment by olalonde** [comment]
So the error actually is `INVALID MESSAGESTART version`. Any idea of what the problem might be?

**Comment by olalonde** [comment]
Running this fixed my problem:

```javascript
bitcore.Networks.add({
  name: 'regtest',
  alias: 'regtest',
  pubkeyhash: 0x6f,
  privatekey: 0xef,
  scripthash: 0xc4,
  xpubkey: 0x043587cf,
  xprivkey: 0x04358394,
  networkMagic: 0xFABFB5DA,
  port: 18444,
  dnsSeeds: [ ]
});
```

The network magic was the network magic of testnet, not testnet3. Bitcore's testnet network is in fact testnet3. But I still think this should be in the list of default networks.

**Comment by maraoz** [comment]
+1 thanks for sharing your process!

**Comment by braydonf** [comment]
We should add this to the docs https://github.com/bitpay/bitcore/blob/master/docs/networks.md with additional information about running bitcoind and bitcoin-cli with regtest.

**Comment by braydonf** [comment]
The only reason I say we shouldn't add it to the defaults in networks.js is that it will conflict with regular testnet.

**Comment by braydonf** [comment]
I wonder if we should have a `enableRegtest` method that would switch the testnet network with regtest?

**Comment by fanatid** [comment]
I think, better way, instead adding regtest network -- add info in code and on bitcore.io (also in github wiki) that describe how developer can add regtest network manually (that isn't hard!) in his application...

**Comment by braydonf** [comment]
I think there may be a better way to handle the regtest case, by having regtest be an alias for testnet, except in the situation of networkMagic, p2p ports and the dns seeds. It would act as a sub network of testnet, and could be included by default.

**Comment by ciindyprem** [comment]
Adding fixed seed nodes as DNS doesn't seem to be available.
my problem can any1 help?
