### ISSUE TITLE
Use crypto.subtle when possible

### ISSUE THREAD

**Issue by dskloet** [bitpay/bitcore#1191]
There seems to by native browser support for ECDSA and other crypto functions in crypto.subtle. Would it be possible for bitcore to use this?

https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto

**Comment by maraoz** [comment]
Interesting. Do you know how well supported that is in different browsers?

**Comment by dskloet** [comment]
According to the link it's supported in Firefox 34, Chrome 37 and Safari 8.
I would suggest to just fall back on the existing libraries when it's not supported.

**Comment by braydonf** [comment]
Doesn't currently support the secp256k1 curve.

**Comment by dskloet** [comment]
That's too bad. Maybe it can already be used for other things? SHA256 should work at least.
I was mostly hoping to use it for pbkdf2 since creating a private key from a mnemonic is quite slow, but that is either not supported yet or I just couldn't get it to work.

At least it's something to keep an eye on and use when more functions are supported.

**Comment by braydonf** [comment]
Any ideas of performance benefits from doing such for SHA256? Ideally this would be handled in the crypto library itself: https://github.com/bitpay/bitcore/blob/master/lib/crypto/hash.js#L5

**Comment by braydonf** [comment]
I believe this is the library, as browserified: https://github.com/crypto-browserify/crypto-browserify

**Comment by dskloet** [comment]
Why did you close the issue?

**Comment by braydonf** [comment]
It's mostly related with the crypto library, and hence should be resolved there.
