### ISSUE TITLE
Unable to create transaction in bitcore playground

### ISSUE THREAD

**Issue by pagalsurd** [bitpay/bitcore#1192]
The complete details are here. Cross posting because this seems like a bitcore issue. 
http://bitcoin.stackexchange.com/questions/36985/cannot-create-a-transaction

Please let me know if you need me to post the entire text here.

**Comment by maraoz** [comment]
I'll check this!

**Comment by braydonf** [comment]
Adding change after signing will clear the signatures: https://github.com/bitpay/bitcore/blob/master/lib/transaction/transaction.js#L638 If there is another issue, please reopen.

**Comment by pagalsurd** [comment]
Doesn't work, please reopen.

**Comment by braydonf** [comment]
The private key used to sign isn't the correct one for the utxo:
```js
> var key = new bitcore.PrivateKey('0497427ad1b6177fe950758f10151ba38a6b38d44577ba45fb06423143bb55a2');

> key.toAddress(bitcore.Networks.testnet)
<Address: mp9sVdsiBgEYZLCkQJmJssU4g8YWDVombD, type: pubkeyhash, network: testnet>

> transaction.inputs[0].output.script.toAddress(bitcore.Networks.testnet)
<Address: msxGdsTJJYu7YrmkV4sbHNK8Z21pHFZ2gX, type: pubkeyhash, network: testnet>
```

**Comment by braydonf** [comment]
The problem is that the private key isn't instantiated correctly, this works *(though clunky)*:
```js
> var key = new bitcore.PrivateKey(
  new bitcore.crypto.BN('0497427ad1b6177fe950758f10151ba38a6b38d44577ba45fb06423143bb55a2', 'hex')
);
> key.toAddress(bitcore.Networks.testnet);
<Address: mp9sVdsiBgEYZLCkQJmJssU4g8YWDVombD, type: pubkeyhash, network: testnet>
```

**Comment by maraoz** [comment]
Maybe we should update the playground's bitcore version

**Comment by braydonf** [comment]
The playground version has been updated: https://bitcore.io/playground
