### ISSUE TITLE
Wrong hash for Bitcoin genesis block?

### ISSUE THREAD

**Issue by olalonde** [bitpay/bitcore#1194]
```javascript
var b = Block.fromJSON({  
  header: {
      version: 1,
      prevHash: '0000000000000000000000000000000000000000000000000000000000000000',
      merkleRoot: '4a5e1e4baab89f3a32518a88c31bc87f618f76673e2cc77ab2127b7afdeda33b',
      time: 1231006505,
      bits: 486604799,
      nonce: 2083236893
    }
});
console.log(b.hash);
```

This outputs: `f3554f2f2af964264669e106f2367c27fe48e49b767f48ca6f0166d0393dc6f2` instead of `000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f `

I took the header values from https://blockchain.info/rawblock/000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f

**Comment by braydonf** [comment]
Probably related: https://github.com/bitpay/bitcore/issues/1180

**Comment by olalonde** [comment]
Yep, setting merkeRoot to ` merkleRoot: '3ba3edfd7a7b12b27ac72c3e67768f617fc81bc3888a51323a9fb8aa4b1e5e4a',
` fixed the problem.

**Comment by maraoz** [comment]
I think this PR could solve the problem: https://github.com/bitpay/bitcore/pull/1202

**Comment by maraoz** [comment]
@olalonde can you retry with the latest version? Should be solved. If the problem persists please reopen
