### ISSUE TITLE
Invalid script buffer on output.script

### ISSUE THREAD

**Issue by fanatid** [bitpay/bitcore#1195]
```js
// txid: ad0a426817666f56d5b4fba97177f455bbfba3b80faca32a58ae9f947896ec68 (in testnet)
var rawtx = '0100000001cbf75e37f8f57f338dd435d564c7302a02d9c6d03e26c8f0f24fa46052c0c0d1010000008b48304502210095cf913f96c52242b3a88dc59a9aed2a568dc80446541348c89c5430727d548402206adbe00b00db7d71458b990ab69090a038244a6b94faca98652656fd0b9be4e4014104dac5c4da1fd483b8655ab6a5d8e5dd2226ef20d1023d7ff38df29bfa8fcfdf73fb99a07efa0c66112c1fa438a8ed8571364bc04f21eaadf54c4918d43aba8ed3ffffffff02804f1200000000001976a914d40f073684cfac11be0366dc6a56a8d3cc87ece488ac1027000000000000044e6f6e6500000000'

var bitcore = require('bitcore')
var tx = bitcore.Transaction(rawtx)
console.log(tx.outputs[1].script) // Invalid script buffer: can't parse valid script from given buffer None
```

Is there a way to get script (even as buffer) from output when script is invalid? (except `output._scriptBuffer`)

May be necessary to add property `rawScript` which will return `new Buffer(this._scriptBuffer)` ?

See also: #880 -- another improvement (`Script.isValidBuffer`)

**Comment by braydonf** [comment]
The behavior of this has changed in recent versions and `tx.outputs[1].script` will return `null` if the script is invalid. `_scriptBuffer` is still the means to access the script buffer. Checking that a script is valid can be done by checking for null. Does this work?

**Comment by fanatid** [comment]
Yes it works now, thanks.
