### ISSUE TITLE
Update bitcore-channel to v0.12.0

### ISSUE THREAD

**Issue by maraoz** [bitpay/bitcore#1203]
Related: https://github.com/bitpay/bitcore-channel/issues/19, https://github.com/bitpay/bitcore/issues/1059

**Comment by tjgillies** [comment]
:shipit:

**Comment by braydonf** [comment]
Fixed in https://github.com/bitpay/bitcore-channel/commit/53a702239b3893e2bf8e50bf13ca47eaa4abb994 Thanks @maraoz
