### ISSUE TITLE
Fix documentation on http://bitcore.io/guide/hierarchical.html

### ISSUE THREAD

**Issue by ferni** [bitpay/bitcore#1209]
http://bitcore.io/guide/hierarchical.html

There are variables that come out of nowhere: "privateKey" (should be "hdPrivateKey"), "output", and "target", (What type are those? Where did they come from?)

**Comment by maraoz** [comment]
@ferni thanks for pointing this out. Want to try and make a PR fixing this?

**Comment by ferni** [comment]
Ok, I'll make it as soon as I have some time.
