### ISSUE TITLE
Immutable Transaction Optimization

### ISSUE THREAD

**Issue by braydonf** [bitpay/bitcore#1210]
If the Transaction class had an immutable option during construction, it would be possible to cache the serialized version of the transaction to optimize performance of calling `toBuffer()` and computing the hash of the transaction. Likewise it may also be possible to cache the buffer automatically, and then upon any update clear the cache to cause the buffer to regenerate.

**Comment by maraoz** [comment]
good idea

**Comment by braydonf** [comment]
Merging with: https://github.com/bitpay/bitcore/issues/1224
