### ISSUE TITLE
PublicKey `toJSON()` returns invalid hex?

### ISSUE THREAD

**Issue by slezica** [bitpay/bitcore#1215]
The `toJSON()` method from PublicKey seems to lose leading zeroes in the point coordinates, causing it to return invalid hexadecimal (odd length).

From the Bitcore Playground:

    >> publicKey.point
      <EC Point
        x: 0589ee559348bd6a7325994f9c8eff12bd5d73cc683142bd0dd1a17abc99b0dc
        y: 8b3f9a2d8b0d343aa021b9c4c57207acbfa9d95fcd7cacbc248f1a936c0422a5
      >

    >> publicKey.toJSON()
      {
        "x":"589ee559348bd6a7325994f9c8eff12bd5d73cc683142bd0dd1a17abc99b0dc",
        "y":"8b3f9a2d8b0d343aa021b9c4c57207acbfa9d95fcd7cacbc248f1a936c0422a5",
        "compressed":true
      }
  
Note that `toJSON().x` has one less character, the leading zero.

If this is actually a bug, the culprit may be `toObject()`, which uses the numeric coordinates without padding them. The output should still be valid hex, though, so I don't know.

    PublicKey.prototype.toObject = function toObject() {
      return {
        x: this.point.getX().toString('hex'),
        y: this.point.getY().toString('hex'),
        compressed: this.compressed
      };
    };

**Comment by braydonf** [comment]
We may need to do `this.point.getX().toString('hex', 2)` to keep an even length, since the points are instances of BN.
