### ISSUE TITLE
Shorten Transaction.inspect output

### ISSUE THREAD

**Issue by braydonf** [bitpay/bitcore#1222]
Similar to Buffer when the buffer length is greater than a maximum length.

**Comment by eordano** [comment]
It would be also nice to have address info or referenced transaction:vout if possible, and some previous output info if available, like...

`<Transaction <hash> <2 inputs, 3 outputs>
<from 3zyxw....1234>
<from ABCD...1234:1>
<from 1Bitc...1111>
<to 3abcd...addr 43222 sat>
<to OP_SOMETHING OP_TRUE 1241 sat>`

This example showcases:
* Show input address if detected
* If no input script type is available, show TXID:VOUT referenced
* Show input satoshis if available
* Show output address if detected
* Show OP_RETURN data if detected
* Show script if no output type is detected
* If no script type detected on outputs, show script and satoshis
