### ISSUE TITLE
Invalid Script Handling for Output.toObject()

### ISSUE THREAD

**Issue by braydonf** [bitpay/bitcore#1230]
output.toObject() with an invalid script case isn't currently handled, as script would be `null`. We may need to do something similar to:

```js
Output.prototype.toObject = function toObject() {
  var obj = {
    satoshis: this.satoshis
  };
  if (this.script) {
    obj.script = this.script.toString()
  } else {
    obj.script = this._scriptBuffer.toString('hex')
  }
};
```

**Comment by maraoz** [comment]
IMO we should always return the raw hex script, and add a `scriptString` field with `this.script.toString()` if `this.script` exists. Similar to: https://github.com/bitpay/bitcore/blob/master/lib/transaction/input/input.js#L59

**Comment by braydonf** [comment]
That may work better.

Ended up doing this, in https://github.com/bitpay/bitcore/pull/1231, to distinguish between hexa string and script string:
```js
Output.prototype.toObject = function toObject() {
  var obj = {
    satoshis: this.satoshis
  };
  if (this.script) {
    obj.script = this.script.toString();
  } else {
    obj.scriptBuffer = this._scriptBuffer.toString('hex');
  }
  return obj;
};
```

**Comment by braydonf** [comment]
I think this is the most simple and reliable, as _scriptBuffer will always be available even with an invalid script:

```js
Output.prototype.toObject = function toObject() {
  var obj = {
    satoshis: this.satoshis
  };
  obj.script = this._scriptBuffer.toString('hex');
  return obj;
};
```

Updated in #1231
