### ISSUE TITLE
update bitcore modules to use bitcore as a peerDependency

### ISSUE THREAD

**Issue by maraoz** [bitpay/bitcore#1232]
See: http://blog.nodejs.org/2013/02/07/peer-dependencies/
idea: @federicobond

**Comment by braydonf** [comment]
Relevant: https://github.com/bitpay/bitcore-mnemonic/pull/26

**Comment by braydonf** [comment]
If we can the [versionGuard](https://github.com/bitpay/bitcore/blob/master/index.js#L7) with peerDependencies, this may be the way to go with npm@3. There are two use cases I've run into where the versionGuard doesn't work:
- Running multiple versions of bitcore side-by-side for benchmarking
- Running mocha tests in watch mode

**Comment by Levino** [comment]
Any solution to this? I get stuff like:

```sh
 Error: More than one instance of bitcore found with versions: v0.13.3 and v0.13.3. Please make sure to require bitcore and check that submodules do not also include their own bitcore dependency.
```
This does not make sense to me at all...
