### ISSUE TITLE
add Transaction#allTo

### ISSUE THREAD

**Issue by maraoz** [bitpay/bitcore#1234]
Add a new Transaction construction method that allows to send all input coins to one address. Example:

```
new Transaction()
  .from(utxos)
  .allTo(someAddress);
```

Currently, the user has to calculate the input total manually:
```
var tx = new Transaction()
  .from(utxos);
tx = tx.to(someAddress, tx.inputAmount);
```

Using `change` is also error-prone:
```
var tx = new Transaction()
  .from(utxos)
  .change(someAddress);
```
because if the inputamount equals the calculated fee, no change output will be added

**Comment by eordano** [comment]
I'd alias it to `change`. If the inputamount equals the calculated fee, that's an error because of not enough funds for it to be a meaningful transaction
