### ISSUE TITLE
creating a tx with more outputs than inputs fails with a misleading error

### ISSUE THREAD

**Issue by maraoz** [bitpay/bitcore#1236]
Uncaught bitcore.ErrorTransactionFeeErrorDifferent: Unspent value is different from specified fee: Unspent value is -33338 but specified fee is 10000 Use Transaction#uncheckedSerialize if you want to skip security checks. See http://bitcore.io/guide/transaction.html#Serialization for more info.

**Comment by braydonf** [comment]
We may need to do the *output greater than input check* (https://github.com/bitpay/bitcore/blob/master/lib/transaction/transaction.js#L222) before the *fee is different* check?

**Comment by dskloet** [comment]
That error can probably go before all the other ones. I can have a look when #1226 is merged.

**Comment by maraoz** [comment]
Yes, that's the same solution we discussed with @eordano

**Comment by dskloet** [comment]
What about missing signatures? Should that check go before fee errors and dust outputs as well?

**Comment by dskloet** [comment]
I created pull request #1241.
