### ISSUE TITLE
line breaks before operators

### ISSUE THREAD

**Issue by dskloet** [bitpay/bitcore#1240]
I noticed some code like this:
```javascrip
      var complex = new Transaction()
        .from(simpleUtxoWith100000Satoshis)
        .to(toAddress, 50000)
        .change(changeAddress)
        .sign(privateKey);
```
In my understanding, since semicolons are optional in javascript, you should never put a line break where a semicolon would also be possible. So I learned to always put the operator on the previous line rather than the next. Was this an oversight or a conscious decision to do it like this in Bitcore?

**Comment by maraoz** [comment]
That's actually method chaining: http://schier.co/blog/2013/11/14/method-chaining-in-javascript.html

**Comment by dskloet** [comment]
I know. I'm talking about whether the period should go on the previous line or the next.

**Comment by braydonf** [comment]
I've noticed that this will fail:
```js
var tx = new Transaction().fromString('...');
```

However, this will succeed: 
```js
var tx = new Transaction();
tx.fromString('...');
```

**Comment by dskloet** [comment]
I'm not sure how that relates to the issue?

**Comment by eordano** [comment]
Yeah, it's a different issue.

`Transaction().fromString(...)` is a very ugly interface that most likely was overlooked and not dropped when upgrading from 0.1 to 0.8.

Also, you can't do `Transaction.fromString(...)` which should work, and `Transaction().fromString()` shouldn't...

**Comment by braydonf** [comment]
Conscious decision, AFAIK, I don't think it's an issue.
