### ISSUE TITLE
Transaction.sign() changes Transaction.hash

### ISSUE THREAD

**Issue by Levino** [bitpay/bitcore#1242]
I am not sure but I think it only applies to multisig transactions because of the call to

```
this._updateScript()
```
 in the function

```

MultiSigScriptHashInput.prototype.addSignature = function(transaction, signature) {
  $.checkState(!this.isFullySigned(), 'All needed signatures have already been added');
  $.checkArgument(!_.isUndefined(this.publicKeyIndex[signature.publicKey.toString()]),
                  'Signature has no matching public key');
  $.checkState(this.isValidSignature(transaction, signature));
  this.signatures[this.publicKeyIndex[signature.publicKey.toString()]] = signature;
  this._updateScript();
  return this;
};
```
in the file ``` lib/transaction/input/multisigscripthash.js ```

I think this is clearly a bug. No "signature" functionality should ever change the hash of a transaction.

Can I as a workaround trigger an "updateScript" on an unsigned transaction?

Background:

The refund transaction in a payment channel references the commit transaction (more precisely the hash thereof). The consumer gets the refund transaction based on the unsigned commit transaction. If he then signs the commit transaction and gives it to the provider his refund transaction is worthless if the commit transactions hash has change through the signature.

**Comment by braydonf** [comment]
The `scriptSig` is included in the hash of a transaction, so adding, changing or removing signatures on an input will change the hash of the transaction. `setScript()` is called for both `publickeyhash` and 'multisigscripthash' inputs.

**Comment by Levino** [comment]
@braydonf Thanks. So the refund transaction has always to be built by the consumer as one needs the signed commit tx? Very unfortunate by probably my bad. Thanks for the quick reply.
