### ISSUE TITLE
Cant derivate bitcoin testnet address from seed key.

### ISSUE THREAD

**Issue by AugustoL** [bitpay/bitcore#1243]
I have this:

var knownBytes = bitcore.util.sha256('LALALA');
var masterKey = new bitcore.HierarchicalKey.seed(knownBytes,'testnet');
var derived = masterKey.derive('m/'+parseInt(i));
var address = new bitcore.Address.fromPubKey(derived.eckey.public).toString();

address is livenet, not testnet.

On config.js I have testnet and debug.

What Im missing? Thanks!!

**Comment by AugustoL** [comment]
Solved, the parameter 'testnet' was missing in the Address.fromPubKey method.

var knownBytes = bitcore.util.sha256('LALALA');
var masterKey = new bitcore.HierarchicalKey.seed(knownBytes,'testnet');
var derived = masterKey.derive('m/'+parseInt(i));
--> var address = new bitcore.Address.fromPubKey(derived.eckey.public,'testnet').toString();

**Comment by braydonf** [comment]
Good to hear. With the latest versions you should also be able to call `toAddress()` from a derived private key:
```js
> var bitcore = require('bitcore');
> var knownBytes = bitcore.crypto.Hash.sha256(new Buffer('LALALA', 'hex'));
> var masterKey = new bitcore.HDPrivateKey.fromSeed(knownBytes, bitcore.Networks.testnet)
> masterKey
<HDPrivateKey: tprv8ZgxMBicQKsPe4u1AwE1YHRUdNeuZsC17iisZVzUeMBps8Jr6s236KmfaUgGMMyU5MGLYWdiUfsfXVKWn8E9b9y19XfTGviyNLBSo95sVCP>
> var derived = masterKey.derive(0)
> derived
<HDPrivateKey: tprv8bfqy4yrLBboCVgnPpuQ28Gi9VKmCzzgUVw4TAJkKrZgc89ZpzrojvAQJLjCLeUVhX7WJQLVFT4zvLWEDvpbT7ctPzPE2rXj3zCwgYZcfe9>
> derived.privateKey.toAddress()
<Address: mxWgWZypLGh4cMKnZVt39KjZkhtpA9pgGH, type: pubkeyhash, network: testnet>
```
