### ISSUE TITLE
Is that possible to add data as hexa instead of text?

### ISSUE THREAD

**Issue by hoangan** [bitpay/bitcore#1244]
I checked the code, seem like it only allowed to add data as text. I wanna add a SHA256 hash in op_return by the way.

**Comment by hoangan** [comment]
I've just checked out the document, look like can use Custom Scripts for this.

**Comment by maraoz** [comment]
You should be able to do this with `script.addData()`. If it only accepts text, accepting raw buffers is a possible improvement

**Comment by FoundationAwesome** [comment]
try this: tx.addData(new Buffer(sigHex, 'hex'))

works for me!

**Comment by braydonf** [comment]
Both text and buffers are expected argument types: https://github.com/bitpay/bitcore/blob/master/lib/script/script.js#L661

If it's text it will default to `utf-8`, using a buffer, as above, you can specify exactly.

**Comment by braydonf** [comment]
@hoangan does he above work as a solution? 

I have one idea for an improvement for this method:
```js
tx.addData(someHexaString, 'hex');
```

**Comment by hoangan** [comment]
Yeah, that works. Thanks.
