### ISSUE TITLE
Address type in PublicKey.toAddress

### ISSUE THREAD

**Issue by fanatid** [bitpay/bitcore#1246]
Now with `PublicKey.toAddress` you can create only address with `PayToPublicKeyHash` type...
It may be worth to adding second argument as address type?

**Comment by maraoz** [comment]
Not really, unless I'm missing something. What would creating a p2sh address from a public key mean?

**Comment by fanatid** [comment]
I'm not likely understand p2sh with pk to end.. but see transformation pk to p2sh in next way:
```js
var bitcore = require('bitcore')
var pk = bitcore.PrivateKey.fromRandom().toPublicKey()
var data = {
  hash: bitcore.crypto.Hash.sha256ripemd160(pk.toBuffer()),
  type: bitcore.Address.PayToScriptHash
}
var address = bitcore.Address(data)
var script = bitcore.Script.buildScriptHashOut(address)
// <Script: OP_HASH160 20 0xc69004a8746374a4bdcbc82ed02598157b481abb OP_EQUAL>
```
