### ISSUE TITLE
Disable DUSTcheck for OP_RETURN transactions

### ISSUE THREAD

**Issue by FoundationAwesome** [bitpay/bitcore#1247]
Failed to broadcast following OP_RETURN tx via bitcore-explorers because of 'Dust amount detected in one output' 

txtransaction = new Transaction()
  .from(utxos)           # Feed information about what unspent outputs one can use
  .to(address, 1e5)      # Add an output with the given amount of satoshis
  .addData(signatureBin)
  .fee(1e5)
  .change(address)       # Sets up a change address where the rest of the funds will go
  .sign(privKeyWIF)      # Signs all the inputs it can

Workarround:
transaction = transaction.serialize ({disableDustOutputs: true})

**Comment by braydonf** [comment]
There is a test for this case: https://github.com/bitpay/bitcore/blob/master/test/transaction/transaction.js#L368

**Comment by Lalitpatadiya12** [comment]
@FoundationAwesome  Did you disabled the options, I want to disable "disableLargeFees" any idea?
