### ISSUE TITLE
script to asm

### ISSUE THREAD

**Issue by fanatid** [bitpay/bitcore#1249]
Transform script `76a9143705495191e0a8445e88fbe8321a20311b2bd9b088ac` to asm:

bitcoind:
```
getrawtransaction 27eba159ab0c50c3d2d1abad6ce83f501b34121fa96d7aa91fad2c3cfec68366 1
data.vout[1].scriptPubKey.asm
OP_DUP OP_HASH160 3705495191e0a8445e88fbe8321a20311b2bd9b0 OP_EQUALVERIFY OP_CHECKSIG
```

bitcoinjs-lib:
```js
require('bitcoinjs-lib').Script.fromHex('76a9143705495191e0a8445e88fbe8321a20311b2bd9b088ac').toASM()
// 'OP_DUP OP_HASH160 3705495191e0a8445e88fbe8321a20311b2bd9b0 OP_EQUALVERIFY OP_CHECKSIG'
```

bitcore:
```js
require('bitcore').Script('76a9143705495191e0a8445e88fbe8321a20311b2bd9b088ac').toString()
// 'OP_DUP OP_HASH160 20 0x3705495191e0a8445e88fbe8321a20311b2bd9b0 OP_EQUALVERIFY OP_CHECKSIG'
```

Why bitcore asm different from bitcoind and bitcoinjs-lib?

**Comment by braydonf** [comment]
That's a good question. Should it be the same? Thoughts @maraoz

**Comment by maraoz** [comment]
Yes, I think we should probably standardize this

**Comment by fanatid** [comment]
So, what decision? Bitcore asm should look like bitcoind asm? It's break back compatibility... `Script.fromString` should support old format and write warning to console that old format will be deleted, says, from version 0.13?

**Comment by braydonf** [comment]
I agree we should standardize, especially considering that `fromString()` looks like it expects having the `0x` format. Could be good for the next major/minor update.

**Comment by braydonf** [comment]
Started a PR that addresses this: https://github.com/bitpay/bitcore/pull/1290

Both formats should likely be supported in `fromString()` or another similar method. The Bitcoin Core script test data has the format `size 0x`: https://github.com/bitcoin/bitcoin/blob/master/src/test/data/script_valid.json#L523 And is handled by `ParseScript`: https://github.com/bitcoin/bitcoin/blob/master/src/core_read.cpp#L25

**Comment by braydonf** [comment]
So here is an problematic use case:

explicit opcode 9 (push data) followed by the data
```js
var script = Script('9 0x000000000000000010');
```

implicit push data (however it could be read as opcode 10, and then not followed by any data)
```js
var script = Script('000000000000000010');
```

Wondering how to handle this scenario the best.

**Comment by braydonf** [comment]
Adding additional methods `fromASM()` and `toASM()` I think will be the best approach and will also be backwards compatible, and we can add in `0.12.x`

**Comment by braydonf** [comment]
Fixed in: https://github.com/bitpay/bitcore/pull/1295
