### ISSUE TITLE
Consider moving custom errors to a seperate module

### ISSUE THREAD

**Issue by braydonf** [bitpay/bitcore#1257]
Since creating a tree of custom errors has been useful in exception handling, it could be useful to abstract this into a separate module (perhaps similar to [errno](https://www.npmjs.com/package/errno)).

**Comment by fanatid** [comment]
I already did this, npm package -- [error-system](https://www.npmjs.com/package/error-system)
details: #1133

**Comment by braydonf** [comment]
Thanks, I thought I remembered #1133, but didn't find it.

**Comment by maraoz** [comment]
Should we migrate bitcore to using https://github.com/fanatid/error-system?

**Comment by fanatid** [comment]
btw, I'm planning add [string-template](https://github.com/Matt-Esch/string-template) to error-system on holidays

**Comment by fanatid** [comment]
FYI I update package, now error-system support named arguments
