### ISSUE TITLE
Consider seperating bitcore-p2p into two modules 

### ISSUE THREAD

**Issue by braydonf** [bitpay/bitcore#1260]
Since all of the protocol messages can be used in both browser and node, separating those portions into a separate module that can be browserified. See https://github.com/bitpay/bitcore-p2p/pull/66

- bitcore-protocol *(includes Bitcoin protocol messages)*
- bitcore-p2p *(only includes TCP based Peer and Pool)*

**Comment by stefanhuber** [comment]
Has there been any progress on the separation issue, as I am working on peer/pool code for cordova? I can only confirm that the only thing which breaks browserify is peer.js and pool.js.

For cordova these issues could be solved:
 - the dns request inside pool.js could be done via a http rest service e.g. (http://api.statdns.com/seed.bitcoin.sipa.be/a for ip4 and http://api.statdns.com/seed.bitcoin.sipa.be/aaaa for ip6)
 - there are cordova plugins for handling tcpsocket and tcpserver, which are necessary by peer.js

Currently, altering peer.js and pool.js is not easily possible, as the code is somewhat dependent on net, dns, and sock5client modules. One approach would be to create two "abstract classes" (or similar in js) for Peer and Pool, with all the reusable code. The packages could be structured like this:

 - bitcore-p2p (with abstract Peer, Pool and all the protocol messages)
 - bitcore-p2p-node (net based implementations as is now, all test could be reused as well)
 - bitcore-p2p-cordova
 - bitcore-p2p-browser
 - bitcore-p2p-whatever

Another approach could be to keep compatibility with all projects, which use bitcore-p2p already as a dependency:
 - bitcore-p2p-protocol (with abstract Peer, Pool and all the protocol messages)
 - bitcore-p2p (net based implementations as is now, all test could be reused as well)
 - bitcore-p2p-whatever

**Comment by braydonf** [comment]
I think @mappum did some work on this with (though not bitcore specific): https://github.com/mappum/bitcoin-protocol
