### ISSUE TITLE
InvalidSorting raised if there is no change

### ISSUE THREAD

**Issue by yacoobk** [bitpay/bitcore#1261]
If there is no change then calling `.shuffleOutputs` or `.sortOutputs` on a transaction will raise `errors.Transaction.InvalidSorting()` - "The sorting function provided did not return the change output as one of the array elements".

This happens even if `.change` is set appropriately in the case when no change is required. It might be strange to sort the outputs when no change address is required, but i believe the code should handle it more gracefully.

The issue appears to lie in `_newOutputOrder` checking `this.outputs[this._changeIndex]` when `_changeIndex` is undefined.

**Comment by braydonf** [comment]
Thanks for the report!
