### ISSUE TITLE
Critical sorting bug in Script.buildP2SHMultisigIn

### ISSUE THREAD

**Issue by bedeho** [bitpay/bitcore#1263]
It appears there is a very hard to track down bug in Script.buildP2SHMultisigIn, which has signature

/**
 * A new P2SH Multisig input script for the given public keys, requiring m of those public keys to spend
 *
 * @param {PublicKey[]} pubkeys list of all public keys controlling the output
 * @param {number} threshold amount of required signatures to spend the output
 * @param {Array} signatures signatures to append to the script
 * @param {Object=} opts
 * @param {boolean=} opts.noSorting don't sort the given public keys before creating the script (false by default)
 * @param {Script=} opts.cachedMultisig don't recalculate the redeemScript
 *
 * @returns {Script}
 */
Script.buildP2SHMultisigIn = function(pubkeys, threshold, signatures, opts)

The users may or may not choose to have the public keys sorted, by setting opts, however the array of signatures are not correspondingly sorted. As a result, if keys are sorted due to opts.noSorting being set, then there is a mismatch between how keys are ordered in the redeem script and the signatures are ordered in prefix part of the scriptSig being generated.

Both sigs and keys should be sorted, or neither.

**Comment by snakecharmer1024** [comment]
This explains the crazy infrequent bug I've been having with the multisig scripts rearranging themselves and invalidating signatures. 

+1

**Comment by snakecharmer1024** [comment]
Fixed my own bug by adding one line to _updateScript:


MultiSigScriptHashInput.prototype._updateScript = function() {
  this.setScript(Script.buildP2SHMultisigIn(
    this.publicKeys,
    this.threshold,
    this._createSignatures(),
    {
      cachedMultisig: this.redeemScript,
      noSorting: false
    }
  ));
  return this;
};

BTW I recommend not making API's have double not-positives "noSorting: false"

**Comment by snakecharmer1024** [comment]
There really should be no modification of the ordering of the public keys after the transaction output has been created, unless it is specifically requested. We are repeatedly running into the issue of creating a multisig output, having another party sign it, then having the signature rejected because the keys were reordered before checking the signature.

**Comment by braydonf** [comment]
Sorting of the public keys I believe is expected behavior, no? Sorting can be disabled for the public keys via `{noSorting:true}` so that the keys are not sorted (signatures are not sorted in any case).
