### ISSUE TITLE
Bitcoin-Specific Hardcode in Privkey.js

### ISSUE THREAD

**Issue by brandonrobertz** [bitpay/bitcore#1265]
I'm writing a namecoin module for bitcore, and mostly everything is working well. Networks are modular and it's easy to add new ones. I've added a `namecoin` network, which basically allows bitcore to generate namecoin private keys and addresses out-of-the-box.

The problem comes when I generate a private key using something like vanitygen and then import it with bitcore.PrivateKey. I'm doing this:

    var bitcore = require('./'); // I'm in bitcore root
    // I've added namecoin to networks.js as default
    var nmc = bitcore.Networks.get('namecoin');

    var wif = '74pxNKNpByQ2kMow4d9kF6Z77BYeKztQNLq3dSyU4ES1K5KLNiz';
    var privKey = bitcore.PrivateKey.fromWIF( wif);

I get a thrown error of `Invalid Network` which comes from the following code in `privatekey.js` from the `PrivateKey._transformBuffer` function:

    info.network = Networks.get(buf[0], 'privatekey');
    if (buf[0] === Networks.livenet.privatekey) {
      info.network = Networks.livenet;
    } else if (buf[0] === Networks.testnet.privatekey) {
      info.network = Networks.testnet;
    } else {
      throw new Error('Invalid network');
    }

Is there a reason why we're hardcoding `Networks.testnet` and `Networks.livenet` for private key import? When I patch that line with another else if, looking for `Networks.namecoin` everything appears to work, but is there some gotcha I'm not aware of?

**Comment by maraoz** [comment]
You're right. That could be done in a more generic way by iterating through all the available networks and checking if `buf[0]` is equal to a network's `privatekey` value.

**Comment by brandonrobertz** [comment]
I can do a PR for this, we will need to expose `Networks.networks` or a new `Networks.all()` method to iterate through the networks. Is there any interest?

**Comment by brandonrobertz** [comment]
I created a PR for this issue with tests. https://github.com/bitpay/bitcore/pull/1267

Any comments?

**Comment by brandonrobertz** [comment]
New PR is here: https://github.com/bitpay/bitcore/pull/1268

**Comment by braydonf** [comment]
Yep, we've previously updated other areas of the code to use any network defined in networks, instead of `livenet` and `testnet` specifically.

**Comment by braydonf** [comment]
Included in https://github.com/bitpay/bitcore/commit/8e13b68405b591f90597fec34b9f4c26594247b4
