### ISSUE TITLE
SIGHASH_ANYONECANPAY maybe should be separated from sigtype

### ISSUE THREAD

**Issue by snakecharmer1024** [bitpay/bitcore#1266]
Transaction.prototype.applySignature will break if the sigtype does not include the correct anyonecanpay flag. This is probably the correct behavior.

Signature.prototype.hasDefinedHashtype will break if the signature's hashtype has the anyonecanpay flag set. I think this is a bug. 

I propose the following change:

Signature.prototype.hasDefinedHashtype = function() {
  var hashtype = this.nhashtype & 0xf;
//  if (this.nhashtype < Signature.SIGHASH_ALL || this.nhashtype > Signature.SIGHASH_SINGLE) {
  if (hashtype < Signature.SIGHASH_ALL || hashtype > Signature.SIGHASH_SINGLE) {
    return false;
  }
  return true;
};

This issue came up in working thru payment channels

**Comment by braydonf** [comment]
This should be revolved with #1284 from @mruddy and landed in v0.12.11
