### ISSUE TITLE
"Error: Non-base58 character" rarely when trying to sign with privkey generated by bitcore

### ISSUE THREAD

**Issue by Overtorment** [bitpay/bitcore#1270]
Happens very rare, but happens.
I generate both private key and WIF just for any case. 
Sometimes signing with private key fails with error "Error: Non-base58 character"
If I re-generate private key from WIF - same error.
When I generate private key from WIF using 3rd party tools - it signs ok.

Example WIF 
"KwFNEF3GCrFnS7o66Xes9PJBQmMq8xurbV7AHAGpBLQnQLuo92UV"
Which is converted via Bitcore to private key  "da14b811e8558e2ed48f733e29cae1e558f14943b7250f80157d28d3596148"
But this private key generates error.

**Comment by Overtorment** [comment]
version user 0.12.5

**Comment by braydonf** [comment]
Any example code? Unable to reproduce the issue.

**Comment by yogiben** [comment]
Can verify that this sometimes happens.

**Comment by Overtorment** [comment]
Here's what  produces error. Using Chain to sign transactions

```js

config = require('./config')
Chain = require('chain-node')
chain = new Chain(config.chain)
bitcore = require('bitcore')


var wif  = 'KwFNEF3GCrFnS7o66Xes9PJBQmMq8xurbV7AHAGpBLQnQLuo92UV' ;
var imported = bitcore.PrivateKey.fromWIF(  wif  );

console.log("WIF = " + wif);
console.log("Address = " + imported.toAddress().toString());
console.log('Priv = ' + imported.toString());
//process.exit();



        chain.transact(
            {
                inputs: [
                    {
                        address: '1HS7ViuotCB88cQU6mmkCC6MzJGFSDadpD',
                        private_key: imported.toString()
                    }
                ],
                outputs: [
                    {
                        address:  '1HS7ViuotCB88cQU6mmkCC6MzJGFSDadpD',
                        "amount": 1
                    }
                ]
            }, function(err, resp) {
                if (err) {
                    console.log(err);
                } else {

                }
            });








// street magic
process.on('uncaughtException', function(err){
    console.log('Exception: ' + err);
});
```







OUTPUT:

```
WIF = KwFNEF3GCrFnS7o66Xes9PJBQmMq8xurbV7AHAGpBLQnQLuo92UV
Address = 1GGYB9ZapqkTNj14yrweQ8D3sRPaxCYNRP
Priv = da14b811e8558e2ed48f733e29cae1e558f14943b7250f80157d28d3596148

/home/burn/Documents/btczen/node_modules/chain-node/node_modules/bitcoinjs-lib/node_modules/bs58check/node_modules/bs58/lib/bs58.js:56
    if (!(c in ALPHABET_MAP)) throw new Error('Non-base58 character')
                                    ^
Error: Non-base58 character
```


the problem is in

```
Priv = da14b811e8558e2ed48f733e29cae1e558f14943b7250f80157d28d3596148
```

thus in

```js
var wif  = 'KwFNEF3GCrFnS7o66Xes9PJBQmMq8xurbV7AHAGpBLQnQLuo92UV' ;
var imported = bitcore.PrivateKey.fromWIF(  wif  );
console.log('Priv = ' + imported.toString());
```


Expected private key hex:
```
00DA14B811E8558E2ED48F733E29CAE1E558F14943B7250F80157D28D3596148
```
Actual:
```
da14b811e8558e2ed48f733e29cae1e558f14943b7250f80157d28d3596148
```

**Comment by Overtorment** [comment]
![image](https://cloud.githubusercontent.com/assets/1913337/10406137/836b59a8-6ee6-11e5-8b6d-590bda21b578.png)

**Comment by braydonf** [comment]
It sounds to be that you may be passing a hex string to a function that is expecting a base58 encoded WIF value, however the code that is throwing the error isn't shown here, and the error is coming from bitcoinjs-lib. You may just need to use `imported.toWIF()` instead of `imported.toString()`.

Also those private keys are equivalent, except one is not zero padded, that shouldn't make a difference however.

**Comment by Overtorment** [comment]
The function expects private key, and provided code works for 99% of all cases, except this one.
Who to blame? Bitcore because it skipps adding "00" sometimes or Chain because they should work fine with private keys with trimmed zeroes?

**Comment by braydonf** [comment]
The error message however doesn't match with a zero-padding issue however.

**Comment by Overtorment** [comment]
Agree

Сб, 10 окт. 2015 г. в 01:21, Braydon Fuller <notifications@github.com>:

> The error message however doesn't match with a zero-padding issue however.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/bitcore/issues/1270#issuecomment-146999122>.
>
-- 
Sent from my iPhone

**Comment by braydonf** [comment]
If you want to zero pad the number *(though I think it may be unrelated)*, you can run:
```js
var key = bitcore.PrivateKey('da14b811e8558e2ed48f733e29cae1e558f14943b7250f80157d28d3596148');
key.bn.toString(16, 32);
```

**Comment by dabura667** [comment]
I think chain_node test modules has an if-then fork along of the lines of:

```javascript
if (input.length == 64) {
  treat_as_raw_privateKey(input);
} else {
  treat_as_WIF_privateKey(input);
};
```

Which is why the zero padding is probably causing the issue.

However, I don't think the generic prototype.toString() should zero pad. Maybe a prototype.toHex() or something.

**Comment by Overtorment** [comment]
I wonder who is responsible to make that decision

**Comment by fanatid** [comment]
@dabura667 you right, [chain-node make decision about key format from string length](https://github.com/chain-engineering/chain-node/blob/1542653d5c5f47cd236095453cad5e69d80d70a1/signer.js#L40)
@Overtorment `private_key` of `inputs` for `chain.transact` can be represented in `WIF` format

**Comment by dabura667** [comment]
```javascript
var regex = /^[5KL][1-9A-HJ-NP-Za-km-z]{50,51}$/
```

All WIF private keys start with either 5, L, or K, and are between 51-52 characters long with the base58 alphabet.

Maybe you should make a pull request to them changing the catch-all `else` with `else if (...)` to check for WIF. Then throw an error in a new catch-all.

**Comment by Overtorment** [comment]
Good idea. Ill check Chain source

**Comment by braydonf** [comment]
Checking for hex values vs base58 values is what Bitcore will use to determine the difference ( https://github.com/bitpay/bitcore/blob/master/lib/util/js.js#L12 ), perhaps the same could be used.

**Comment by abuaesh** [comment]
I got this error when I was passing a hexadecimal address to bitcoinMessage.verify; because I was using an outdated(v 3.3.7) Electrum wallet to get the address. The newer version(v3.3.8) gives base58 formats for the wallet addresses. 
The error was gone when I tried the base58 address. 

Is there a function that converts addresses from/to hexadecimal and base58 formats? It can come in handy!

**Comment by JayeshKowale** [comment]
i am getting this error when am running my npm dev net plz suggest something

**Comment by abuaesh** [comment]
Hi Jayesh,

Try this:

https://github.com/bitpay/bitcore/issues/1270
