### ISSUE TITLE
MAX_STANDARD_TX_SIGOPS and MAX_BLOCK_SIGOPS not enforced

### ISSUE THREAD

**Issue by greggzigler** [bitpay/bitcore#1274]
Transactions with many inputs and/or outputs might exceed the number of signature operations permitted by bitcoind. Good, expose the number of sigops of a given tx. Better, expose a util to compare sigops to the MAX values. Best, enforce the limit in transaction verify() method or somewhere similar.

**Comment by braydonf** [comment]
Relevant method is Bitcoin: https://github.com/bitcoin/bitcoin/blob/master/src/main.cpp#L776

**Comment by braydonf** [comment]
Also:
MAX_BLOCK_SIGOPS: https://github.com/bitcoin/bitcoin/blob/master/src/consensus/consensus.h
MAX_STANDARD_TX_SIGOPS: https://github.com/bitcoin/bitcoin/blob/master/src/main.h#L62
CScript::GetSigOpCount: https://github.com/bitcoin/bitcoin/blob/master/src/script/script.cpp#L190

**Comment by braydonf** [comment]
Adding a method to script (e.g. `getSignatureOperationCount()`) I think would be a good first step and provide everything that would then be needed.

**Comment by braydonf** [comment]
`getSignatureOperationCount()` has landed in v0.12.11

**Comment by braydonf** [comment]
Moved to: https://github.com/bitpay/bitcore-lib/issues/72
