### ISSUE TITLE
new errors.Transaction.InvalidOutputAmountSum() not message added

### ISSUE THREAD

**Issue by benjaminmcdonald** [bitpay/bitcore#1297]
new errors.Transaction.InvalidOutputAmountSum();

generates an error with no message attached.

"{"message":"undefined Use Transaction#uncheckedSerialize if you want to skip security checks. See http://bitcore.io/guide/transaction.html#Serialization for more info....

in function Transaction.prototype.getSerializationError

**Comment by braydonf** [comment]
Want to submit a PR with a fix for this?

**Comment by braydonf** [comment]
Moved to: https://github.com/bitpay/bitcore-lib/issues/76
