### ISSUE TITLE
Change property being ignored.

### ISSUE THREAD

**Issue by luxi-io** [bitpay/bitcore#1304]
var transaction = new Transaction().from(utxos).to(destination, parseFloat(satoshis)).change(from).sign(derived.privateKey, 0);

Change property is being ignored, and remainder of UTXO being used is being sent as a fee.

transaction.getFee() shows the correct expected fee (generally 0.0001 BTC), however the transaction itself only has 1 output (the destination), with the input/output amount equalling the amount in satoshis listed.

A couple of test sends have shown that the change property is being completely disregarded.

**Comment by braydonf** [comment]
I was unable to reproduce this behavior. The only time that the change address should not be used is if there isn't any change. Can you provide the exact amounts from the utxos and the satoshis.

**Comment by Christewart** [comment]
I am experiencing behavior very similar to this. It is for the utxos that are currently on the address 2NFgDf11zEm1rPhj2ZX8xu56Be3m9hU2yfh when attempting to send 0.002 BTC to another address. The change address is not added to the tx which triggers an error saying the fee is too high.

**Comment by fanatid** [comment]
@Christewart what mean *very similar to this*? Can you show code that repeats this bug?

**Comment by Christewart** [comment]
here you go @fanatid 

```javascript
  insight.getUnspentUtxos("2NFgDf11zEm1rPhj2ZX8xu56Be3m9hU2yfh", function(err, utxos) {
	var p2sh = "2NFgDf11zEm1rPhj2ZX8xu56Be3m9hU2yfh"
	var user1Pub = new bitcore.PublicKey("02b8a02d043db6266a698c4d71585f3b4dc354aa7bf83ba387ed878840be5c05b7");
	var user2Pub = new bitcore.PublicKey("030e7ce7e2694dbfa2bfb3f740c080f0389d59570724bcdd92c60b335984e4db77");
	var sbPub = new bitcore.PublicKey("025e9adcc3d65c11346c8a6069d6ebf5b51b348d1d6dc4b95e67480c34dc0bc75c");
	var userAddress = new bitcore.Address("mw3tkWJAkedEHnsRVyVRbsJFEmAEZPgzAY");
	var suredBitsAddress = bitcore.Address.fromString("n463mgm8c8dVt1sfN2cdViQbFQFRcRewJj");

	var winnings = 200000.0
	var txFee = new bitcore.Unit(10000, bitcore.Unit.satoshis);
	var sbFee = new bitcore.Unit(winnings * 0.01, bitcore.Unit.satoshis);
	var userAmount = winnings - txFee.satoshis - sbFee.satoshis
	var paymentAmount = new bitcore.Unit(userAmount,bitcore.Unit.satoshis);

	paymentAmount = new bitcore.Unit(paymentAmount.satoshis + sbFee.satoshis, bitcore.Unit.satoshis);
	console.log(paymentAmount.satoshis);
	multiSigTx = new bitcore.Transaction()
	.from(utxos, [user1Pub, user2Pub, sbPub], 2)
	 .to(userAddress, paymentAmount.satoshis)
	 .fee(txFee).change(suredBitsAddress)

	console.log("Change output: " + multiSigTx.getChangeOutput());
	console.log(multiSigTx.serialize());
  });```

**Comment by fanatid** [comment]
should be:
```js
multiSigTx = new bitcore.Transaction()
  .from(utxos, [user1Pub, user2Pub, sbPub], 2)
  .to(userAddress, paymentAmount.satoshis)
  .fee(txFee.toSatoshis())
  .change(suredBitsAddress)
```

**Comment by Christewart** [comment]
Interesting, is there any talk of supporting native bitcore unit types in settings amounts instead of converting them down to numeric types in javascript?

**Comment by fanatid** [comment]
As I understand, in `bitcore` you always should use `satoshis`.
`bitcore.Unit` just need for converting between *BTC <-> mBTC <-> uBTC <-> bits <-> satoshis*.
