### ISSUE TITLE
Improve fee estimation in transactions

### ISSUE THREAD

**Issue by isocolsky** [bitpay/bitcore#1309]
Fees should be estimated as a function of the projected size of the transaction without rounding up to the nearest kB.
See https://github.com/bitpay/bitcore/blob/master/lib/transaction/transaction.js#L865

**Comment by braydonf** [comment]
Took a look at how Bitcoin Core is handling fees and  `CFeeRate`  is in units of "satoshis-per-1,000-bytes": https://github.com/bitcoin/bitcoin/blob/ddd8d80c63182aefea56abf743bb9199d9602544/src/amount.h#L39

So going more granular here, may not be beneficial.

**Comment by braydonf** [comment]
However in `GetMinRelayFee` used in `AcceptToMemoryPool`:https://github.com/bitcoin/bitcoin/blob/ddd8d80c63182aefea56abf743bb9199d9602544/src/main.cpp#L743 bytes are used with `CAmount`,

**Comment by braydonf** [comment]
Moved to: https://github.com/bitpay/bitcore/issues/1404
