### ISSUE TITLE
Correct Sequence Number for lockTime transactions

### ISSUE THREAD

**Issue by zmanian** [bitpay/bitcore#1315]
The default sequence number of all inputs is U_INT_MAX.

If a lock time is set on a transactions will all sequence numbers are U_INT_MAX, the transactions is immediately valid for a block.

Setting a locktime using the API does not change the sequence number of the inputs, this makes the locktime set essentially meaningless.

Proposal: Setting the locktime on a transaction should set the sequence number on all inputs to a none MAX value.

**Comment by zmanian** [comment]
Just FYI,

Transaction 224660f2196fd22becb54f7c69f7a0ca07526e456276ef9f000c31a783275ab8 on testnet has 0 sequence number and was created with a locktime. Appears to be a correct tx

**Comment by braydonf** [comment]
Fixed in https://github.com/bitpay/bitcore/pull/1324
Landed in release 0.13.2
