### ISSUE TITLE
Transactions signed with SIGHASH_ANYONECANPAY

### ISSUE THREAD

**Issue by zmanian** [bitpay/bitcore#1318]
I haven't fully understood what is going on here but it's pretty clear to me that signing SIGHASH_ANYONECANPAY produces a signature that is invalid and not accepted by bitcoin core.

Needs further investigation.

**Comment by maraoz** [comment]
Thanks for reporting!!

**Comment by braydonf** [comment]
Moved to: https://github.com/bitpay/bitcore-lib/issues/75
