### ISSUE TITLE
Bitcore incorrectly classifies 80 byte OP_RETURN

### ISSUE THREAD

**Issue by olalonde** [bitpay/bitcore#1333]
```javascript
var bitcore = require('bitcore');
var Script = bitcore.Script;
var sc = Script.fromString('6a50f4572091308a3065084d8805a70b00070230258e7147152546710d54e148f8d6f591385417713f0fddea794b9bee624eacd80fc76d48bbd7e693ed5e5dee96fbccd3bce7d96a7caaa1b2a326d4a6a9d6');
sc.classify();
// Result: Unknown
// Expected: data
```

**Comment by braydonf** [comment]
80 byte OP_RETURN will classify as data, there is a [test in #isDataOut](https://github.com/bitpay/bitcore/blob/master/test/script/script.js#L233). 

However the opcode 0x50 (80) is reserved, and a opcode (76) OP_PUSHDATA1 can push data on the stack larger than 75.

Taking a look at the script, the first opcode following OP_RETURN is OP_RESERVED and not a pushdata opcode:

```
<Script: OP_RETURN OP_RESERVED 0xf4 OP_7 32 0x91308a3065084d8805a70b00070230258e7147152546710d54e148f8d6f59138 OP_4 23 0x713f0fddea794b9bee624eacd80fc76d48bbd7e693ed5e OP_13 0xee OP_DIV 0xfb 0xcc 0xd3 0xbc 0xe7 0xd9 OP_RETURN OP_SWAP OP_HASH256 OP_LESSTHANOREQUAL OP_NOP3 OP_MIN 38 0xd4a6a9d6>
```

**Comment by olalonde** [comment]
Ah ok, I was under the impression that this was a valid OP_RETURN script. Strangely, it got mined in testnet: https://www.blocktrail.com/tBTC/tx/4577a022790b520c21442e2f812d7a07e551d48e947d58a6fe03e9e3f33cb7e0

**Comment by olalonde** [comment]
Also, bitcoin-core has this test:

https://github.com/bitcoin/bitcoin/blob/ca37e0f33980a1fe96ac4ed08fd7d692a7a592a5/src/test/transaction_tests.cpp#L355

which bitcore classifies as an unknown script.

**Comment by braydonf** [comment]
The script from the above Bitcoin Core test does classify as data:
```js
> var sc = bitcore.Script('6a4c5004678afdb0fe5548271967f1a67130b7105cd6a828e03909a67962e0ea1f61deb649f6bc3f4cef3804678afdb0fe5548271967f1a67130b7105cd6a828e03909a67962e0ea1f61deb649f6bc3f4cef38');
undefined
> sc
<Script: OP_RETURN OP_PUSHDATA1 80 0x04678afdb0fe5548271967f1a67130b7105cd6a828e03909a67962e0ea1f61deb649f6bc3f4cef3804678afdb0fe5548271967f1a67130b7105cd6a828e03909a67962e0ea1f61deb649f6bc3f4cef38>
> sc.classify()
'Data push'
> sc.isDataOut()
true
```

Using this to get the full hex from the test:
```cpp
CScript sc;
sc = CScript() << OP_RETURN << ParseHex("04678afdb0fe5548271967f1a67130b7105cd6a828e03909a67962e0ea1f61deb649f6bc3f4cef3804678afdb0fe5548271967f1a67130b7105cd6a828e03909a67962e0ea1f61deb649f6bc3f4cef38");
std::string scriptHex = HexStr(sc.begin(), sc.end());
```

**Comment by olalonde** [comment]
Oops sorry, seems you are right. Closing this issue.

**Comment by dcousens** [comment]
@olalonde you were missing the `OP_PUSHDATA1`,  `OP_RETURN {DATA}` instead of `OP_RETURN 0x76 {DATA}`
