### ISSUE TITLE
Verifying Signature for a bitcore Transaction

### ISSUE THREAD

**Issue by Christewart** [bitpay/bitcore#1336]
Hi everyone,

I'm trying to verify a signature that I created for a bitcore transaction and then sent over the wire. I am reconstructing the transaction server side with the exact same parameters that were passed to the transaction on the client side. When I ask Bitcore to verify the signature that was sent over the wire, I get the following error: 

Uncaught bitcore.ErrorInvalidArgument: Invalid Argumentmodule.exports.checkArgument @ VM14504 bitcore.js:9875verify @ VM14504 bitcore.js:7999Transaction.verifySignature @ VM14504 bitcore.js:8935(anonymous function) @ VM14697:53(anonymous function) @ bitcore-explorers.min.js:1u @ bitcore-explorers.min.js:1n @ bitcore-explorers.min.js:1

I'm pasting the source file below this line so you can replicate my issue. 

```javascript
/****************************************************************************************************/
var p2shAddress = "2NDwka1gsLhhVDAscCXhFeFRmXJRztJ2DwK"
var user1Pub = "030e7ce7e2694dbfa2bfb3f740c080f0389d59570724bcdd92c60b335984e4db77";
var user2Pub = "030e7ce7e2694dbfa2bfb3f740c080f0389d59570724bcdd92c60b335984e4db77";
var sbPub = "025e9adcc3d65c11346c8a6069d6ebf5b51b348d1d6dc4b95e67480c34dc0bc75c";

var userAddress = "mw3tkWJAkedEHnsRVyVRbsJFEmAEZPgzAY"
var suredBitsAddress = "n3PfhG4MwtGHvffmenirLgKiZ3vHwpQBLL"
var winnings = 200000;
var userSignature = new bitcore.crypto.Signature(JSON.parse(
'{"publicKey":"030e7ce7e2694dbfa2bfb3f740c080f0389d59570724bcdd92c60b335984e4db77","prevTxId":"9df007e38ed5ebc91693351a6b93af8cc27f4f60e824a4a20856cb9cd6b76d02","outputIndex":0,"inputIndex":0,"signature":"30440220407c29165c3174d12458376d909e2f0b3d165e55e16f5a0549338900bf6c882602202d58a11d2c47a5c583ef9a9dee486bbfb557e1febfc11e6ea20f78d7e346885b","sigtype":1}'
));
var requiredSigs = 2; 
var sbPrivateKey = new bitcore.PrivateKey("PRIVATEKEYWIF");
/****************************************************************************************************/
var txFee = new bitcore.Unit(10000, bitcore.Unit.satoshis);
var sbFee = new bitcore.Unit(winnings * 0.01, bitcore.Unit.satoshis);
console.log("extra point fee: " + sbFee)
var userAmount = winnings - txFee.satoshis - sbFee.satoshis
var paymentAmount = new bitcore.Unit(userAmount,bitcore.Unit.satoshis);
insight.getUnspentUtxos(p2shAddress, function(err, utxos) {
	if (err) {
		  throw err;
	} else {
            var multiSigTx;
	    if (sbFee.satoshis > 5460) {
		multiSigTx = new bitcore.Transaction()
		.from(utxos, [user1Pub, user2Pub, sbPub], 2)
		 .to(userAddress, paymentAmount.satoshis)
		 .to(suredBitsAddress, sbFee.satoshis)
		 .fee(txFee)
		 .change(suredBitsAddress).sign(sbPrivateKey);
		console.log(multiSigTx);
		//console.log("User Signature" + userSignature.toString());
		console.log(multiSigTx.verifySignature(userSignature));
		multiSigTx.applySignature(userSignature);
	        console.log("Tx fully signed: " + multiSigTx.isFullySigned());
	        console.log(multiSigTx.serialize());
	    } else {
		//this is the case for when the stakes are so low that a user has a dust output
		//in this case we are ignoring suredbits fee
		//see this question: https://bitcoin.stackexchange.com/questions/32524/bitcoin-transaction-with-dust-output-stuck
		paymentAmount = new bitcore.Unit(paymentAmount.satoshis + sbFee.satoshis, bitcore.Unit.satoshis);
		console.log("Payment amount: " + paymentAmount);
		multiSigTx = new bitcore.Transaction()
		.from(utxos, [user1Pub, user2Pub, sbPub], 2)
		 .to(userAddress, paymentAmount.satoshis)
		 .fee(txFee)
		 .change(suredBitsAddress).sign(sbPrivateKey);
		console.log(multiSigTx);
		console.log(multiSigTx.verifySignature(userSignature));
		multiSigTx.applySignature(userSignature);
	        console.log("Tx fully signed: " + multiSigTx.isFullySigned());
	        console.log(multiSigTx.serialize());
	    }

	}
});
```
The error is specifically occuring on line 51

**Comment by braydonf** [comment]
It looks like the JSON being passed into `bitcore.crypto.Signature` is for `bitcore.Transaction.Signature`. 

Also feel free to post questions, and etc. to https://labs.bitpay.com/c/bitcore

**Comment by Christewart** [comment]
This did not work, I replaced `bitcore.crypto.Signature` with `bitcore.Transaction.Signature` and got the same error.


bitcore.js:9875 Uncaught bitcore.ErrorInvalidArgument: Invalid Argumentmodule.exports.checkArgument @ bitcore.js:9875verify @ bitcore.js:7999Transaction.verifySignature @ bitcore.js:8935(anonymous function) @ VM15137:52(anonymous function) @ bitcore-explorers.min.js:1u @ bitcore-explorers.min.js:1n @ bitcore-explorers.min.js:1
suredbits.wallet.js:200 Finding balance for: mw3tkWJAkedEHnsRVyVRbsJFEmAEZPgzAY

**Comment by braydonf** [comment]
The "public key", "number of the input" and the "subscript" arguments are missing, following the stack trace will reveal the issue. Please see: https://github.com/bitpay/bitcore/blob/master/lib/transaction/transaction.js#L1047 and https://github.com/bitpay/bitcore/blob/master/lib/transaction/sighash.js#L122

Also please see `isValidSignature` on `MultiSigScriptHashInput` for example of how this works:
https://github.com/bitpay/bitcore/blob/master/lib/transaction/input/multisigscripthash.js#L144

**Comment by Christewart** [comment]
I used the `isValidSignature` method and that seems to work for making sure a signature is valid
