### ISSUE TITLE
BAD_SIGNATURES / SERVER_COMPROMISED error code when cosigning/fetching a transaction proposal

### ISSUE THREAD

**Issue by bitalias** [bitpay/bitcore#1341]
Hi,

I have got a 2/3 wallet, created with bitcore-wallet 0.0.7. Using bitcore-wallet-client 0.1.3 to propose+sign and then cosign a transaction. The cosigning part fails with the BAD_SIGNATURES error code. 

Anybody who knows why this is happening? Version incompatibility?
Thankful for any help!

**Comment by bitalias** [comment]
When trying to sign proposal by cosigning Copay client following message appears: 
![could-not-accept-payment-copay](https://cloud.githubusercontent.com/assets/12757135/10270759/22ed00c2-6b26-11e5-927d-d8e931923e59.png)

**Comment by bitalias** [comment]
Upgraded to bitcore-wallet-client 0.6.0 and now having following error message:

{ code: 'SERVER_COMPROMISED',
  message: 'Server response could not be verified' }

Any ideas?

**Comment by isocolsky** [comment]
Hi, are you trying to access a wallet with a previously created pending transaction proposal? We had a report of a similar problem some days ago. It got fixed in bitcore-wallet-client 0.6.4. Could you please try installing that version and check if the problem still persists? Thanks!

**Comment by bitalias** [comment]
No pending transaction proposal. First proposal ever. Bitcore wallet client does not seem to be compatible with bitcore wallet. I have a newer version than 0.6.4 now. If it got fixed downgrading does not seems the right thing to do. Would be awesome to know which versions of BWC work with which versions of BW, so I can install the proper versions...

**Comment by isocolsky** [comment]
I see, will look into the issue ASAP and get back to you.

**Comment by isocolsky** [comment]
I upgraded the bitcore-wallet-client dependency from 0.6.0 to 0.6.4 and did some extensive testing (1-of-1 and multi-sig wallets interacting with the Copay app). Everything works as expected. Could you try the new release bitcore-wallet@0.6.1? If you continue to see the error, could you please describe step-by-step what you are doing so we can try to reproduce the issue?
Thanks.

**Comment by bitalias** [comment]
> 'Hi, are you trying to access a wallet with a previously created pending transaction proposal? We had a report of a similar problem some days ago. It got fixed in bitcore-wallet-client 0.6.4. Could you please try installing that version and check if the problem still persists? Thanks!
Actually this is indeed what happens. One server proposes the transaction and the other server fetches it from BWS and is supposed to cosign it. Afterwards the transaction proposal gets again fetched from the first server to get broadcasted.
So I keep receiving 
>  { code: 'SERVER_COMPROMISED',
  message: 'Server response could not be verified' }
Even after upgrading to 0.6.4 as you suggested. I also reinstalled everything else related.

BTW it seems that I did not use BW 0.0.7, just that the --version flag always returns 0.0.7, another (little) bug since in package.json clearly a nigher version is mentioned?

**Comment by bitalias** [comment]
Something we do differently. Bug still exists. Definetly using 0.6.4 and Bitpay's BWS.

Here is the debug output:

> [debug:unction.Verifier.checkTxProposalBody (/home/wallet/walletPRO/node_modules/bitcore-wallet-client/lib/verifier.js:124:7)] Regenerating & verifying tx proposal hash -> Hash: ["{\"message\":\"{\\\"iv\\\":\\\"DPslcuDJf+5n09ImgrBrpA==\\\",\\\"v\\\":1,\\\"iter\\\":1,\\\"ks\\\":128,\\\"ts\\\":64,\\\"mode\\\":\\\"ccm\\\",\\\"adata\\\":\\\"\\\",\\\"cipher\\\":\\\"aes\\\",\\\"ct\\\":\\\"ABiyfF79RrRZDeXP6ztSMQvCLgbyOJpeQl2jz7TdNjsMcQ0=\\\"}\",\"outputs\":[{\"amount\":1000,\"message\":\"{\\\"iv\\\":\\\"Fc+XsTUmUAO95xCfe3ALYQ==\\\",\\\"v\\\":1,\\\"iter\\\":1,\\\"ks\\\":128,\\\"ts\\\":64,\\\"mode\\\":\\\"ccm\\\",\\\"adata\\\":\\\"\\\",\\\"cipher\\\":\\\"aes\\\",\\\"ct\\\":\\\"XLmGGqCc/XCJFVnp4Wkb6CVCo0yx7zHA3KjInktnOz5mpqRctvQ67hBhxUeCcWApcySVtqSgw00eYZ5T1XOw72nc777tIZEQDuI6QvJu0lvhOTaGT+Qs4v6obHBDOkRs55MmacHT3IWLorRux8rOAm1IweQDM+tu5y7CfOSabd1ahIw0LL+DCFLWoca+NGh+4rmKB2Xb515wwQAhY60sirRBD8r84m6xWzcyqd5Ss3zvpQ9FW3yGC2HZhd61aRMpvWAWfJpfG++l+B9vSUkK/p6gQOC4pLe3Tg==\\\"}\",\"toAddress\":\"3EysCGt78T5svgxc5eZMaUjgGL1tuMmGc6\"}],\"payProUrl\":null}"," Signature: ","304402207880f4a0fdb61f03f762c7b7b69755b22eee6d79d88aa2c24a29de9822c19957022001f2cf2ca9ff2a01b04190ce3aba8722c51ae4cdf4d0bc43208d1722455eac8a"]

returns error
> { code: 'SERVER_COMPROMISED',
  message: 'Server response could not be verified' }

**Comment by bitalias** [comment]
Figure out what is failing:
> if (!WalletUtils.verifyMessage(hash, txp.proposalSignature, creatorSigningPubKey))
   return false;
is returning indeed false (in lib/verifier.js)

How come? When we switch this check off, what are the security implications?

**Comment by isocolsky** [comment]
Thank you for the detailed info. I still cannot reproduce the issue. How are you generating the proposal? Bitcore Wallet does not support multiple_output proposals yet. Are you going through BWC or are you using BWS REST API?

**Comment by isocolsky** [comment]
>When we switch this check off, what are the security implications?

The purpose of this check is so each user can verify that a given tx proposal is actually coming from one of their copayers. If removed, the user is vulnerable to an attack from a compromised server that could send a fake tx proposal on behalf of one of the copayers for the user to sign.

**Comment by bitalias** [comment]
> How are you generating the proposal? Bitcore Wallet does not support multiple_output proposals yet. Are you going through BWC or are you using BWS REST API?

Using BWC 0.6.4. Compatibility issue with BW and BWC disappeared after upgrading to the newest version. Keys also get created with BWC. With BW I can read the tx-proposal, no warnings.

**Comment by matiu** [comment]
This issue is probably related with https://github.com/bitpay/bitcore-wallet-client/pull/170

Could you check again using BWC master at BW? Please note that the tx proposal need to be created again.

**Comment by matiu** [comment]
closing this one one, in favor of: https://github.com/bitpay/bitcore-wallet-client/issues/155
