### ISSUE TITLE
Address generated not match with Armory

### ISSUE THREAD

**Issue by nemesisqp** [bitpay/bitcore#1344]
Why address generated in bitcore not match with address from Amory when I import private key ?
example with private key (gen in bitcore):
```
3c46815ae7273fed5781c67c103df96edc452b422a142667108777eb1d9deb07
```
address in bitcore is : 
```
17iWvek2RcKHBfWjzqmbDM5b2fk2j7Vxgg
```
but in armory address is: 
```
1LWpfJ2vsDmiAP7kaKkbATRaSHN3h7Zdfi
```
or
```
1PeHpf3ScTCvQw2GeNKQ9yFTHAKCk3MTsG
```

**Comment by fanatid** [comment]
I imported your private key in bitcoind (v0.11.0) and get address matched with bitcore address.

```js
var pkHex = '3c46815ae7273fed5781c67c103df96edc452b422a142667108777eb1d9deb07'
var pk = require('bitcore').PrivateKey(pkHex)
console.log(pk.toWIF()) // KyEsuCtugk6SBaFxPeQgd8qTjqReadfs9KFVk8jdwepRVXCjmMSJ
console.log(pk.toAddress().toString()) // 17iWvek2RcKHBfWjzqmbDM5b2fk2j7Vxgg
```

```bash
$ bitcoind -daemon
Bitcoin server starting
$ bitcoin-cli getaddressesbyaccount ''
[
    "18iNYGGLJSNGScoCExAEBxWW9jMRRdM2LT"
]
$ bitcoin-cli importprivkey KyEsuCtugk6SBaFxPeQgd8qTjqReadfs9KFVk8jdwepRVXCjmMSJ
$ bitcoin-cli getaddressesbyaccount ''
[
    "17iWvek2RcKHBfWjzqmbDM5b2fk2j7Vxgg",
    "18iNYGGLJSNGScoCExAEBxWW9jMRRdM2LT"
]
```

Probably you should ask this question in armory bug-tracker.

**Comment by nemesisqp** [comment]
Thanks, I will do that

**Comment by nemesisqp** [comment]
It seem this is just compressed, uncompressed public key problem :D

**Comment by braydonf** [comment]
Glad to hear this was solved. For reference, uncompressed public keys are supported for that use-case, however discouraged because of the confusion: https://github.com/bitpay/bitcore/blob/master/docs/publickey.md#compressed-vs-uncompressed
