### ISSUE TITLE
BIP37 create address, list transactions, send

### ISSUE THREAD

**Issue by runvnc** [bitpay/bitcore#1351]
Hello, looking for a clear explanation or links to some simple explanations for the following use case:

I would like to build a module or a cli with bitcore that is a lightweight client using BIP37 in order to create addresses, receive and log only relevant transactions (using BIP 37), and send money out. 

I saw something on a related project (bitcore-p2p) but it seems fairly complex and I'm not sure if I'm supposed to include only bitcore-p2p or also use bitcore.  Or is that just a flag for the bitcore cli?

I actually don't know if this might be a configuration flag (to use BIP37 rather than full node) or what.

Thanks for any help.

**Comment by braydonf** [comment]
BIP37 is implemented in bitcore-lib and bitcore-p2p. Though it sounds like you're referring to an fully implemented SPV client, which there isn't an option for currently, there have been a few people discussing such at https://forum.bitcore.io/
