### ISSUE TITLE
More informative logging during startup

### ISSUE THREAD

**Issue by bitjson** [bitpay/bitcore#1363]
I'm still syncing the blockchain – when I start `bitcored`, I see the output:
```bash
info: Starting bitcoind
```
After perhaps 45 seconds, `info: Bitcoin Daemon Ready` is logged. I believe Bitcoind is `Validating Blocks` (the message I get in the Qt client), but I'm getting very little feedback during that time. Is it possible for us to provide more logging there?

**Comment by bitjson** [comment]
(continued)
```
$ bitcored
[2015-10-25T17:56:03.815Z] info: Starting bitcoind
[2015-10-25T17:56:38.878Z] info: Bitcoin Daemon Ready
```
So ~30 second delay in which nothing is logged. It'd be great if the user could better understand what's happening – a progress indicator would be excellent.

**Comment by braydonf** [comment]
Usually the startup is fairly quick. Are you running with a test build with the wallet enabled? That will slow down startup.

**Comment by bitjson** [comment]
I was on Mac OS X 10.10, Node v0.12.7, fresh install of bitcore via:

```
$ npm install -g bitcore
$ bitcored
```

Still same behavior on OS X 10.11.1. Plenty of memory and CPU. Is there any other info that would be helpful?

**Comment by braydonf** [comment]
Here is the area of code it is in: https://github.com/bitpay/bitcore-node/blob/master/src/libbitcoind.cc#L401

It waits for `chainActive` and `mapBlockIndex` to be fully loaded.

**Comment by braydonf** [comment]
There is more information displayed during startup now.
