### ISSUE TITLE
npm install -g bitcore ERROR:

### ISSUE THREAD

**Issue by chris-vl** [bitpay/bitcore#1364]
I try to install and i get the following errors below | Also i dont receive email for bitcore forum activation
root@train:~# npm install -g bitcore
npm ERR! Linux 3.19.0-30-generic
npm ERR! argv "/root/.nvm/versions/v0.12.0/bin/node" "/root/.nvm/versions/v0.12.0/bin/npm" "install" "-g" "bitcore"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code EBADPLATFORM

npm ERR! notsup Unsupported
npm ERR! notsup Not compatible with your operating system or architecture: bitcore-node@0.2.5
npm ERR! notsup Valid OS:    darwin,linux
npm ERR! notsup Valid Arch:  x64
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: ia32

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log
root@vultr:~# nano /root/npm-debug.log

**Comment by dabura667** [comment]
Looks like it only supports 64 bit OSes.

**Comment by chris-vl** [comment]
switced to 64 bit 
root@train:~# npm install -g bitcore
|
> utf-8-validate@1.2.1 install /root/.nvm/v0.12.7/lib/node_modules/bitcore/node_modules/bitcore-node/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate
> prebuild --download

sh: 1: prebuild: Permission denied

> bufferutil@1.2.1 install /root/.nvm/v0.12.7/lib/node_modules/bitcore/node_modules/bitcore-node/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil
> prebuild --download

sh: 1: prebuild: Permission denied
npm WARN optional dep failed, continuing utf-8-validate@1.2.1

> bufferutil@1.2.1 install /root/.nvm/v0.12.7/lib/node_modules/bitcore/node_modules/bitcore-node/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil
> prebuild --download

sh: 1: prebuild: Permission denied
npm WARN optional dep failed, continuing bufferutil@1.2.1

> bufferutil@1.2.1 install /root/.nvm/v0.12.7/lib/node_modules/bitcore/node_modules/bitcore-node/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil
> prebuild --download

sh: 1: prebuild: Permission denied
npm WARN optional dep failed, continuing bufferutil@1.2.1

> utf-8-validate@1.2.1 install /root/.nvm/v0.12.7/lib/node_modules/bitcore/node_modules/bitcore-node/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate
> prebuild --download

sh: 1: prebuild: Permission denied
npm WARN optional dep failed, continuing bufferutil@1.2.1

> utf-8-validate@1.2.1 install /root/.nvm/v0.12.7/lib/node_modules/bitcore/node_modules/bitcore-node/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate
> prebuild --download

sh: 1: prebuild: Permission denied
npm WARN optional dep failed, continuing utf-8-validate@1.2.1
npm WARN optional dep failed, continuing utf-8-validate@1.2.1

> leveldown@1.4.2 install /root/.nvm/v0.12.7/lib/node_modules/bitcore/node_modules/bitcore-node/node_modules/leveldown
> prebuild --download

sh: 1: prebuild: Permission denied
npm ERR! Linux 3.19.0-30-generic
npm ERR! argv "/root/.nvm/v0.12.7/bin/node" "/root/.nvm/v0.12.7/bin/npm" "install" "-g" "bitcore"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! leveldown@1.4.2 install: `prebuild --download`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the leveldown@1.4.2 install script 'prebuild --download'.
npm ERR! This is most likely a problem with the leveldown package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild --download
npm ERR! You can get their info via:
npm ERR!     npm owner ls leveldown
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log
root@train:~#

**Comment by kleetus** [comment]
that is interesting...I noticed that you are using root user with nvm. I am
not sure exactly what difference that would make, but have you attempted
using a non-privileged user with nvm to install bitcore? In general, this
would be advisable anyway.



On Sun, Oct 25, 2015 at 6:57 AM, chris-vl <notifications@github.com> wrote:

> switced to 64 bit
> root@train:~# npm install -g bitcore
> |
>
> utf-8-validate@1.2.1 install
> /root/.nvm/v0.12.7/lib/node_modules/bitcore/node_modules/bitcore-node/node_modules/
> socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate
> prebuild --download
>
> sh: 1: prebuild: Permission denied
>
> bufferutil@1.2.1 install
> /root/.nvm/v0.12.7/lib/node_modules/bitcore/node_modules/bitcore-node/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil
> prebuild --download
>
> sh: 1: prebuild: Permission denied
> npm WARN optional dep failed, continuing utf-8-validate@1.2.1
>
> bufferutil@1.2.1 install
> /root/.nvm/v0.12.7/lib/node_modules/bitcore/node_modules/bitcore-node/node_modules/
> socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil
> prebuild --download
>
> sh: 1: prebuild: Permission denied
> npm WARN optional dep failed, continuing bufferutil@1.2.1
>
> bufferutil@1.2.1 install
> /root/.nvm/v0.12.7/lib/node_modules/bitcore/node_modules/bitcore-node/node_modules/
> socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil
> prebuild --download
>
> sh: 1: prebuild: Permission denied
> npm WARN optional dep failed, continuing bufferutil@1.2.1
>
> utf-8-validate@1.2.1 install
> /root/.nvm/v0.12.7/lib/node_modules/bitcore/node_modules/bitcore-node/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate
> prebuild --download
>
> sh: 1: prebuild: Permission denied
> npm WARN optional dep failed, continuing bufferutil@1.2.1
>
> utf-8-validate@1.2.1 install
> /root/.nvm/v0.12.7/lib/node_modules/bitcore/node_modules/bitcore-node/node_modules/
> socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate
> prebuild --download
>
> sh: 1: prebuild: Permission denied
> npm WARN optional dep failed, continuing utf-8-validate@1.2.1
> npm WARN optional dep failed, continuing utf-8-validate@1.2.1
>
> leveldown@1.4.2 install
> /root/.nvm/v0.12.7/lib/node_modules/bitcore/node_modules/bitcore-node/node_modules/leveldown
> prebuild --download
>
> sh: 1: prebuild: Permission denied
> npm ERR! Linux 3.19.0-30-generic
> npm ERR! argv "/root/.nvm/v0.12.7/bin/node" "/root/.nvm/v0.12.7/bin/npm"
> "install" "-g" "bitcore"
> npm ERR! node v0.12.7
> npm ERR! npm v2.11.3
> npm ERR! file sh
> npm ERR! code ELIFECYCLE
> npm ERR! errno ENOENT
> npm ERR! syscall spawn
>
> npm ERR! leveldown@1.4.2 install: prebuild --download
> npm ERR! spawn ENOENT
> npm ERR!
> npm ERR! Failed at the leveldown@1.4.2 install script 'prebuild
> --download'.
> npm ERR! This is most likely a problem with the leveldown package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR! prebuild --download
> npm ERR! You can get their info via:
> npm ERR! npm owner ls leveldown
> npm ERR! There is likely additional logging output above.
>
> npm ERR! Please include the following file with any support request:
> npm ERR! /root/npm-debug.log
> root@train:~#
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/bitcore/issues/1364#issuecomment-150912143>.
>



-- 
Chris Kleeschulte
KK4DYJ


Please note that I only check email twice per day; once at 12pm and at 7pm
US Eastern Time, Monday - Friday. If your email is a true emergency, please
call me at my desk right away. I appreciate your patience.

-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v1

mQENBFVGpOYBCACWr+/tba3xKXvF77GAFLvpazyNfxsHAbzFLNCV/UgFycKhD5ZY
BbTctpXXKASqfHF7aiTqfQo74catqfCtvMt5zdDwfHdiFvg1M8B6Lsqp4uUU8y/F
nVXDIASEpvdl5Hki8GOVpIwtWiZxMeqPvUGKV0mCelOtvzLILNILjIYnw4YIFrea
UvHAOZ6ggd0xXeqIeSsONgZqDRpLRvDF22kzIlxZE965la6u+k/InYHQJh6Q2tPN
Sk/jW6J06F7mJ7GRBhV9KKFYW9tUTc7CqdhKrN+PNVkXdrGi4j7Zmk3PIBiUHwM2
Cm8+d0rlWqv//UpRJFV2KXAPty2m728AiuMxABEBAAG0JUNocmlzIEtsZWVzY2h1
bHRlIDxsYWNvbmlhQGdtYWlsLmNvbT6JATgEEwECACIFAlVGpOYCGwMGCwkIBwMC
BhUIAgkKCwQWAgMBAh4BAheAAAoJEEVidVpzVuRYFGMH/0Fybe0S6gdhXnm6ofEJ
RrU+oC+ufD3QEo5YHcHPEjgvt+x4fBLBSXZAnulNdzwacf2yqonNU5T8JtlX2cr3
swBvpfbdVGUDpSWt1anBoTJ+lFbUE/DkYHCIdcZeCCqO/gJdSNn3KxxvVE/g3pDN
xAYATWoopfG0U8xCLgQbV+cC0qTDfkSj1BZOHISMIoshXmkaZfWrH+oUMBK/Dw1C
0Zp6NDPgme/E6p2D0o3xjQpSy4mPd/1Bq6AsD5I2SoHXwLU5V7O1b+o8/9yrMUkv
jArEE4aLeTD6FxUNfRehDYeWuStp1sczWsG3ZngQwaaBWayey2kweD1AmQ941NN5
Jp+5AQ0EVUak5gEIAJ/IyDrwwY4i4XuLVX/bRMIS+7dJHJh19hkvhbTOynIrXQcl
sbJI/l9uDDGTbRDORUGvwQLOAFU/xvXNMb/CuESThvdcRBAq7sVGIjOl22itF+Wc
BslXWWAfnuHmw1CZ5N3qXbUG7zvuti/Wgg5bZj6Gfld41mNP3V2juFPIcs/pyKtf
hcJ92/TppuxC4DIqlugBk+51jAoSVJb8814A8hqlcndtMzb8Xt0+T8vqPS4aSjkz
MS42ijQpXFv3LJCTGrwSJbsMj+GHb0Lw+a+bFqbp6LE2g5fJiKPZUoGNSsa+/J3n
hP3qFTPuib7awZIQFp281lICsYmRNCGWe+gYNZkAEQEAAYkBHwQYAQIACQUCVUak
5gIbDAAKCRBFYnVac1bkWHhLB/0WvIzS+8pNmLmlgtVbMyQtlNAkmSnamYom+8jL
DdhHd4s1xc3i1ACQLzfojuYFvFWEt5pIS15Qdvu+31SJ03VY/jaYW0nycdb+W8wD
rg53PBrChka7j6Lg1ANKFJq1s7cMVyvumAXPqjjjDGIh021im+WhNDvLGi2BCW17
50a4YL6Iv7q76z6rqbgh1txbZ5QLJXX11xtikiD2SGxACoYAxIjFl+lyZI7SIX5h
dhOfNdwAYnfEWimKl4NCGtQC7lE9dPfDya2lk+FxJQpl/lmJTspAt43kBMoYZ4xG
MDAO12PmRSQHhqfVgwHX0f2Y11PC011vd0fTlhOtxdARiA20
=L/YR
-----END PGP PUBLIC KEY BLOCK-----

**Comment by chris-vl** [comment]
Thanks i need bicore to run insight for some tests
i install it with:
curl https://raw.githubusercontent.com/creationix/nvm/v0.23.2/install.sh | bash
source ~/.bashrc
apt-get install npm
apt-get install git
nvm install v0.12.7
npm install bitcore
cd node_modules/bitcore/bin
./bitcored
