### ISSUE TITLE
"Error: More than one instance of bitcore-lib found. Please make sure to require bitcore-lib and check that submodules do not also include their own bitcore-lib dependency."

### ISSUE THREAD

**Issue by LAMike310** [bitpay/bitcore#1366]
Hi,

I started a new EC2 instance, and I did a fresh install of node, git and nvm. I set the nvm to 0.12, and I did a sudo npm intsall bitcore and sudo npm install bitcore-explorers, along with a few other modules needed for my script. When I run the script, I get this error:

"Error: More than one instance of bitcore-lib found. Please make sure to require bitcore-lib and check that submodules do not also include their own bitcore-lib dependency."

How can I fix this? Has anyone else run into a similar situation?

I'm using Ubunti 14.04 btw, and the script works fine on my local machine. 

Thanks,

Mike

**Comment by braydonf** [comment]
You may run into issues when installing multiple modules globally, as the bitcore-lib won't be shared across them, each with another instance of bitcore-lib, which will lead to issues with `instanceof` type handling when objects are passed between modules. More info: https://github.com/bitpay/bitcore/issues/1328

**Comment by LAMike310** [comment]
So starting from a fresh AWS instance of Ubuntu 14.04, what would be a good way to install bitcore and bitcore explorers in a way that doesn't cause any errrors?

**Comment by braydonf** [comment]
Are you trying to setup a full node?

https://bitcore.io/guides/full-node

**Comment by LAMike310** [comment]
No I'm just trying to use the Bitcore Explorers API to look up UTXOs and create transactions.

**Comment by LAMike310** [comment]
Oh maybe I can just use:

var bitcore = require('bitcore-lib');

instead of 

var bitcore = require('bitcore')


I will test that out when I get home

**Comment by Levino** [comment]
This include guard stuff is really weird. Why do you have to do that? Nobody else is doing it in an npm package...

**Comment by fanatid** [comment]
@Levino 
https://github.com/bitpay/bitcore-lib/blob/master/lib/transaction/transaction.js#L612
https://github.com/bitpay/bitcore-lib/blob/master/lib/transaction/transaction.js#L45
In total I found 87 lines where instanceof used with class from `bitcore-lib`.

**Comment by Levino** [comment]
@fanatid Sorry, but I do not see the connection here? One cannot include (require) bitcore twice. It is setting a global variable "bitcore" and checks for it "not being present". The only reason behind this can be, that bitcore relies on global variables, which it should not. Checking for the type of instance should work anyhow, shouldn't it?

**Comment by fanatid** [comment]
If you have two or more bitcore-lib instances than instanceof not worked.
details: https://github.com/bitpay/bitcore/issues/1164

**Comment by cosmoarunn** [comment]
The error thrown from index.js file, 

````
bitcore.versionGuard = function(version) {
  if (version !== undefined) {
    var message = 'More than one instance of bitcore-lib found. ' + 
      'Please make sure to require bitcore-lib and check that submodules do' +
      ' not also include their own bitcore-lib dependency.';
    throw new Error(message);
  }
};
````

you can either update the version or mark it 'undefined'.
PS: (It's not an issue of installing bitcore globally )

**Comment by Levino** [comment]
No other library in the world does this. Should be removed.

**Comment by fanatid** [comment]
How much libraries in the world uses `instanceof` for type checking?

**Comment by oojr** [comment]
@braydonf whats the solution? I am using bitcore-lib and bitcore-explorers and receiving this error

**Comment by askucher** [comment]
this validation should be removed

**Comment by dabura667** [comment]
Yeah it should... from your project folder run this as a temp solution:

```bash
find ./node_modules -type f -print0 | xargs -0 sed -i 's/global\._bitcore/__NULLVARsdfs6d/g'
```

**Comment by red-name** [comment]
So how can one use `bitcore-lib` and `bitcore-explorers` together?

I need this to read UTXOs and create transactions.
