### ISSUE TITLE
Support BIP101

### ISSUE THREAD

**Issue by toomim** [bitpay/bitcore#1370]
It's time to [support BIP101](https://medium.com/@spair/increasing-the-block-size-limit-85ff236fc516) in Bitpay code!

[BIP101 has activated on testnet](https://www.reddit.com/r/btc/comments/3s0zh8/bip101_has_activated_on_testnet_bigger_blocks/). The chain is about to fork into a big blockchain and a small blockchain. However, Bitpay's code will only be able to see the big blocks if it supports BIP101. Does Bitcore support BIP101?

The [docs say](https://github.com/bitpay/bitcore-node/blob/master/docs/services/bitcoind.md) that [bitcore-node](https://github.com/bitpay/bitcore-node) interfaces with [Bitcoin Core](https://github.com/bitcoin/bitcoin). Can it interface with [Bitcoin XT](https://github.com/bitcoinxt/bitcoinxt)? Can we update the docs?

There may be a fork tomorrow morning. If https://test-insight.bitpay.com/ gets onto BIP101 in time, we'll be able to watch the first forked blocks on Bitpay Insight!

**Comment by jtoomim** [comment]
I think we can close this now. Yes?

**Comment by toomim** [comment]
Maybe once BIP101 support is in master? If you check out this repo, I think it installs core w/o BIP101.

**Comment by kleetus** [comment]
The BIP 101 changes that we've made (https://github.com/bitpay/bitcore-node/tree/0.11.1-big-blocks) may not be merged right away, we need to edit docs, write tests, confer with the business and some other things. For right now, we are running the BIP 101 at test-insight.bitpay.com. This will be our proving ground while we prepare for what's next.

**Comment by jtoomim** [comment]
Okay.

It seems that test-insight is not following the rest of the BIP101 network. We're on block 586925 right now, and have a lot more work than the longer branch you're apparently following. Perhaps you could add one of these nodes?

69.90.132.200
79.143.179.215
45.79.162.82

**Comment by kleetus** [comment]
I'll take a look, thanks for the update.

**Comment by jtoomim** [comment]
We're in #bitcoinxt on freenode doing testing.

**Comment by kleetus** [comment]
I think I missed the boat on this one. On the one hand, test-insight IS accepting big blocks, theoretically, however, I did NOT take your advice and connect to your test peers. After review, the peers that I was connected to never relayed those blocks to me. On the other hand, I shouldn't be using this host in this way anyway. So, I spun up a new host (outbound only) and connected to your peers. If there is another test, I should be prepared. thanks for your hard work on this.

**Comment by jtoomim** [comment]
Thanks, no worries. The last two days have been mostly for testing out the waters. We'll be doing more tests for sure. For now, we're going to focus on building tools to collect data and manage our servers better. Block propagation times are the main concern re: BIP101, so that's what we're going to try to measure well. Doing so will take some work. There will be light testing for the next few days, then probably some more intensive testing after that.

By the way, I've been wanting to talk with someone at BitPay about 0-conf transaction security. The mempool eviction policies that have been recently added to XT and expecially to Core have some implications that I think could be a concern to 0-conf processors like BitPay. Could you have someone email me at j@toom.im, or send me their email address?

**Comment by rromanchuk** [comment]
Hey guys, thanks for all the help in this. I'm running bitcore-node built from bitcore/bitcoin PATCH 0.11.1-big-blocks on http://insight.trytipper.com:3001/insight/ and on the correct chain.  I tried building against  https://github.com/jtoomim/bitcoinxt  PATCH fortestnet, but got a build failure posted below. 


```
109509 info bitcore-node@1.0.0-dev Failed to exec install script
109510 verbose stack Error: bitcore-node@1.0.0-dev install: `./bin/install`
109510 verbose stack Exit status 255
109510 verbose stack     at EventEmitter.<anonymous> (/Users/ryan/.nvm/versions/node/v4.2.2/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
109510 verbose stack     at emitTwo (events.js:87:13)
109510 verbose stack     at EventEmitter.emit (events.js:172:7)
109510 verbose stack     at ChildProcess.<anonymous> (/Users/ryan/.nvm/versions/node/v4.2.2/lib/node_modules/npm/lib/utils/spawn.js:24:14)
109510 verbose stack     at emitTwo (events.js:87:13)
109510 verbose stack     at ChildProcess.emit (events.js:172:7)
109510 verbose stack     at maybeClose (internal/child_process.js:818:16)
109510 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
109511 verbose pkgid bitcore-node@1.0.0-dev
109512 verbose cwd /Users/ryan/bitcoinxt-dev/bitcore-node
109513 error Darwin 15.2.0
109514 error argv "/Users/ryan/.nvm/versions/node/v4.2.2/bin/node" "/Users/ryan/.nvm/versions/node/v4.2.2/bin/npm" "install"
109515 error node v4.2.2
109516 error npm  v2.14.7
109517 error code ELIFECYCLE
109518 error bitcore-node@1.0.0-dev install: `./bin/install`
109518 error Exit status 255
109519 error Failed at the bitcore-node@1.0.0-dev install script './bin/install'.
109519 error This is most likely a problem with the bitcore-node package,
109519 error not with npm itself.
109519 error Tell the author that this fails on your system:
109519 error     ./bin/install
109519 error You can get their info via:
109519 error     npm owner ls bitcore-node
109519 error There is likely additional logging output above.
109520 verbose exit [ 1, true ]
```

Any hints you can tell me for debugging? Or... there any way you can merge upstream 0.11.2 into a big-blocks branch?

**Comment by kleetus** [comment]
I will merge 0.11.2 into the big-blocks branch.

**Comment by braydonf** [comment]
Closing as BIP101 has been marked as withdrawn: https://github.com/bitcoin/bips/blob/master/bip-0101.mediawiki
