### ISSUE TITLE
Cannot install Bitcore on ARM?

### ISSUE THREAD

**Issue by LAMike310** [bitpay/bitcore#1373]
When attempting to install bitcore using npm, it says that the package cannot be installed on the arm architecture.  Do you have a suggested workaround or alternative for this?  Here's what's in the console.log:

twenty@bitcoin-computer:~/HelloSatoshi$ npm install bitcore
npm ERR! Linux 4.1.11-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "bitcore"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code EBADPLATFORM

npm ERR! notsup Unsupported
npm ERR! notsup Not compatible with your operating system or architecture: bitcore-node@1.0.0
npm ERR! notsup Valid OS:    darwin,linux
npm ERR! notsup Valid Arch:  x64
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: arm

npm ERR! Please include the following file with any support request:
npm ERR!     /home/twenty/HelloSatoshi/npm-debug.log

Any solution to this answer will get $10 in Bitcoin!

**Comment by Levino** [comment]
Probably the linked bitcoind lib does not work on ARM. The one for ARM should also be linked. Want to use this too on my Odroid U3.

**Comment by braydonf** [comment]
It's possible to compile for ARM, however there are a few tweaks that need to be made to get this to work. @kleetus has started work on this and has been testing.

**Comment by kleetus** [comment]
that's true, I did have a patch to support ARM and Windows. It won't be merged upstream any time soon. but, you can always check out my branch:

https://github.com/kleetus/bitcore-node/tree/feature/arm_support

I don't keep it up to date with bitpay/master, but most the changes are just in the build shell script.
