### ISSUE TITLE
Can I save the Blockchain on a Flash drive with Bitcore?

### ISSUE THREAD

**Issue by LAMike310** [bitpay/bitcore#1379]
Hello,

I was thinking of using a Raspberry Pi with Bitcore, but the only way I can pull it off is if I use an external flash drive to store the Blockchain. Is that possible? 

Thanks,

Mike

**Comment by braydonf** [comment]
Yes, this is possible. However performance may be affected.

**Comment by braydonf** [comment]
Also there can be memory issues while running on a Raspberry Pi, though generally it can run below 1GB, it can often exceed this limit.

**Comment by LAMike310** [comment]
Thanks @braydonf, the Raspberry Pi might not be the best tool for this job, but I may go with the Pine64+ instead.

So after the NPM install of Bitcore, is there something I can write in the command line to make the Blockchain download on the external drive?

Thanks,

Mike

**Comment by braydonf** [comment]
You'll just need to set the data directory in bitcore-node.json file to the location.
