### ISSUE TITLE
Unable to install bitcore on Windows 10 x64

### ISSUE THREAD

**Issue by bedeho** [bitpay/bitcore#1381]
C:\Users\mender>npm install -g bitcore
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "bitcore"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12
npm ERR! code EBADPLATFORM

npm ERR! notsup Unsupported
npm ERR! notsup Not compatible with your operating system or architecture: bitcore-node@1.0.1
npm ERR! notsup Valid OS:    darwin,linux
npm ERR! notsup Valid Arch:  x64
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\mender\npm-debug.log

**Comment by kleetus** [comment]
yeah sorry about that, Window's isn't currently supported but you can checkout my branch, https://github.com/kleetus/bitcore-node/tree/feature/arm_support

this will show you how to change the build scripts to make this work. Theoretically, if its supported by Bitcoin, then you can massage the build scripts to get it to work for Bitcore.
