### ISSUE TITLE
Any chance we could get our project listed on the Applications section of the README? We're 100% bitcore

### ISSUE THREAD

**Issue by ScroogeMcDuckButWithBitcoin** [bitpay/bitcore#1382]
And for that matter, 100% bitcoin. We just released our first npm version, with almost all of the functionality defined in the white paper. Care to take a look and see what you think?

https://github.com/17Q4MX2hmktmpuUKHFuoRmS5MfB5XPbhod/dropzone-lib

(Also - thank-you so much everyone for giving us this great library)

**Comment by braydonf** [comment]
Thanks! Unfortunately list of applications isn't comprehensive, and as of yet doesn't include third-party applications.
