### ISSUE TITLE
Build error on Mac OS X 10.11

### ISSUE THREAD

**Issue by CarlosFaria94** [bitpay/bitcore#1385]
Hi there!

I have a problem building bitcore, the problem comes from leveldown@1.4.4

log:

> 39332 verbose stack Error: leveldown@1.4.4 install: `prebuild --install`
> 39332 verbose stack Exit status 2
> 39332 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
> 39332 verbose stack     at emitTwo (events.js:87:13)
> 39332 verbose stack     at EventEmitter.emit (events.js:172:7)
> 39332 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
> 39332 verbose stack     at emitTwo (events.js:87:13)
> 39332 verbose stack     at ChildProcess.emit (events.js:172:7)
> 39332 verbose stack     at maybeClose (internal/child_process.js:821:16)
> 39332 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
> 39333 verbose pkgid leveldown@1.4.4
> 39334 verbose cwd /Users/carlosfaria/Desktop/bitcore
> 39335 error Darwin 15.3.0
> 39336 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "bitcore"
> 39337 error **node v4.2.6**
> 39338 error **npm  v3.6.0**
> 39339 error code ELIFECYCLE
> 39340 error leveldown@1.4.4 install: `prebuild --install`
> 39340 error Exit status 2
> 39341 error Failed at the leveldown@1.4.4 install script 'prebuild --install'.
> 39341 error Make sure you have the latest version of node.js and npm installed.
> 39341 error If you do, this is most likely a problem with the leveldown package,
> 39341 error not with npm itself.
> 39341 error Tell the author that this fails on your system:
> 39341 error     prebuild --install
> 39341 error You can get information on how to open an issue for this project with:
> 39341 error     npm bugs leveldown
> 39341 error Or if that isn't available, you can get their info via:
> 39341 error     npm owner ls leveldown
> 39341 error There is likely additional logging output above.
> 39342 verbose exit [ 1, true ]

**Comment by kleetus** [comment]
Can you provide the entire output of npm install bitcore? There is something going on above where you cut and paste, more than likely.

**Comment by CarlosFaria94** [comment]
It's here: [npm-debug.txt](https://github.com/bitpay/bitcore/files/114378/npm-debug.txt)

**Comment by kleetus** [comment]
I noticed that I had neglected to do a prebuild of leveldown for node v0.12 for darwin. I just did this. I am curious, however, why the build did not default to building from source. Maybe you don't have Xcode or the command line tools installed? The upload of leveldown for node v0.12 would not help you because you are using node v4.2.6. I don't have any 10.11 machines around to test with, but you could try: 

$ npm cache clean
 
then:

$ sudo npm install bitcore -g

you might something like this:

prebuild WARN install EACCES: permission denied, access '/Users/user/.npm'

If this still does not work, then please let me upgrade this machine to 10.11 and find out what may be going on.

**Comment by CarlosFaria94** [comment]
I have Xcode, but apparently I had not installed command line tools, so I installed and try clean npm cache. But still does not work.

[npm-debug.txt](https://github.com/bitpay/bitcore/files/114755/npm-debug.txt)

**Comment by kleetus** [comment]
I am curious if you tried installing with (if you are installing as root, not sudo):

unsafe-perm

as such:

# npm install --unsafe-perm -g bitcore

I am not sure exactly what command you are running to install, meaning if you are installing as the root user, then you will have to tell npm to use unsafe-perm.

You can also think about using nvm:

https://github.com/creationix/nvm

**Comment by braydonf** [comment]
Just tested installing with node@4.2.6 and npm@3.6.0 and osx@10.10.3 and all went well.

**Comment by CarlosFaria94** [comment]
Problem solved. I noticed that I was using sudo. Sorry, my fault.
