### ISSUE TITLE
Assertion when syncing livenet 

### ISSUE THREAD

**Issue by matiu** [bitpay/bitcore#1386]
[2016-02-03T15:43:15.794Z] info: Bitcoin Height: 207885 Percentage: 3.7537741661071777
Assertion failed: (prev->next_ != end), function delete_nodes, file /Users/chrisk/source/zzbitcore_node/bin/../libbitcoind/depends/x86_64-darwin/include/boost/unordered/detail/table.hpp, line 537.
Abort trap: 6

**Comment by matiu** [comment]
Actually, this happens seconds after querying ~2K addresses in insight.

The log shows:
```
IO error: /xxx/.bitcore/data/bitcore-node.db/034893.ldb: Too many open files in system
```

**Comment by braydonf** [comment]
`bitcore-node.db` is no longer used, and syncing is with bitcoind.

**Comment by zazuuu** [comment]
не чего не могу понять
