### ISSUE TITLE
ncaught bitcore.ErrorInvalidState: Invalid state: undefined

### ISSUE THREAD

**Issue by off-bank** [bitpay/bitcore#1388]
Why this throws me "ncaught bitcore.ErrorInvalidState: Invalid state: undefined"? Do I need sighash defined?

`var bitcore = require('bitcore-lib');
var mytx='010000000171575c7585d347a2d31a09973bd118ea45083592f873cc53eea42f70f816dc4b000000001976a914a42cb159f6f8be525632491980eb9315cccef20e88acffffffff02e8030000000000001976a914e8db9f4559cbaa586dab4e6d1eedd482bdc3fc9d88acd07e0100000000001976a914a42cb159f6f8be525632491980eb9315cccef20e88ac00000000';
var myPrivKey='XXXXXXXXXXX';

var tx = new bitcore.Transaction(mytx);
tx.sign(myPrivKey);`

**Comment by fanatid** [comment]
It's happened because transaction inputs do not know information about correspond outputs.

**Comment by off-bank** [comment]
Thanks again, @fanatid. It's because of the script?   How do I sign a transacional like that created by coinprism API? I can use the API to sign it and I can broadcast it fine afterwards, but I'm looking to sign it locally in the browser as it is more secure.

**Comment by fanatid** [comment]
@off-bank check tests: https://github.com/bitpay/bitcore-lib/blob/master/test/transaction/transaction.js#L256

**Comment by off-bank** [comment]
I'll check it out, thanks. I wish there was a "sign any transaction" script without any checks. Maybe I can remove the checks from  the js.
Anyway, as it seems my transactions are exception, I'll go ahead and close the issue.
