### ISSUE TITLE
Why is the OP_RETURN getting rejected?

### ISSUE THREAD

**Issue by LAMike310** [bitpay/bitcore#1389]
Hello Bitcore team,

I made a script that writes data to the Blockchain, and I wanted to send a message that is 75 characters long, which I think is the limit for OP_RETURN transactions, but I get this error when I try to broadcast it:

`Error in broadcast: Transaction rejected by network (code -26). Reason: 64: scriptpubkey`

I do get the raw transaction hash, though, for what it's worth. Also, I'm using Bitcore 0.13, don't know how to make this work with the latest version of Bitcore. Any help would be really appreciated! 

Here's my script:

```
var bitcore = require('bitcore-lib');
var explorers = require('bitcore-explorers');
var insight = new explorers.Insight();

var publicAddress = '1ApaqPjAPrV6SE3aPMAR3wTeKqHSt9VVfk';
var privateKey = '5HzUqceaVVC9bqf1tq7jVwvuejrFC8xJfuHS3S8WWVe84JCndAc'

var bitcoinRecipient = '14JNZ1HzVbTFWCoX1hp8pVVZyCGR3wEPeU'

var minerFee = 5000;
var letterToSatoshi = 'cheese-steel-dog-puppies-fruit-shoes-apples-bank-jets-ball-foot-dance-kings';

insight.getUnspentUtxos(publicAddress, function (error, utxos) {
console.log('utxos' + ' :' + JSON.stringify(utxos, undefined, 2));
if(utxos.length == 0) {
  console.log("Not enough Satoshis to cover the miner fee.");
  return
}
else if (bitcore.Unit.fromBTC(utxos[0].toObject().amount).toSatoshis() - minerFee > minerFee)     {
  console.log("We've got enough Satoshis!");
  var transaction = new bitcore.Transaction()
    .from(utxos[0]) // using the last UXTO to sign the next transaction
    .to(bitcoinRecipient, 10000 - minerFee) // Send 10000 Satoshi's
    .addData(letterToSatoshi) // Our message to Satoshi
    .sign(privateKey); // Last step for the digital autograph
  console.log('transaction_hex: ' + transaction.checkedSerialize());
  insight.broadcast(transaction, function (error, body) {
    if (error) {
      console.log('Error in broadcast: ' + error);
    }
    else {
      console.log("Success! Here's our Transaction ID: " + body);
      console.log('http://explorer.chain.com/transactions/' + body + "#!transaction-op-return")
    }
  });
   }
});

```
Thanks,

Mike

**Comment by fanatid** [comment]
Can you show transaction? afaik with `OP_RETURN` you have only 40 bytes

**Comment by LAMike310** [comment]
I tried to broadcast the raw hash of that transaction, but it hasn't been confirmed yet:

https://live.blockcypher.com/btc/tx/7ad3ca062c7eae60f489844a272a5d77b649d29397238ba737f8f066d29023ae/

**Comment by LAMike310** [comment]
@fanatid I believe it was once 40, but 0.11 of Bitcoin Core changed it back to 80. Is this possible to do with Bitcore? 

https://github.com/bitcoin/bitcoin/pull/5286

**Comment by dabura667** [comment]
The old 40 byte limit was based on strict requirements that there was only one OP_RETURN and one push data op. The size of the data being pushed was capped at 40 bytes.

The new byte limit is the scriptpubkey in total must stay at 80 or below. Since OP_RETURN uses 1 byte and push data for 77-79 bytes is two bytes, that means the new max is 77 bytes assuming only one push data is used.

**Comment by dabura667** [comment]
Your scriptPubkey is 77 bytes, which fits the 80 byte limit for opreturn.

The insight you are connecting to has not yet upgraded to include the new opreturn rules is your answer.

Are you just using the public insight or are you spinning your own?

**Comment by fanatid** [comment]
@dabura667 thanks, can you clarify about
> was only one OP_RETURN

now we can use a few OP_RETURN???

**Comment by LAMike310** [comment]
@dabura667 I'm using the bitcore-explorers@1.0 library and the bitcore-lib@0.13.13, so I think that means I'm using the public insight right? Or does it the opposite?

**Comment by dabura667** [comment]
@fanatid I believe you can have multiple OP_RETURNs as long as the total byte size of all of the OP_RETURNs and their data all add up to a total of 80 bytes or less.

**Comment by dabura667** [comment]
ie. I could have 3 OP_RETURN outputs with 24 bytes of data each, but having 3 OP_RETURNs with 25 bytes of data each will **not** be OK.

(The former adds up to 78 bytes and the latter adds up to 81 bytes)

**Comment by dabura667** [comment]
@LAMike310 I found your answer.

https://insight.bitpay.com/api/status?q=getinfo

Bitpay's public insight is running on 0.9.5 which is a backwards compatibility port to an old version.

Broadcasting anything through the public server will have to adhere to the old rules unless you have your own node and would like to run insight on top of it.

I would give you my own IP, but I can't guarantee you my node will always be up for you.

Hope this answers your question. Until you can get your own insight running on a new version of bitcoind, you'll have to copy paste the raw tx manually, or just run a normal post request through another site instead of using insight (bitcore-explorers w/e)

**Comment by dabura667** [comment]
maybe add a require https then instead of insight.broadcast, use https.post

https://api.blockcypher.com/v1/btc/main/txs/push

the key for the transaction hex string in the payload object is "tx"

**Comment by LAMike310** [comment]
@dabura667 I'm getting an error when posting to that API, I'm using axios and the blockcypher API:

```
var axios = require('axios')
axios.post('https://api.blockcypher.com/v1/bcy/test/txs/push',
        {"tx": "01000000015e9d654ccdf376c21502152ad7eba61027c5860f35557729a45e356a7cdc9ad6000000008a47304402201f06d4679b3f835215c338bace1d8b317aeade5346309389b60f4d7753f5a710022033d9e5aafdd4154889b6ab71eb927b8879eeb3dc9c6c2e665e665485f71a4e0b014104f0087a849a6e9ebc5b3fb9090849a22b72c71564e165458a9957150a7dd24639f1f60746cbfa25950ec9bc7064a77141a78c5a309ff7cc0b90050e8a6a1a8ed7ffffffff02da210000000000001976a914fed9eb51a9d13032e4cf2d6a4856fe8bde18b18c88ac0000000000000000546a4c5177723335322d33316472342d4141412d30322d31362d31352d32336f6c2d313030303030303030302d33323132322d333435352d363933352d323334392d323334302d31323333322d30322d31302d313500000000"}
      )
      .then(function (response) {
        console.log(response.data);
      })
      .catch(function (response) {
        console.log(response.data);
      });
```

The error I'm getting is this: "Transaction 02b1be3be0a6a4f7d8e369cca88520443b3fc0993d3660d4d52e5f383d505650 has an input referencing an unknown transaction: d69adc7c6a355ea4297755350f86c52710a6ebd72a150215c276f3cd4c659d5e.'"

https://live.blockcypher.com/btc/tx/d69adc7c6a355ea4297755350f86c52710a6ebd72a150215c276f3cd4c659d5e/ says that transaction has 6+ confirmations, so I'm not sure what is going wrong... Any ideas?

**Comment by dabura667** [comment]
You are using their blockcypher testnet API

`https://api.blockcypher.com/v1/bcy/test/txs/push`

You must use their mainnet Bitcoin API

`https://api.blockcypher.com/v1/btc/main/txs/push`

**Comment by LAMike310** [comment]
@dabura667 Thanks for that! It works now. 

Here's the script I'm using if anyone else wants to use it in the future: 

https://gist.github.com/LAMike310/96104a94427db04eefb2

Thanks again for the quick responses, I really appreciate it.
