### ISSUE TITLE
Fee so low, transactions don't confirm for days

### ISSUE THREAD

**Issue by msmyers** [bitpay/bitcore#1390]
https://blockchain.info/address/13apNfX6NuThkeoN3w5anPa8yJEVGkKWPK

I'm deploying Bitcore for www.coinmewallet.com and our customers are complaining that transactions don't confirm. I saw a transaction that took over a day to complete. I'm hosting my own BWS instance and using the bitcoire-wallet-client.

Any thoughts on this?

**Comment by braydonf** [comment]
Fees should be calculated in BWS with bitcoind estimatefee: https://github.com/bitcoin/bitcoin/blob/28ad4d9fc2be102786a8c6c32ebecb466b2a03dd/src/rpc/mining.cpp#L655
