### ISSUE TITLE
Peer connection timeout

### ISSUE THREAD

**Issue by stevedekorte** [bitpay/bitcore#1393]
A callback for peer connection timeout would be helpful.

**Comment by braydonf** [comment]
Any more information? Please be more specific.

**Comment by stevedekorte** [comment]
If I'm intermittently connected to the net (e.g. I may not have a connection when I start bitcore but I might a few minutes later), I'd like bitcore to deal with it gracefully.
1) tell me if it has issues
2) try reconnecting periodically if needed
Right now it (seems to) die silently.

**Comment by braydonf** [comment]
Is this in reference to bitcore-p2p or bitcore-node? In bitcore-p2p there are disconnect events for peers that will add new peers, an interval can be used to periodically reconnect in the event of network disruption. With bitcore-node, bitcoind handles peer connections, and should reconnect, however there isn't an event for peers connecting/disconnecting.

**Comment by stevedekorte** [comment]
Not sure. I just tried starting my app with wifi off and bitcore didn't connect to after turning it back on.

**Comment by braydonf** [comment]
I'm unable to reproduce that behavior.
