### ISSUE TITLE
Error: More than one instance of bitcore-lib found.

### ISSUE THREAD

**Issue by randomshinichi** [bitpay/bitcore#1394]
I have a bitcore service which depends on a module that depends on bitcore-lib. When I try to deploy a bitcore node that uses this service, I get this:
`Error: More than one instance of bitcore-lib found. Please make sure to require bitcore-lib and check that submodules do not also include their own bitcore-lib dependency.`
I think (I'm not sure) that the bitcore-lib in the bitcore node folder is conflicting with the bitcore-lib that my module requires. I tried installing bitcore-lib globally, but npm install in my custom module still pulls in bitcore-lib, so I have to rm -rf node_modules/bitcore-lib in order to use the global bitcore-lib. Why does it pull it in locally anyway? Can't it see that I already have bitcore-lib in the global NODE_PATH?

**Comment by braydonf** [comment]
I just [ran a test](https://gist.github.com/braydonf/b3d398b78494e41c69fc12b04d20372d), and yes a globally installed bitcore-lib would work technically, however each submodule would need to not include bitcore-lib in the node_modules.

Also, when developing, `ln -s /path/to/bitcore-lib` in node_modules works well.

**Comment by braydonf** [comment]
As for why npm is loading it locally: A local `package.json` will take precedence, for example, `npm install` directly within will install the dependencies regardless. However it looks like submodules can be satisfied by global installs (from what it seems), probably a question for npm though. Hope that helps, let us know if there are any other issues. `npm list` can be useful for inspecting dependencies.
