### ISSUE TITLE
Slow Blockchain sync? (6.5% after 10 hours)

### ISSUE THREAD

**Issue by LAMike310** [bitpay/bitcore#1396]
I started syncing the Blockchain last night, and when I woke up, the sync was at 6.5%. At this rate it will probably take a week, is this typical? The ReadMe says it should take up to 4 hours depending on the internet connection, but my upload/download stats are pretty decent. Is there something I'm doing wrong? Or should I just wait it out?

<img width="741" alt="screen shot 2016-04-16 at 10 05 20 am" src="https://cloud.githubusercontent.com/assets/2181637/14582484/1e203fae-03bb-11e6-90a3-00a2473c6dc8.png">

**Comment by martindale** [comment]
@braydonf any thoughts on why this might be different from Bitcoin Core's sync behavior?

**Comment by braydonf** [comment]
@LAMike310 I believe the reference of 4 hours is for testnet, which I think the biggest bottleneck typically bandwidth. Reindexing would take less than that. For livenet, 24 to 48 hours would be more expected.

@martindale In regards to bandwidth there should be no difference from Bitcoin Core's sync behavior. The sync/indexing in Bitcore 3.0 is slightly slower than Bitcoin Core v0.11. With branch I'm working on now with Bitcoin Core v0.12 with [address indexes](https://github.com/bitpay/bitcoin/pull/6) in Bitcoin Core the reindexing is faster.

**Comment by braydonf** [comment]
Also, disk speeds and CPU can also affect the sync and indexing times.

**Comment by LAMike310** [comment]
Thanks @braydonf, I moved the downloading part to my MacMini, and I'm using an external USB, so I guess that doesn't help much... I'm at 12.9% so far.

**Comment by braydonf** [comment]
New version available with indexes in bitcoind, speed should be improved.
