### ISSUE TITLE
Question: What's the process for updating components?

### ISSUE THREAD

**Issue by dabura667** [bitpay/bitcore#1399]
I've been (probably incorrectly) updating each individual component by:
1. `kill xxxx` where xxxx is the pid for bitcored
2. `cd ~/mynode/` then `npm install bitcore-wallet-service@latest` to update the BWS folder in node_modules below mynode.
3. restart bitcored

A few things:
1. Is there a better way to do it than kill? I use nohup bitcored & to start bitcored in the background and rotate nohup.out logs. kill seems to work fine, but just wondering if there's a better way.
2. How should I be managing updates for components? I have been just using npm install from ~/mynode to get the latest versions in the dependency folders... that sound ok?

I think my sloppy way of doing things has caused problems, as Something is telling me it can't find Insight (both mainnet and testnet) all the time... but my BWS seems to be working totally fine. Also, my insight-api is fully synced.

**Comment by braydonf** [comment]
Using upstart or systemd may be a better method, e.g.:
```
service bitcore restart
```

There is an example upstart script here: https://github.com/bitpay/bitcore/tree/master/etc/init

Also `kill -2 xxx` will send SIGINT
