### ISSUE TITLE
Insight API not found, but can connect with curl

### ISSUE THREAD

**Issue by dabura667** [bitpay/bitcore#1400]
below is a copy-paste of some info. nohup.out is basically recording stdout for bitcored.

Note: I added this.apiPrefix to insight.js in order to double check that it was trying to connect to the right apiPrefix... this is why the error log says the api prefix as well.

Also note that I am able to use Copay with my BWS, even though this is constantly spitting out errors... (I don't know why)

Ever since the errors showed up, my Copay has been much faster, so maybe it's defaulting to check the bitpay insight server??? I am not sure.

```bash
hoge@mybox:~/mynode$ cat nohup.out
...
(couple hundred lines after 5 minutes of uptime)
...
ERR! Error connecting to Insight (livenet) @ http://localhost:3001/insight-api 
ERR! Error connecting to Insight (testnet) @ https://test-insight.bitpay.com:443/insight-api 
ERR! Error connecting to Insight (livenet) @ http://localhost:3001/insight-api 
ERR! Error connecting to Insight (testnet) @ https://test-insight.bitpay.com:443/insight-api 
ERR! Error connecting to Insight (livenet) @ http://localhost:3001/insight-api 
ERR! Error connecting to Insight (testnet) @ https://test-insight.bitpay.com:443/insight-api 

hoge@mybox:~/mynode$ curl http://localhost:3001/insight-api/sync
{"status":"finished","blockChainHeight":411368,"syncPercentage":100,"height":411368,"error":null,"type":"bitcore node"}

hoge@mybox:~/mynode$ cat ./node_modules/bitcore-node/package.json | grep version
  "version": "2.1.1",

hoge@mybox:~/mynode$ cat ./node_modules/bitcore-wallet-service/package.json | grep version
  "version": "1.6.1",

hoge@mybox:~/mynode$ cat ./node_modules/insight-api/package.json | grep version
  "version": "0.3.2",

hoge@mybox:~/mynode$ cat ./node_modules/bitcore-wallet-service/lib/blockchainexplorers/insight.js  | grep "return 'Insight"
  return 'Insight (' + this.network + ') @ ' + this.hosts + this.apiPrefix;

hoge@mybox:~/mynode$ cat ./node_modules/bitcore-wallet-service/lib/blockchainmonitor.js  | grep "log.error('Error"
    log.error('Error connecting to ' + explorer.getConnectionInfo());
```

**Comment by braydonf** [comment]
I believe the connection is via websocket, and different than the express app. What's the error details in blockchainmonitor?

**Comment by dabura667** [comment]
Do those errors print to stdout? If so I haven't seen them.

If not, where are the blockchainmonitor.js specific logs?

Should I try modifying the source and print some more verbose info?

**Comment by braydonf** [comment]
Yeah, we may need to log more verbose info by modifying the source. The first param [should be](http://socket.io/docs/client-api/#) an error object, from the connect_error event:
```js
socket.on('connect_error', function(err) {
  log.error(err);
  log.error('Error connecting to ' + explorer.getConnectionInfo());
});
```

**Comment by dabura667** [comment]
I was getting a timeout error:
"xhr poll error"

I upgraded BWS to 1.7.0 and the problem is resolved.
