### ISSUE TITLE
Has the latest commit broken things ?

### ISSUE THREAD

**Issue by aussiehash** [bitpay/bitcore#1401]
https://github.com/bitpay/bitcore/commit/3ce344a2318c222442b35fb84c021d630d1f43fb

    $ npm install -g bitcore
    \
    > bitcore-node@3.0.0 preinstall     /home/bitnodes/.nvm/versions/node/v4.4.5/lib/node_modules/bitcore/node_modules/bitcore-node
    > ./scripts/download
    
    Downloading bitcoin: https://github.com/bitpay/bitcoin/releases/download/v0.12-bitcore/
    npm ERR! Linux 3.10.75-84
    npm ERR! argv "/home/bitnodes/.nvm/versions/node/v4.4.5/bin/node"     "/home/bitnodes/.nvm/versions/node/v4.4.5/bin/npm" "install" "-g" "bitcore"
    npm ERR! node v4.4.5
    npm ERR! npm  v2.15.5
    npm ERR! code ELIFECYCLE
    
    npm ERR! bitcore-node@3.0.0 preinstall: `./scripts/download`
    npm ERR! Exit status 8
    npm ERR! 
    npm ERR! Failed at the bitcore-node@3.0.0 preinstall script './scripts/download'.
    npm ERR! This is most likely a problem with the bitcore-node package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     ./scripts/download
    npm ERR! You can get information on how to open an issue for this project with:
    npm ERR!     npm bugs bitcore-node
    npm ERR! Or if that isn't available, you can get their info via:
    npm ERR! 
    npm ERR!     npm owner ls bitcore-node
    npm ERR! There is likely additional logging output above.
    
    npm ERR! Please include the following file with any support request:
    npm ERR!     /home/bitnodes/npm-debug.log

**Comment by braydonf** [comment]
`npm install -g bitcore` is working here with node 4.4.5 and npm 2.15.5. Looks like there was a problem when downloading bitcoin. The download URL is missing the path, e.g.:

```
Downloading bitcoin: https://github.com/bitpay/bitcoin/releases/download/v0.12-bitcore/bitcoin-0.12.0-linux64.tar.gz
```

**Comment by braydonf** [comment]
What do you get when you run:
```
$ uname -m
```

**Comment by aussiehash** [comment]
$ uname -m
    armv7l

**Comment by aussiehash** [comment]
Whilst upgrading to 0.12 should bring a speed improvement, [it is not backwards compatible with prior versions requiring a reindex](https://github.com/bitcoin/bitcoin/blob/master/doc/release-notes/release-notes-0.12.0.md#downgrade-to-a-version--0120).

Bitcore v3 works fine on my Odroid XU4 (Exynos5422) appears to be 32-bit also

**Comment by braydonf** [comment]
Thanks for the info, we should better handle this case. The [download script](https://github.com/bitpay/bitcore-node/blob/master/scripts/download) is matching `x86_64` and `x86_32` for `uname -m`.

Arm binaries are not built as part of the release yet. Compiling bitcoin (https://github.com/bitpay/bitcoin/tree/0.12-bitcore) for arm would be necessary.

Builds are deterministically built with Gitian (https://github.com/devrandom/gitian-builder) and a [descriptor](https://github.com/bitpay/bitcoin/tree/0.12-bitcore/contrib/gitian-descriptors) for arm is needed to include as part of the release.

**Comment by braydonf** [comment]
Adding arm gitian descriptor to upstream bitcoin would likely be the best path for this.
