### ISSUE TITLE
Finished syncing Blockchain, getting error when starting node after

### ISSUE THREAD

**Issue by LAMike310** [bitpay/bitcore#1406]
I started syncing the blockchain a few weeks ago, and today it was completed. Once I shut down the Bitcore node and  did `bitcore install insight-api insight-ui` to install the UI for insight. When I started the Bitcore node up again after it installed, I got this error:

> [2016-06-06T21:55:46.113Z] info: Starting bitcoind
> [2016-06-06T21:55:55.446Z] info: Bitcoin Daemon Ready
> [2016-06-06T21:55:55.447Z] info: Starting db
> [2016-06-06T21:55:55.725Z] info: Bitcoin Database Ready
> [2016-06-06T21:55:55.726Z] info: Starting address
> [2016-06-06T21:55:55.898Z] info: Starting web
> [2016-06-06T21:55:55.932Z] info: Starting insight-api
> [2016-06-06T21:55:55.932Z] info: Starting insight-ui
> [2016-06-06T21:55:55.933Z] info: Bitcore Node ready
> [2016-06-06T21:55:56.891Z] **error: uncaught exception: [TypeError: Cannot read property 'length' of undefined]**
> [2016-06-06T21:55:56.893Z] error: TypeError: Cannot read property 'length' of undefined
>     at BufferReader.eof (/Users/user/Desktop/bitcoin/node_modules/bitcore-lib/lib/encoding/bufferreader.js:38:30)
>     at Transaction.fromBufferReader (/Users/user/Desktop/bitcoin/node_modules/bitcore-lib/lib/transaction/transaction.js:301:27)
>     at Transaction.fromBuffer (/Users/user/Desktop/bitcoin/node_modules/bitcore-lib/lib/transaction/transaction.js:297:15)
>     at InsightAPI.transactionEventHandler (/Users/user/Desktop/bitcoin/node_modules/insight-api/lib/index.js:255:30)
>     at emitOne (events.js:82:20)
>     at Bitcoin.emit (events.js:169:7)
>     at /Users/user/Desktop/bitcoin/node_modules/bitcore-node/lib/services/bitcoind.js:116:12
> [2016-06-06T21:55:56.893Z] info: Beginning shutdown
> [2016-06-06T21:55:56.894Z] info: Stopping insight-ui
> [2016-06-06T21:55:56.894Z] info: Stopping insight-api
> [2016-06-06T21:55:56.894Z] info: Stopping web
> [2016-06-06T21:55:56.895Z] info: Stopping address
> [2016-06-06T21:55:56.895Z] info: Stopping db
> [2016-06-06T21:55:56.915Z] info: Stopping bitcoind
> [2016-06-06T21:55:57.919Z] info: bitcoind shutdown.

Has anyone else run into this issue after syncing the Blockchain? Any help would be appreciated!

**Comment by braydonf** [comment]
Please include version numbers of all packages

**Comment by LAMike310** [comment]
Here's what I have locally @braydonf:

bitcore-lib@0.13.15
bitcore-node@2.1.1
insight-api@0.4.1
insight-ui@0.4.0

**Comment by braydonf** [comment]
You need to install compatible version of insight with `insight-api@0.3.x` and `insight-ui@0.3.x`.

Or upgrade to `bitcore-node@3.0.x` (requires a reindex see: https://github.com/bitpay/bitcore-node/blob/master/docs/upgrade.md)

**Comment by LAMike310** [comment]
Thanks! It's working now
