### ISSUE TITLE
Just want to say thank you

### ISSUE THREAD

**Issue by kabutosamourai** [bitpay/bitcore#1412]
Since version 4.0 landed, the Bitcore software has been very stable over long runs with heavy usage. Previously, we were seeing memory issues and halts, but we have had very good reliability since the 4.0 upgrade.

We just wanted to say thank you.

**Comment by martindale** [comment]
Agreed.  The new child-process and ZMQ interface is _amazing_.  Thank you for making this improvement.

**Comment by braydonf** [comment]
Glad to hear that it's running well. Thanks!
