### ISSUE TITLE
Decouple Service Management

### ISSUE THREAD

**Issue by martindale** [bitpay/bitcore#1413]
Many production environments have an existing service management tool such as `pm2`.  It'd be extremely useful if services could simply be run as standalone scripts, i.e., `node insight.js` vs. `node bitcore.js`, so that external toolings work much more easily.

`./bin/bitcored` for example does not seem to terminate when signaling it with `SIGINT` (via CTRL+C), which makes it hard to orchestrate as a process.

**Comment by braydonf** [comment]
Using `upstart` and `systemd` to manage is currently supported. There is a debian package builder with some example scripts in the [scripts directory](https://github.com/bitpay/bitcore/tree/master/scripts).

1. `./bin/bitcored` should respond to SIGINT, what was the issue there? 
2. What were the challenges when using `pm2`?

Perhaps creating a script similar to this could be useful:

```js
var config = loadConfig();

var node = new bitcore.Node({
  network: config.network,
  services: [
    {
      name: 'bitcoind',
      module: bitcore.services.Bitcoin,
      config: config.bitcoind
    },
    {
      name: 'custom',
      module: CustomService,
      config: config.custom
    }
  ]
});

node.start(function(err) {
  if (err) {
    throw err;
  }
});

process.on('SIGINT', function() {
  node.stop(function(err) {
    if (err) {
      console.error('Failed to stop services: ' + err);
      return process.exit(1);
    }
    process.exit(0);
  });
});
```
