### ISSUE TITLE
bitcored: not found

### ISSUE THREAD

**Issue by ccMehdi** [bitpay/bitcore#1415]
Hello Everyone,

I can't seem to get the script going. Keep getting the following: bin/sh: 1: exec: bitcored: not found.

I'm running Ubuntu 14 and followed the instruction on bitcore.io website. 

Your help is greatly appreciated.

**Comment by braydonf** [comment]
You may need to initiate nodejs with `nvm use v4` in a new shell.

**Comment by ccMehdi** [comment]
This is what I currently have in my .bashrc:

if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

export NVM_DIR="/home/bitcore/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

bitcore@bws:~$ nvm current
v4.4.7

thank you.

**Comment by ccMehdi** [comment]
Got it figured out and it working now. Thank you everyone.

**Comment by timigod** [comment]
@ccMehdi mind sharing how?

**Comment by osagga** [comment]
This issue is outdated, to use the most recent bitcore (`v8`), check the [README]( https://github.com/bitpay/bitcore/blob/master/README.md) on master

**Comment by timigod** [comment]
@osagga the readme is completely different from all the docs on https://bitcore.io/
