### ISSUE TITLE
Set custom fee doesn't work

### ISSUE THREAD

**Issue by bachvtuan** [bitpay/bitcore#1416]
Hi, I tried to set fee, the transaction is success but it used default fee. Can you explain why ?

`

    var from_public = "1PqytXWbAu4fjeHTdeFBiQBjvEjYrcDzod";
    var script = new bitcore.Script(new bitcore.Address(from_public)).toHex();
    console.log("script",script);

    var privateKey = new bitcore.PrivateKey('KyJvKDS1akH6Z4SgHUzJH6ANsMs62McD2Rwaw3gUjv9MXVwu8XXV');
    var utxo = {
      "txId" : "7d2ac05fa3f196395c87dd4b5fb39ec04d9e8bf330f72bed49286cb6f5ba596e",
      "outputIndex" : 0,
      "address" : from_public,
      "script" : script,
      "satoshis" : 1
    };

    var transaction = new bitcore.Transaction()
      .from(utxo)
      .fee(5430)

      //.feePerKb(1000)
      .to(address, 546)
      .change(address)
      .enableRBF()
      .sign(privateKey);

      //transaction;

      console.log(transaction.isRBF());
      
      //uncheckedSerialize
      

      console.log(transaction.getFee());
     

    var post_params = {
        url:"https://blockchain.info/pushtx", form:{tx: transaction.uncheckedSerialize()}
    };

    request.post(post_params,function(error, response, body) {
        console.log("body",body);

    });`

**Comment by bachvtuan** [comment]
Hey, this code just took all of my money for fee (  44.34usd) for that :(
https://blockchain.info/tx/56b9e3a48bea9315c088ea149089e658cca346cd67ef04bbe846d98b735b1a16


```

    var from_public = "1P2cjkh1fXZUASHQAMUV9i1Sw8AGzkBx1w";
    var script = new bitcore.Script(new bitcore.Address(from_public)).toHex();
    console.log("script",script);

    var privateKey = new bitcore.PrivateKey('myprivatekeyxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx');
    var utxo = {
    "txId" : "bb6725ddb24e3f544529636bfe36001c7fbff59127e54d7cb937b70efc8ec46c",
    "outputIndex" : 4,
    "address" : from_public,
    "script" : script,
    "satoshis" : 1
    };

    var transaction = new bitcore.Transaction()
      .from(utxo)
      //.feePerKb(1000)
      .to([{address: address, satoshis: 546}])
      .fee(5430)
      .change(address)
      .sign(privateKey);

```

**Comment by braydonf** [comment]
1. It looks like `uncheckedSerialize()` is being used, and should generally not be used. Using `uncheckedSerialize()` skips several checks, including the following:
  - The output amount does not exceed the input amount
  - The fee specified is the actual fee
  - The fee is not abnormally large

2. The source of the problem is that the amount of satoshis for the utxo is incorrect. According to the utxo given, the satoshis available to spend is 1, however the actual amount is larger. As soon as the output is added with 546 satoshis, that amount is exceeded and there isn't change or fee available, and a change output isn't added. The transaction when serialized would throw an error that the output amount exceeds the input amount.

**Comment by bachvtuan** [comment]
Thank you @braydonf .
I'm newbie in Bitcoin, I have been struggled over 1 week. I have some questions want to ask you, please help me.

1. what's method I should use instead of "uncheckedSerialize" ?
2. What's the mean of shatoshis in utxo ? I don't see any document talking about this number, so I just give it as 1.  By the way, The lib doesn't throw any error, my transaction was submitted to blockchain with fee is my entire btc( that sound the biggest fee I have seen for a bitcoin transaction ). Anyway, I think your lib should prevent use so much fee like my case.
3. In my case, I just need create a transaction with amount is 546 satoshis and fee is 5430 satoshis. what's appropriate value of shatoshis in utxo  ?
4. It's really help if you send me demo code that work for my case.
5. Since my bitcoin was gone, I don't have much left, I would like to send you 0.01BTC for your kindly help :)

**Comment by braydonf** [comment]
You should be using `tx.serialize()`, as this includes such checks. The satoshis in the "unspent output" (UTXO) should match the amount in that output.  

The change method is to specify the address to return the remaining amount. For example if the total satoshis for the inputs is 10,000, and the amount being sent is 3,000. There is a remainder of 7,000 satoshis. That amount needs to be sent back to one of the wallets addresses, minus a small amount for the fee.

**Comment by bachvtuan** [comment]
Thank you @braydonf,I will try on tomorrow.

**Comment by bachvtuan** [comment]
Hi. My account has 30k satoshis but every time I made a transaction, fee always take the rest.
Here is my code 

```
    var from_public = "1AphDfptAGJoFudGCHQ6pEinspm73icn18";
    var script = new bitcore.Script(new bitcore.Address(from_public)).toHex();
    var address = "1AphDfptAGJoFudGCHQ6pEinspm73icn18";

    var privateKey = new bitcore.PrivateKey('L5hdFtFX3SngkhZNQTdNUW22T6QSxCT4gwMDRhGppUF9EZDXamGK');
    var utxo = {
      "txId" : "5a96c2509da839e94bc8a7c6f479eb4784f41a0f004e6efa5f7b7592d470f74a",
      "outputIndex" : 1,
      "address" : from_public,
      "script" : script,
      "satoshis" : 10546
    };
    
    var transaction = new bitcore.Transaction()
      .from(utxo)
      .to([{address: address, satoshis: 546}])
      .fee(10000)
      .enableRBF()
      .sign(privateKey);


    var post_params = {
        url:"https://blockchain.info/pushtx", form:{tx: transaction.serialize()}
    };

    request.post(post_params,function(error, response, body) {
        console.log("body",body);
    });

```

This is url for transaction https://blockchain.info/address/1AphDfptAGJoFudGCHQ6pEinspm73icn18

**Comment by bachvtuan** [comment]
Hi. I did it.. need to set change to send the rest of remain money.

```

    var from_public = "1rGXteb8ztKWKirqfbMuvU8fn6YTrBxEa";
    var script = new bitcore.Script(new bitcore.Address(from_public)).toHex();

    var privateKey = new bitcore.PrivateKey('Ky72ZGMwEe3tCpxxxxxxxxxxxxxxxxxxxxxxxxx');
    var utxo = {
      "txId" : "f7f8fb0bf9d67e95f155ab29bf9b38491c7b7a6f3c341f49010dbc27d522d12a",
      "outputIndex" : 1,
      "address" : from_public,
      "script" : script,
      "satoshis" : 19454
    };


    
    var transaction = new bitcore.Transaction()
      .from(utxo)
      .to(address, 546)
      .fee(1000)
      .change(from_public)
      .enableRBF()
      .sign(privateKey);


    var post_params = {
        url:"https://blockchain.info/pushtx", form:{tx: transaction.serialize()}
    };

    request.post(post_params,function(error, response, body) {
        console.log("body",body);
    });

```

**Comment by Lalitpatadiya12** [comment]
Anyone please help if I am adding fee into my transaction at that time it'll give me error as below

throw serializationError;
    ^
undefined

**Comment by Lalitpatadiya12** [comment]
@bachvtuan @braydonf  anyone has idea if I want to calculate fees before transaction go to blockchain or actual transaction?

**Comment by Ranjit190** [comment]
all any one have any idia i am getting error "Unspent value is different from specified fee: Unspent value is 906 but specified fee is 905"?
