### ISSUE TITLE
pushtx

### ISSUE THREAD

**Issue by benzmuircroft** [bitpay/bitcore#1420]
I'm looking for examples/SendTx.js

As I want to broadcast a tx to the network

it would be an improvement from me using a 3rd party service to do this if Bitcore can do this!

I have looked all over this repo and run multiple searches for **sending a payment** but found nothing not even in issues

**Comment by benzmuircroft** [comment]
Is it a lib?

**Comment by benzmuircroft** [comment]
i just want to pushtx not run wallet.. I already have my signed txhash

```

var transaction=new Ƀ.Bitcore.Transaction()
	.	fee(Ƀ.Bitcore.Unit.fromBTC(fee).toSatoshis())
	.	from(unspents)
	.	to(Ƀ.Bitcore.Address.fromString(payToAddress),Ƀ.Bitcore.Unit.fromBTC(amount).toSatoshis())
	.	change(payWithKeys.address)
	.	sign(payWithKeys.privateKey);


// >> send to network!! (?)
```

**Comment by gabegattis** [comment]
The examples have been replaced by the documentation at https://github.com/bitpay/bitcore-lib/tree/master/docs and https://bitcore.io/api/

If you want to finish your example, you want to do
```js
var rawTx = transaction.serialize();
```

You can push that raw tx to the network by copy/pasting at https://insight.bitpay.com/tx/send or by using the sendrawtransaction RPC call to bitcoind.

**Comment by benzmuircroft** [comment]
I don't see a lb for sending RPC to bitcoind

**Comment by benzmuircroft** [comment]
note: I am trying to avoid 3rd party rate limits so the insight api might be a no-go for me! I want to pushtx directly to the network using my own pruned node (small vps for a startup company)

**Comment by gabegattis** [comment]
If you are running bitcoind using Bitcore, there is a bitcore service for making api calls to bitcoind. https://bitcore.io/api/service/bitcoin

If you just have vanilla bitcoind running by itself, you can use https://github.com/bitpay/bitcoind-rpc to connect to it and send RPC commands.

**Comment by benzmuircroft** [comment]
thanks, it's much clearer now!
