### ISSUE TITLE
Failed at the zmq@2.15.3 install script 'node-gyp rebuild'

### ISSUE THREAD

**Issue by nanofaroque** [bitpay/bitcore#1421]
I am unable to npm install for bitcore and its showing this error.

**Comment by bitcoinsSG** [comment]
which os are you running? on ubuntu; you should try sudo apt-get install libzmq-dev
or even a more comprehensive solution
sudo apt-get install libtool pkg-config build-essential autoconf automake libzmq-dev

**Comment by dsky1990** [comment]
apt-get install libzmq-dev slove my problem
