### ISSUE TITLE
Installation Point to GitHub 404

### ISSUE THREAD

**Issue by kreshendo** [bitpay/bitcore#1423]
I am trying to install GitHub on Ubuntu 16.04 and the installation stops and exits when trying to download Bitcoin core from GitHub.
 
This link appears to be the problem:
https://github.com/bitpay/bitcoin/releases/download/v0.12.1-bitcore-2/

**Comment by braydonf** [comment]
You should have a link such as:
https://github.com/bitpay/bitcoin/releases/download/v0.12.1-bitcore-2/bitcoin-0.12.1-linux64.tar.gz

Here is the script that downloads:
https://github.com/bitpay/bitcore-node/blob/master/scripts/download

**Comment by wmpedersen** [comment]
This is an issue with the script as `uname -m` doesn't return x86_32 for all 32-bit architectures.

**Comment by braydonf** [comment]
Looks like it needs to be matching `i686`. There also is an issue, as there isn't an exit failure either.

**Comment by kreshendo** [comment]
OK I need this server set up today. So if I clone this repo and the bitcore-node repo, which script do I edit in the bitcore repo to point to my cloned , and edited version of the bitcore-node repo that will download bitcoin for i686?

**Comment by braydonf** [comment]
Just submitted a PR to fix this: https://github.com/bitpay/bitcore-node/pull/486/files

**Comment by kreshendo** [comment]
Thanks.
