### ISSUE TITLE
Install fails missing bitcoind modules

### ISSUE THREAD

**Issue by tomtruitt** [bitpay/bitcore#1424]
Followed install instructions and got error.
![pasted image at 2016_10_11 05_51 pm](https://cloud.githubusercontent.com/assets/10718256/19290321/1bd4d24c-8fdd-11e6-9ec6-061563f60a6b.png)

**Comment by tomtruitt** [comment]
switched to node v4 as per README but same issue 
![image](https://cloud.githubusercontent.com/assets/10718256/19293666/3170bef6-8ff4-11e6-906b-2af05b86c44a.png)

**Comment by tomtruitt** [comment]
oh interesting after switching to node 4 i see the issue is permission denied (probably this just wasnt being told to me with node 6 seems generally less verbose)

**Comment by tomtruitt** [comment]
even building with docker doesn't work.
![image](https://cloud.githubusercontent.com/assets/10718256/19294288/16a1ce6c-8ff9-11e6-8ba5-1e421294840e.png)

is this repo still relevant?

**Comment by tomtruitt** [comment]
@braydonf

**Comment by braydonf** [comment]
If you're installing as the root user, you'll likely have issues.

> **Note**: Do not run this command with sudo or with root privileges as this will lead to [permission issues](https://docs.npmjs.com/misc/scripts#user). 

https://bitcore.io/guides/full-node#install-bitcore

**Comment by tomtruitt** [comment]
I see thank you. I'll fix and proceed and likely close the issue all tomorrow. thanks for clarifying!

**Comment by tomtruitt** [comment]
ok this time i got 3 errors about not finding python. i need python installed?

**Comment by tomtruitt** [comment]
first i got errors about python. after a quick apt-get i've been staring at this for a while.. 
![image](https://cloud.githubusercontent.com/assets/10718256/19325266/5c6c2c36-9093-11e6-9c46-862d8a9bcf20.png)

**Comment by tomtruitt** [comment]
looks like oom. made a temp swap file and the install seems to have completed! thanks for your help!
