### ISSUE TITLE
Failed at the zmq@2.15.3 install script 'node-gyp rebuild'.

### ISSUE THREAD

**Issue by diadal** [bitpay/bitcore#1430]
x bitcoin-0.12.1/lib/libbitcoinconsensus.0.dylib
x bitcoin-0.12.1/lib/libbitcoinconsensus.dylib
/Users/johnmark/.nvm/versions/node/v7.0.0/bin/bitcore -> /Users/johnmark/.nvm/versions/node/v7.0.0/lib/node_modules/bitcore/bin/bitcore
/Users/johnmark/.nvm/versions/node/v7.0.0/bin/bitcored -> /Users/johnmark/.nvm/versions/node/v7.0.0/lib/node_modules/bitcore/bin/bitcored

> bufferutil@1.2.1 install /Users/johnmark/.nvm/versions/node/v7.0.0/lib/node_modules/bitcore/node_modules/bufferutil
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node

> utf-8-validate@1.2.1 install /Users/johnmark/.nvm/versions/node/v7.0.0/lib/node_modules/bitcore/node_modules/utf-8-validate
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node

> zmq@2.15.3 install /Users/johnmark/.nvm/versions/node/v7.0.0/lib/node_modules/bitcore/node_modules/zmq
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
/bin/sh: pkg-config: command not found
gyp: Call to 'pkg-config libzmq --libs' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/johnmark/.nvm/versions/node/v7.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/Users/johnmark/.nvm/versions/node/v7.0.0/bin/node" "/Users/johnmark/.nvm/versions/node/v7.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/johnmark/.nvm/versions/node/v7.0.0/lib/node_modules/bitcore/node_modules/zmq
gyp ERR! node -v v7.0.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
/Users/johnmark/.nvm/versions/node/v7.0.0/lib
└── (empty)

npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/johnmark/.nvm/versions/node/v7.0.0/bin/node" "/Users/johnmark/.nvm/versions/node/v7.0.0/bin/npm" "install" "-g" "bitcore"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! zmq@2.15.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zmq@2.15.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the zmq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs zmq
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls zmq
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/johnmark/npm-debug.log
npm ERR! code 1

**Comment by doplumi** [comment]
Same error, also on Darwin. Did you manage to get past it?

Unfortunately, installing node 4 via nvm as suggested in the docs, does nothing.

**Comment by msapelov** [comment]
Try to `brew install zmq` or _czmq or zmqp_

**Comment by mikeyb** [comment]
Was hitting this on Debian as well.  Might be worth adding as a requirement for install doc

`sudo apt install libzmq-dev`

After installing this package `npm install` succeeded using npm 4.8.2 via `nvm install 4`

**Comment by csotomon** [comment]
I have the same problem installing 4.1.1 version in ubuntu 16.04 with libzmq3-dev package

The bitcore 3.0.0 installation works well, but >=4.0.0 no.

**Comment by scottie** [comment]
same here as above

**Comment by psiofxt** [comment]
Seems this issue still exists a year later. Up to date `npm` and `npm-gyp` still doesn't allow bitcore to install and failed at `zmq-2.15.3`

**Comment by mikeyb** [comment]
Are you using the ubuntu built in version of npm?  If so, it is far far out of date.  Use `nvm` to install a newer npm version and see if that works for you

**Comment by psiofxt** [comment]
@mikeyb Thanks, this definitely worked on a fresh instance I was installing on. Previously I manually installed `zmq` to get it to work, but simply using `nvm` to use `node>8.0.0` works!
