### ISSUE TITLE
bitcored syncing at 8 connections only

### ISSUE THREAD

**Issue by mariuszlitwin** [bitpay/bitcore#1431]
Hello,

My bitcore node is synchronizing at 8 connections (according to insight-ui).

My setup is Ubuntu Server 16.04.1 LTS with node v4.6.2.
My server is ok according to specs from [bitcore-node repo](https://github.com/bitpay/bitcore-node) (2 vCPUs, 8GB RAM, 256 SSD drive).

Tested it against VirtualBox VM, local system and GCP VM with the same results.

Will be happy to provide additional information to replicate my issues.

Thank you in advance.

**Comment by gabegattis** [comment]
8 connections is the maximum by default in bitcoind. You can use the "maxconnections" option in bitcoin.conf to change this, but it is not necessarily a good idea to do so. See Pieter Wuille's response on https://bitcoin.stackexchange.com/questions/8109/how-does-one-attain-1-000-connections-like-blockchain-info
