### ISSUE TITLE
Testnet node not working properly after restart

### ISSUE THREAD

**Issue by frz-dev** [bitpay/bitcore#1432]
Hi,
every time I try to restart my (testnet) node, it seems to stop syncing correctly with the network.
It only receives a few transactions, and it's surely missing many others (including those I produce).

This is not always the case, but happens many times. If I restart the computer, and starts the node, it operates correctly.
Usually I stop it with a Ctrl-C which seems to be correctly detected and handled by the node (it performs a normal shutdown). So I wonder why this happens.

Any clue to solve this issue?

**Comment by pmosse** [comment]
Hi, did you manage to solve this? Could you share your config file? Thanks!

**Comment by frz-dev** [comment]
Hi, I'm not currently working on that code (neither I can find the directory I was using for the development) but as I remember correctly I didn't really find a solution.

This is my config file:
```
{
  "network": "testnet",
  "port": 3001,
  "services": [
    "bitcoind",
    "insight-api",
    "insight-ui",
    "web",
  ],
  "servicesConfig": {
    "bitcoind": {
      "spawn": {
        "datadir": "/media/Data/dev/blockchain/bitcoin/data",
        "exec": "/media/Data/dev/blockchain/bitcoin/bitcoin-0.12.1/bin/bitcoind"
      }
    }
  }
}
```
