### ISSUE TITLE
Failed at the bitcore-node@3.1.3 preinstall script './scripts/download'

### ISSUE THREAD

**Issue by Noperslol123** [bitpay/bitcore#1436]
-edit-
_The issue seems to be with the bitcore-node NPM module concerning unsupported i686 architecture. There seems to be a proposed fix, but it has yet to be merged. (https://github.com/bitpay/bitcore-node/pull/486)_

I cannot get Bitcore to install on Ubuntu or Whonix. I have successfully gotten it to install on Centos 7 and have finished development of my project, but I would like to deploy on a Debian distro rather than Red Hat. For some reason, NPM will not install Bitcore on the Debian distros specified above. Below are the exact steps that I am performing on a fresh OS install via Virtual Box.

First we have to install NVM, which is a Node.js version manager. Bitcore is reportedly only compatible with Node.js version 4.6.0. We will use NVM to install that version.

https://github.com/creationix/nvm#install-script	
sudo apt-get install git-all
sudo curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.32.1/install.sh | bash

At this point, close and reopen your terminal so that NVM will be detected. To verify NVM has been installed, do..
command -v nvm
Which should output ‘nvm’. Next we’ll install bitcore.

https://bitcore.io/guides/full-node/
nvm install v4.6.0
sudo apt-get install libzmq3-dev build-essential
npm install -g bitcore

Below is the output that I am getting.

`user@host:~$ npm install -g bitcore
> bitcore-node@3.1.3 preinstall /home/user/.nvm/versions/node/v4.6.0/lib/node_modules/bitcore/node_modules/bitcore-node
> ./scripts/download
Downloading bitcoin: https://github.com/bitpay/bitcoin/releases/download/v0.12.1-bitcore-4/
npm ERR! Linux 3.16.0-4-686-pae
npm ERR! argv "/home/user/.nvm/versions/node/v4.6.0/bin/node" "/home/user/.nvm/versions/node/v4.6.0/bin/npm" "install" "-g" "bitcore"
npm ERR! node v4.6.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! bitcore-node@3.1.3 preinstall: `./scripts/download`
npm ERR! Exit status 22
npm ERR! 
npm ERR! Failed at the bitcore-node@3.1.3 preinstall script './scripts/download'.
npm ERR! This is most likely a problem with the bitcore-node package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./scripts/download
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bitcore-node
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls bitcore-node
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/user/npm-debug.log
user@host:~$
`

If any other info is needed, I will do my best to provide it.

**Comment by LeJ0ker** [comment]
same

**Comment by LeJ0ker** [comment]
i have it.
Just install curl xD

**Comment by rjmacarthy** [comment]
How to fix this on windows?  I added curl to environment path, didn't fix the issue?

**Comment by sampleblood** [comment]
it happens when download file from github ,I fixed it by export  in .bashrc.
 export http_proxy="http://server:port/"
export https_proxy="http://server:port/"
export ftp_proxy="http://server:port/"

**Comment by kangasbros** [comment]
Having the same problem, anyone know a fix?

**Comment by sampleblood** [comment]
when download file from github ,it use curl ,so be sure that your curl is ok

**Comment by fluentart** [comment]
sudo apt install curl

**Comment by bellaj** [comment]
same issue on windows 10

**Comment by huanvliu** [comment]
same issue on ubantu 16

**Comment by bellaj** [comment]
I think this issue comes from the used node/npm version

**Comment by takeratta** [comment]
same issue on Ubuntu 17.10 x64

**Comment by Lalitpatadiya12** [comment]
Same issue on centos 6.9 any idea ?

**Comment by Zzitao** [comment]
Same issue on ubuntu14,anyone tell me how to fix it

**Comment by usab** [comment]
Same issue win 7

**Comment by scrapup** [comment]
I have encountered this problem。 Just using flowing command：
```
npm install -g --unsafe-perm=true bitcore
```

**Comment by rohitpratapitm** [comment]
Still same issue on windows 10. Anyone has a work around.

**Comment by Pantela777** [comment]
I have similar problem...

**Comment by Guanyuhao** [comment]
window 环境我遇到了同样的问题

**Comment by ngocphong1991** [comment]
anyone can help, same issue on win 10 :(

**Comment by Guanyuhao** [comment]
我也尝试了npm install -g --unsafe-perm=true bitcore 可是还是遇到相同的问题

**Comment by lerennardleonard** [comment]
@Guanyuhao worked for me, cheers !

**Comment by Ramin-Bateni** [comment]
sudo apt install curl
sudo npm install -g --unsafe-perm=true bitcore-node
