### ISSUE TITLE
Unable to run Dockerfile

### ISSUE THREAD

**Issue by mr-e-** [bitpay/bitcore#1439]
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/home/bitcore/.nvm/versions/node/v4.7.3/lib/node_modules/npm/node_modules/which/which.js:14:12)
gyp ERR! stack     at F (/home/bitcore/.nvm/versions/node/v4.7.3/lib/node_modules/npm/node_modules/which/which.js:69:19)
gyp ERR! stack     at E (/home/bitcore/.nvm/versions/node/v4.7.3/lib/node_modules/npm/node_modules/which/which.js:81:29)
gyp ERR! stack     at /home/bitcore/.nvm/versions/node/v4.7.3/lib/node_modules/npm/node_modules/which/which.js:90:16
gyp ERR! stack     at /home/bitcore/.nvm/versions/node/v4.7.3/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
gyp ERR! stack     at /home/bitcore/.nvm/versions/node/v4.7.3/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Linux 4.9.4-moby
gyp ERR! command "/home/bitcore/.nvm/versions/node/v4.7.3/bin/node" "/home/bitcore/.nvm/versions/node/v4.7.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/bitcore/.nvm/versions/node/v4.7.3/lib/node_modules/bitcore/node_modules/bitcore-node/node_modules/zmq
gyp ERR! node -v v4.7.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN optional dep failed, continuing bufferutil@1.2.1
npm ERR! Linux 4.9.4-moby
npm ERR! argv "/home/bitcore/.nvm/versions/node/v4.7.3/bin/node" "/home/bitcore/.nvm/versions/node/v4.7.3/bin/npm" "install" "bitcore" "-g"
npm ERR! node v4.7.3
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE

npm ERR! zmq@2.15.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zmq@2.15.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the zmq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs zmq
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls zmq
npm ERR! There is likely additional logging output above.
npm ERR! Linux 4.9.4-moby
npm ERR! argv "/home/bitcore/.nvm/versions/node/v4.7.3/bin/node" "/home/bitcore/.nvm/versions/node/v4.7.3/bin/npm" "install" "bitcore" "-g"
npm ERR! node v4.7.3
npm ERR! npm  v2.15.11
npm ERR! path npm-debug.log.3470552518
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall open

npm ERR! Error: EACCES: permission denied, open 'npm-debug.log.3470552518'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, open 'npm-debug.log.3470552518']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'open',
npm ERR!   path: 'npm-debug.log.3470552518' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /npm-debug.log
ERROR: Service 'bitcore' failed to build: The command '/bin/sh -c /bin/bash -l -c "npm install bitcore -g"' returned a non-zero code: 1

**Comment by dabura667** [comment]
What command did you use to run this?
