### ISSUE TITLE
More than one instance of bitcore-lib found.

### ISSUE THREAD

**Issue by haydencarlson** [bitpay/bitcore#1446]
Upon npm installing my project which depends on `bitcore-mnemonic ` and `bitcore-payment-protocol` both also get bitcore-lib installed into both.
This is causing an error `more than on instance of bitcore-lib found check submodules folder for duplicates.

<img> https://gyazo.com/8b26aee53b6b478fa8e770e9d444b04b </img>

**Comment by dabura667** [comment]
Use a more recent version of node and then delete your node modules folder and do npm install again.

It really helps.

**Comment by haydencarlson** [comment]
I'm running version 6.2.1 and deleted node modules and npm installed.

**Comment by cconley717** [comment]
Same problem as well, using Node 7.10.0 with NPM 4.2.0. The problem is the dependencies using different versions of bitcore-lib. I have tried manually installing the latest version of bitcore-lib in these dependencies, but then the modules within the dependencies that depend on bitcore-lib are then broken due to changes in bitcore-lib.

**Comment by haydencarlson** [comment]
I made a symbolic link to 0.14.0 for all instances it was used.
It works now but it sucks.

**Comment by cconley717** [comment]
Thanks, that worked. Everything is working like normal now. Mah gawd.....

**Comment by dabura667** [comment]
btw, the event that version guard is trying to prevent is no longer a problem in recent versions of node.

If two dependencies require two different versions of bitcore, the requires in each dependency will load the correct version.

I just added a startup script to find bitcore-lib folders and replace "global._bitcore" with __null

**Comment by vetler** [comment]
Exactly what did you do? I need some hand-holding here - I'm not that familiar with nvm and node.

**Comment by cconley717** [comment]
It looks like they updated the repo to use the proper version of bitcore-lib. Try deleting everything and try again.

**Comment by haydencarlson** [comment]
Awesome . Yep I tried a fresh copy now and it's working. Thx @kleetus

**Comment by xibxor** [comment]
This issue is happening again...

**Comment by haydencarlson** [comment]
@xibxor did you try to create a link like i suggested to before?

**Comment by xibxor** [comment]
No, I just installed an older version of bitcore using the @ operator for npm.

**Comment by johncloud200** [comment]
how to fix?

**Comment by haydencarlson** [comment]
This also worked for me 
```npm uninstall --prefix /path/to/your/bws -S bitcore-lib```

@jeshan creds.

**Comment by johncloud200** [comment]
@haydencarlson isn't that can break bws functionality?
