### ISSUE TITLE
Increase number of connections? 

### ISSUE THREAD

**Issue by bsbits** [bitpay/bitcore#1448]
Greeting,

By default, the number of connection is 8.
When I browse a hosted insight on localbitcoin / Bitpay, the number of connections is higher.

I would like to know the pros / cons of increasing the number of connections.
And how to increase that number on my own node.

Thank you.

**Comment by dabura667** [comment]
Port forwarding.

**Comment by bsbits** [comment]
@dabura667 : do you have any link of how to do that ?

Thank you.

**Comment by bitcoinbrisbane** [comment]
@bsbits you need to do it on your modem or router.  Add a forward rule port 8333 to your nodes ip.
