### ISSUE TITLE
Error: More than one instance of bitcore-lib found. Please make sure to require bitcore-lib and check that submodules do not also include their own bitcore-lib dependency.

### ISSUE THREAD

**Issue by xishoon** [bitpay/bitcore#1454]
Hi everybody
When I run the command bitcored, it gives me the following error

/home/ruby/.nvm/versions/node/v4.8.3/lib/node_modules/bitcore/node_modules/insight-api/node_modules/bitcore-lib/index.js:12
    throw new Error(message);
    ^
Error: More than one instance of bitcore-lib found. Please make sure to require bitcore-lib and check that submodules do not also include their own bitcore-lib dependency.
    at Object.bitcore.versionGuard (/home/ruby/.nvm/versions/node/v4.8.3/lib/node_modules/bitcore/node_modules/insight-api/node_modules/bitcore-lib/index.js:12:11)
    at Object.<anonymous> (/home/ruby/.nvm/versions/node/v4.8.3/lib/node_modules/bitcore/node_modules/insight-api/node_modules/bitcore-lib/index.js:15:9)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ruby/.nvm/versions/node/v4.8.3/lib/node_modules/bitcore/node_modules/insight-api/lib/blocks.js:4:15)
    at Module._compile (module.js:409:26)

**Comment by anduck** [comment]
Well, this is far from a proper way to solve this issue, but you can get rid of this error by editing file

`~/.nvm/versions/node/v4.8.3/lib/node_modules/bitcore/node_modules/insight-api/node_modules/bitcore-lib/index.js`

line 7:
`bitcore.versionGuard = function(version) {`
Change it to:
`bitcore.versionGuard = function(version) { return;`

**Comment by anand011090** [comment]
I just went to index.js and I changed the line throw new Error(message) to throw new Error(version) in the file index.js. That gave me the current version of the bitcoin-lib. In my case, it was v0.13.19. Now revert the changes and updated the version to this one which you have got.

**Comment by Boyarov** [comment]
this problem with npm version
enter:

```
nvm use v4
bitcored
```

**Comment by Lohann** [comment]
It works, thanks @Boyarov !

**Comment by amillerchip** [comment]
This is the result of `npm list` from `~/.nvm/versions/node/v4.8.5/lib` after installing bitcore:

```
├─┬ bitcore@4.1.1
│ ├─┬ bitcore-lib@0.14.0
│ │ ├── bn.js@2.0.4
│ │ ├── bs58@2.0.0
│ │ ├── buffer-compare@1.0.0
│ │ ├─┬ elliptic@3.0.3
│ │ │ ├── brorand@1.0.5
│ │ │ └── hash.js@1.0.3
│ │ ├── inherits@2.0.1
│ │ └── lodash@3.10.1
│ ├─┬ bitcore-node@3.1.3
│ │ ├── async@1.5.2
│ │ ├── bitcoind-rpc@0.6.0
│ │ ├─┬ bitcore-lib@0.13.19
```

It looks like `bitcore` depends on `bitcore-lib` v0.14, but then also depends on `bitcore-node `which depends on `bitcore-lib` v0.13, and then includes check to make sure they do not depend on different versions.

**Comment by usab** [comment]
@adamu 
Is 4.1.0 the latest version?

**Comment by flotwig** [comment]
Would like to note that this issue is still present when installing `bitcored` from npm on a vanilla Ubuntu 17.10 installation.

**Comment by adubinsky** [comment]
npm -g install bitcore@4.1.0 fixed the issue for me.

**Comment by manojvenkateswararaja** [comment]
How to achieve assymetric encrypt and decrypt technique in ethereum by picking the keys from testrpc . In Testrpc iam getting account address and private key where the public key resides and how we need to pick it up.
"my code is"
 var testIdentity= {
                        type: 'ethereum',
                        display: '0x54dbb737eac5007103e729e9ab7ce64a6850a310',
                        privateKey: '52435b1ff11b894da15d87399011841d5edec2de4552fdc29c8299574436924d',
                        publicKey: 'a35813f8025a217675e4f85e758d0a43616fe661',
                        foreign: false
                    };
            var message = "foobar";
            var bitcore = require('bitcore-lib');
            var ECIES = require('bitcore-ecies');
            
                    /**
                 * encrypt the message with the publicKey of identity
                 * @param  {{privateKey: ?string, publicKey: string}} identity
                 * @param  {string} message
                 */
                var encrypt = function(identity, message) {
            
                    /*
                     * this key is used as false sample, because bitcore would crash when alice has no privateKey
                     */
                    var privKey = new bitcore.PrivateKey('52435b1ff21b894da15d87399011841d5edec2de4552fdc29c8299574436925d');
                    var alice = ECIES().privateKey(privKey).publicKey(new bitcore.PublicKey(identity.publicKey));
                    var encrypted = alice.encrypt(message);
            
                    return encrypted.toString('hex');
                };
            
                /**
                 * decrypt the message with the privateKey of identity
                 * @param  {{privateKey: ?string, publicKey: string}}   identity
                 * @param  {string}   encrypted
                 */
               
                
                
                
            var enc = encrypt(testIdentity, message);
            console.log("encrypted data...",enc)
            // var dec = decrypt(testIdentity, enc);
            
            // if(dec!="message"){
            //     alert('error');
            // }else{
            //     alert('sucess');
            // }
            
             var decrypt = function(identity, encrypted) {
                    var privKey = new bitcore.PrivateKey(identity.privateKey);
                    var alice = ECIES().privateKey(privKey);
            
                    var decryptMe = new Buffer(encrypted.e, 'hex');
            
                    var decrypted = alice.decrypt(decryptMe);
                    return decrypted.toString('ascii');
                };
            
               var dec = decrypt(testIdentity, enc);
               console.log("decrypted file.....",dec)
         })

**Comment by li069025** [comment]
https://baijiahao.baidu.com/s?id=1614559114632526526&wfr=spider&for=pc 看看这个

**Comment by ameensol** [comment]
can confirm, just got this error

**Comment by adiingit** [comment]
Solution finally !!

https://github.com/bitpay/bitcore/issues/1457#issuecomment-467594031

**Comment by trinisofttechnologies** [comment]
var bitcore = require('bitcore-explorers/node_modules/bitcore-lib');


You can use this to resolve this error.
Thanks

**Comment by 34r7h** [comment]
the above solution is difficult using webpack and babel. is there a package that combines packages for simplicity?

**Comment by dchambers** [comment]
Adding this to my `package.json` did it for me:

```json
"resolutions": {
  "bitcore-lib": "0.16.0"
}
```

**Comment by anubnair** [comment]
this issue is still persist. Say some package, for exampe Ethereum-Bip44, that has a dependency of bitcore 0.13.13. so the entire code should use 0.13.13 which is very old!

**Comment by placecodex** [comment]
my solution 

reemplace 
 const bitcore = require('bitcore-lib');  for 
const bitcore = require('bitcore-insight').Bitcore;

**Comment by Chibueze-Adeyemi-Ajayi** [comment]
@trinisofttechnologies really worked for me too ... nice job, let keep building

**Comment by li069025** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by PiusLucky** [comment]
Import bitcore-lib this way:

`import * as bitcore from 'bitcore-lib';`

Hope it helps.

**Comment by PiusLucky** [comment]
Hope it helps.

```
import bitcore from 'bitcore-lib';
if (global._bitcore) delete global._bitcore;
const Insight = require('bitcore-insight').Insight;

let insight = new Insight('testnet');
```
```
console.log('🚀 ~ ', insight);
console.log('🚀 ~ ', bitcore);
```
1

[`bitcore-lib` creates a global object named _bitcore, and every time you want to create an instance it checks to make sure that object is not available. To solve this, I simply delete this variable before requiring:](https://stackoverflow.com/questions/45217988/error-more-than-one-instance-of-library-found)

**Comment by estevanpedro** [comment]
Solved by creating a file `lib/customBitcore.ts`

```
const bitcore = require("bitcore-lib")

bitcore.versionGuard = () => {}

module.exports = bitcore

```

And edited the file `next.config.mjs`



```
/** @type {import('next').NextConfig} */
const nextConfig = {
  /** YOUR CONFIGS ... */
  webpack(config) {
    config.resolve.alias = {
      ...config.resolve.alias,
      "bitcore-lib": path.resolve(__dirname, "lib/customBitcore.ts"),
    }
    return config
  }
}

export default nextConfig
```



Basically replaces the function that was giving the `throw new Error(message);`.
