### ISSUE TITLE
Network mismatch for chain

### ISSUE THREAD

**Issue by thosuperman** [bitpay/bitcore#1466]
Hello, I got the error 

[error] (node) Network mismatch for chain.

- OS: Ubuntu 16.04
- NodeJS: v8.2.0
- Version 5.0.0-beta.1
- Env: Testnet

![2017-08-25_173131](https://user-images.githubusercontent.com/17564259/29710658-6b5b3378-89bb-11e7-88f8-a727d4638a68.png)

Would anyone help me in this case?

Thanks and best regards,
Tho

**Comment by thosuperman** [comment]
I have tried change to livenet but I can't access to http://xx.xx.xx.xx:3001/insight

**Comment by Ariel-Li-Yu** [comment]
I've encountered the same situation with testnet, does anyone know how to fix this?
