### ISSUE TITLE
Transactions value error (U)

### ISSUE THREAD

**Issue by thosuperman** [bitpay/bitcore#1468]
### Describe the issue
I follow this guide: https://blog.bitpay.com/bitcore-segwit-activation/
But I got the Transactions value error (U)

#### If so, please list the steps to reproduce below:
1. Install nodejs 4.5.0 and npm
2. Install zeromq3-x 3.2.5
3. npm install bitcore
4. Update to use version 1.14.5:
cd /home/ubuntu/node_modules/bitcore/node_modules/bitcore-node/bin
wget https://github.com/btc1/bitcoin/releases/download/v1.14.5/bitcoin-1.14.5-x86_64-linux-gnu.tar.gz
tar -zxvf bitcoin-1.14.5-x86_64-linux-gnu.tar.gz
rm –rf bitcoind
ln -s bitcoin-1.14.5/bin/bitcoind bitcoind
5. Start by command: /home/ubuntu/node_modules/bitcore/bin/bitcored

### Expected behaviour
Show the values look like https://insight.bitpay.com/block/000000000000000062e7755ff41fc82b4e7809e753c2320e10f167be8bc05a57

### Actual behaviour
All of the Transactions value showing as error (U)

### Screenshots.
![2017-08-29_151304](https://user-images.githubusercontent.com/17564259/29811248-f830ecc0-8ccc-11e7-92eb-3f1166fe10d3.png)
![2017-08-29_151246](https://user-images.githubusercontent.com/17564259/29811249-f832db2a-8ccc-11e7-9986-75dcd177d3f1.png)

### What version of bitcoin-core are you using?
Version 1.14.5 (aka Production Release)

### Machine specs:
- OS: Ubuntu 16.04 (Amazon EC2 c4.large)
- CPU: 2 cores
- RAM: 3.75 GB
- Disk size: 360 GB
- Disk Type (HD/SDD): SSD

**Comment by Technoprenerd** [comment]
@thosuperman, how did you manage to get it working? (What is the fix?)

**Comment by cryptozeny** [comment]
why it closed? same issue here
