### ISSUE TITLE
Can't open http://xx.xx.xx.xx:3001/insight/

### ISSUE THREAD

**Issue by thosuperman** [bitpay/bitcore#1469]
OS: Ubuntu 16.04
Version: v5.0.0-beta.4

**Steps to reproduce below:**

    Install nodejs 8.4.0 and npm
    Install zeromq3-x 3.2.5
    npm install bitcore@beta
    
Run: /home/ubuntu/node_modules/bitcore/bin/bitcored

Issue: Can't open http://xx.xx.xx.xx:3001/insight/ also http://localhost:3001/insight/

**Comment by dabura667** [comment]
bitcore install insight-ui

**Comment by thosuperman** [comment]
![2017-08-31_102118](https://user-images.githubusercontent.com/17564259/29905023-336d115a-8e36-11e7-9793-cc65bd60f048.png)

I think insight-ui has already installed by command **npm install bitcore@beta**
