### ISSUE TITLE
Bitcored v5.0 switch from Bcoin to other node

### ISSUE THREAD

**Issue by got3nks** [bitpay/bitcore#1471]
I upgraded to Bitcore 5 beta4,

> To switch underlying Bitcoin implementations, you can point Bitcore to any full node which supports the Bitcoin P2P protocol, even another fork of Bitcoin. And since you won't need to fork Bitcore's codebase to do it, switching implementations is easier than ever. You can choose which Bitcoin transaction validation rules you want to use, whether Segwit or different block sizes.

How do I disable the built-in Bcoin node and make Bitcore point to my Bitcoin Cash node instead?

I'm currently running a Bitcoin Cash full node with this configuration:

```
server=1
whitelist=127.0.0.1
txindex=1
addressindex=1
timestampindex=1
spentindex=1
zmqpubrawtx=tcp://127.0.0.1:28332
zmqpubhashblock=tcp://127.0.0.1:28332
rpcallowip=127.0.0.1
rpcuser=...
rpcpassword=...
```

**Comment by got3nks** [comment]
I think I found out how, https://github.com/bitpay/bitcore-node/blob/master/bitcore-node.json.sample

```
    "p2p": {
      "peers": [
        { "ip": { "v4": "127.0.0.1" } }
      ]
    }
```

**Comment by got3nks** [comment]
I think the built-in Bcoin node is automatically disabled if you point your Bitcore configuration to use your Cash node.

**Comment by realcheese** [comment]
@got3nks Besides placing the above config under `servicesConfig`, did you remove `bitcoind` from `servicesConfig` as well as `services`?

**Comment by got3nks** [comment]
Version 5.0 does not have any bitcoind entry under servicesConfig by default.

**Comment by arruah** [comment]
Can you please show your bitcore-node.json? 
I got the error 
0|bitcored | SyntaxError: /home/ayan/.bitcore/bitcore-node.json: Unexpected string in JSON at position 253
After this
 "p2p": {
      "peers": [
        { "ip": { "v4": "127.0.0.1" } }
      ]
    }

**Comment by chakhalyan1** [comment]
I have use bitcore 5.0.0-beta.44, how can run for bitcoin cash?

**Comment by chakhalyan1** [comment]
Hi All.  I have find how can start bitcoin-abc via bitcore-node.
1. will download bitcoin-abc from [https://www.bitcoinabc.org/may15hardfork]
2. install bitcore-node and create Your  node 
             **bitcore-node create -d <bitcoin-data-dir> mynode**
3. change bitcore-node.json following case.
       `{
  "network": "livenet",
  "port": 3001,
  "services": [
    "bitcoind",
    "insight-api",
    "insight-ui",
    "web"
  ],
  "servicesConfig": {
    "bitcoind": {
      "spawn": {
        "datadir": "<bitcoin-data-dir>",
        "exec": "/btcABC/bitcoin-abc-0.16.2/bin/bitcoind"
      }
    }
  }
}
`
4. bitcore-node start

**Comment by m24927605** [comment]
Here is my install steps,you can check it.
https://github.com/m24927605/BCH_Node_InsightAPI

**Comment by hxzqlh** [comment]
@chakhalyan1 @m24927605 Have you try it? Does it work?

**Comment by m24927605** [comment]
@hxzqlh yeah,I run my install steps today,and it work.

**Comment by hxzqlh** [comment]
@m24927605 Is bitcoin cash addr api also ok? In my previous experiences, bch address not work as below.
```
bcc@a0bd3708b81c:~/mynode$ curl localhost:3001/insight-api/addr/1Gyz4vuYixD1BPDMCqBb8Hbm514v6YyNuU
Method not found. Code:-32601

bcc@a0bd3708b81c:~/mynode$ curl localhost:3001/insight-api/addr/qz7cgzl5mavucstffsr8qf8mp2v60zncqv7tn3nler
Invalid address: Non-base58 character. Code:1
```

**Comment by chakhalyan1** [comment]
for me also was worked. but before comment

**Comment by psiofxt** [comment]
@hxzqlh Hi! Did you ever get the `/addr` methods working? I finally got my bch bitcore node running -- `/block-index/1000` works but other methods don't.

**Comment by hxzqlh** [comment]
@psiofxt unfortunately, the `/addr`api didn‘t work，it said "Method Not Found" such thing~

**Comment by osagga** [comment]
@psiofxt You can try this [fork](https://github.com/osagga/bitcore-node-cash) for BCH that I'm working on. It's still in development and has some minor issues (check 'issues'), but it works for most of the `api` calls in bitcore.

**Comment by libin777** [comment]
> 这是我的安装步骤，您可以查看它。
> [https://github.com/m24927605/BCH_Node_InsightAPI ](https://github.com/m24927605/BCH_Node_InsightAPI)
> [https://github.com/m24927605/BCH_Bitcore_v5.x_InsightAPI ](https://github.com/m24927605/BCH_Bitcore_v5.x_InsightAPI)
> https://github.com/m24927605/bitcore-node-v8-node.git

According to your steps, I have successfully installed， But there is still a problem，When I access the /addr  insight interface, I return Method not found. Code:-32601，Do you know what the problem is?
