### ISSUE TITLE
Will 5.0 have full btc1 / segwit2x support?

### ISSUE THREAD

**Issue by shawnholt** [bitpay/bitcore#1472]
You mention segwit support but want to understand if this will fully support btc1 / segwit2x big blocks and proper signaling.

**Comment by chrisrico** [comment]
I haven't gotten the upgrade running yet, but my understanding is you run whatever Bitcoin P2P compatible node you want, and then you connect Bitcore to it. So you can run btc1, Bitcoin Core, or Bitcoin ABC and they'll all work work Bitcore.

**Comment by got3nks** [comment]
You can run any node you want, just add this in your `servicesConfig`:
```
    "p2p": {
      "peers": [
        { "ip": { "v4": "127.0.0.1" } }
      ]
    }
```

This will connect to any Bitcoin P2P compatible node you are running on the default port.

**Comment by chrisrico** [comment]
Does the internal Bcoin node keep its own copy of the blockchain in addition to that of the full node? Does it keep extra indexes?

**Comment by chrisrico** [comment]
Just in case anyone is wondering, it does keep a separate copy of the blockchain.

**Comment by ngmiller** [comment]
@chrisrico I'm looking at pointing bitcore at my own node as well. Are you sure bitcore continues to keep an entirely separate chain, effectively doubling node storage requirements, or is it just the extra index data? I really need to be able to point this at my own node but hearing that an entirely separate copy of chain is needed on top of what my node implementation requires is a bit disappointing.

**Comment by DanielRHayes** [comment]
closing, no longer relevant
