### ISSUE TITLE
Is it possible to create private key costume ?

### ISSUE THREAD

**Issue by Lalitpatadiya12** [bitpay/bitcore#1479]
Suppose If i am create one private key and public and default address something like below.

`privateKey :  02xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxd`
`publicKey : 03XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX`
`address : mnXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX`

Now If i want to create one more privateKey which is related to above one means Last character of privatekey is d and if i want to create another private key something like 

` 02xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxe`

is it possible to increment the value of last digit..?

**Comment by dabura667** [comment]
Yes. But don’t. There is no point.

**Comment by Lalitpatadiya12** [comment]
@dabura667  Is there any concept like wallet and sub-wallet in bitcore..?

**Comment by dabura667** [comment]
look at bitcore-mnemonic

You can generate a secret phrase that you can then turn into an HDPrivatekey (from bitcore-lib)

HDPrivateKeys can be derived using paths.

One popular path is BIP44, which is m/44’/0’/0’/0/0 for the first address of the first account.

You can create multiple accounts and addresses, just follow the instructions on BIP44.
