### ISSUE TITLE
Version 5: Switch node to Zcash

### ISSUE THREAD

**Issue by robertkowalski** [bitpay/bitcore#1481]
Hi and thanks for bitcore!

I 'm dabbling with a Zcash node and the latest beta right now.

I added a new network with `addNetwork` and changed the section where the genesis block is checked.

The node connects, but after a few ping pong everything dies. I wonder whats the right way to connect to bitcoin forks? Or maybe I just misread the blog post?

**Comment by ngmiller** [comment]
@robertkowalski I don't believe this is possible. Zcash is a separate coin, separate protocol, with an entirely different set of consensus rules.

**Comment by robertkowalski** [comment]
> zcash's rpc protocol is compatible.

yes, currently each bitcore is forcked for every bitcoin based coin, e.g. https://github.com/BitMEX/zcash-bitcore-node

the idea is to be able to easily switch coins with one implementation

**Comment by DanielRHayes** [comment]
@robertkowalski  We are working towards allowing you to have a multi-currency node in our `v8.0.0` branch.  There isn't any current development work to support any coins beyond BTC and BCH in the other packages of bitcore.
