### ISSUE TITLE
hdPrivateKey - Lemonade-Stand

### ISSUE THREAD

**Issue by bitkron-project** [bitpay/bitcore#1494]
Please show me how to generate the HDPrivateKey and where should i put the keys into.

**Comment by DanielRHayes** [comment]
Please see the code example in the [Lemonade Stand tutorial](https://bitcore.io/guides/lemonade-stand).  In particular this code is generating the private key.

```
  this.hdPrivateKey = new bitcore.HDPrivateKey(this.node.network);
  this.log.info('Using key:', this.hdPrivateKey);
  this.addressIndex = 0;
```
