### ISSUE TITLE
How to get notification if any transaction done in address ?

### ISSUE THREAD

**Issue by Lalitpatadiya12** [bitpay/bitcore#1496]
How to get instant notification of any address receive something(bitcoin/Satoshi)

**Comment by DanielRHayes** [comment]
You could use [this tutorial](https://bitcore.io/guides/satoshi-fire-alarm) from the bitcore website

**Comment by todipratik** [comment]
@DanielRHayes Can you share the updated link, please? Above link seems to be broken.

@Lalitpatadiya12 If you also have the link (or updated reference), request to share.
