### ISSUE TITLE
testnet and faucet

### ISSUE THREAD

**Issue by kiahmed** [bitpay/bitcore#1499]
is there any active testnode out there ? and faucet ?

**Comment by DanielRHayes** [comment]
Out of scope of bitcore.  But yes there are BTC and BCH testnets and faucets.  You can google for instructions on how to run a testnet node for each, below are some faucets.

BTC
faucet- https://testnet.manu.backend.hamburg/faucet

BCH
faucet- https://testnet.manu.backend.hamburg/bitcoin-cash-faucet
