### ISSUE TITLE
Bitcore for Bitcoin Cash

### ISSUE THREAD

**Issue by vladislavmamchich** [bitpay/bitcore#1501]
Hello, can I run Bitcore for Bitcoin Cash?

**Comment by DanielRHayes** [comment]
[There is a BCH implementation of bitcore-lib](https://github.com/bitpay/bitcore-lib-cash) as well as one for [bitcore-p2p](https://github.com/bitpay/bitcore-p2p-cash).  We are currently working on `v8` which will include a node for indexing multiple currencies through a trusted peer.

**Comment by osagga** [comment]
Check this [fork](https://github.com/osagga/bitcore-node/tree/cash) (you can inspect the code edits, it's not much) that I made to work with bitcoin-abc. I haven't test it with a fully synced livenet (since it's taking forever), but it works with regtest.

**Comment by m24927605** [comment]
this is my v8 solution.
https://github.com/m24927605/bitcore-node-v8-node
