### ISSUE TITLE
Private Key From Bitcoin Address

### ISSUE THREAD

**Issue by CHADBERRY** [bitpay/bitcore#1502]
Is it possible to work this algorithm the other way round?

Can you get a Private Key from just a Bitcoin Address?

**Comment by gabegattis** [comment]
no

**Comment by lp12ucw** [comment]
Hi can any 1 help me please I carnt seem to be able to actually deposit or withdraw a bic I duno if it’s just coz I haven’t got the correct I’d to verify my account or if it’s just coz I’m a propa spaz just carnt get grips of it 😂😂 But I do have to master keys so I’ll be glad to see the favour back 😉👍🏻
