### ISSUE TITLE
Downloading bitcoin: Permission denied.

### ISSUE THREAD

**Issue by thanhnd2812** [bitpay/bitcore#1530]
Please help,

I'm installing bitcore via npm with this command:

`sudo npm i -g bitcore`

but got an error:

> bitcore-node@3.1.3 preinstall /usr/local/lib/node_modules/bitcore/node_modules/bitcore-node
> > ./scripts/download
> 
> Downloading bitcoin: https://github.com/bitpay/bitcoin/releases/download/v0.12.1-bitcore-4/bitcoin-0.12.1-osx64.tar.gz
> ./scripts/download: line 44: bitcoin-0.12.1-osx64.tar.gz: Permission denied

Thanks in advance.

**Comment by bonney92** [comment]
bitcoincash:qplhk3jyeqkqce2pa7shnxm3pe7858lutgq4psmh7x

**Comment by bonney92** [comment]
bitcoincash:qplhk3jyeqkqce2pa7shnxm3pe7858lutgq4psmh7x

**Comment by Oberst-Starlight** [comment]
Same problem

**Comment by madwiki** [comment]
Do you think it is the correct way to solve this issue? So you expect users use node.js v4 forever?
