### ISSUE TITLE
VERSION 8 only returning empty arrays or no block found

### ISSUE THREAD

**Issue by phewitt** [bitpay/bitcore#1608]
I followed the npm run build && docker-compose up with some tweaks I added bitcoin-0.16.1 and a custom bitcore.config.json. 
I run bitcoin D before running lerna run start with the following flags

`/usr/src/app/bitcoin-0.16.1/bin/bitcoind -datadir=/usr/src/app/data -server -daemon -rpcuser=bitcoin -rpcpassword=bitcoin`

```
{
  "bitcoreNode": {
    "pruneSpentScripts": true,
    "chains": {
      "BTC": {
        "regtest": {
          "chainSource": "p2p",
          "trustedPeers": [
            {
              "host": "127.0.0.1",
              "port": 8333 
            }
          ],
          "rpc": {
            "host": "127.0.0.1",
            "port": 8332,
            "username": "bitcoin",
            "password": "bitcoin"
          }
        }
      }
    }
  }
}
```
My responses at `http://localhost:3000/api/BTC/regtest/tx/9b0fc92260312ce44e74ef369f5c66bbb85848f2eddd5a7a1cde251e54ccfdd5` is `[ ]` 
and 
`http://localhost:3000/api/BTC/regtest/block/0` is `block not found`
both mongo and bitcore-node containers are running and everything seems to be correct, but I'm still not getting any results. I tested bitcoind using bitcoin-cli to make sure I actually had blocks and transactions and I do. Any thoughts on what the issue could be?

**Comment by phewitt** [comment]
After more investigating it looks like bitcore-node container is connecting to  mongo and initializing however it doesn't look like it is running "addBlock" or writting more to the database after the initial connect. Which makes sense that there is no block found because there isn't any data in the model which causes the code to throw

**Comment by amanoooooooooooooooo** [comment]
could you provide some details how you solve your problems,  thank you
