### ISSUE TITLE
Insight search for address

### ISSUE THREAD

**Issue by jguthrie7** [bitpay/bitcore#1647]
I have insight v8 running on BTC testnet.

When I attempted to search for a valid address (`mgeMkmoHSEMEnEBajTbx2qgDQjp3PU3H6H`) using the search bar I get: `No matching records found`

I can however navigate to this address by going directly to the URL: `http://.../#/btc/address/mgeMkmoHSEMEnEBajTbx2qgDQjp3PU3H6H`

**Comment by micahriggan** [comment]
@jguthrie7 thanks
