### ISSUE TITLE
V8 `/tx/` endpoints don't provide the number of confirmations

### ISSUE THREAD

**Issue by osagga** [bitpay/bitcore#1667]
This follows from bitpay/bitcore-node#575, my argument is as follows:

It is true that the user can calculate the confirmations locally (using currentHeight and txHeight), but I think it would be much faster and more convenient if the `\tx\` API endpoints return the confirmations value.

If the user needs to derive the confirmations, the user will need to make two API calls per transaction (one to get the current chain tip, and another to get the tx.height) to calculate the confirmations, instead of only one if the API endpoint that provides it.

All the node has to do is to locally compute the confirmations when a transaction is requested (or multiple transactions) through the API. 

Having the API providing the confirmations will not increase the storage, it would only slightly impact the response time (not by much compared to the user making two API calls to compute the same value).

**Comment by micahriggan** [comment]
@sagivo, I'll see about adding confirmations tomorrow

**Comment by osagga** [comment]
@micahriggan Hey, any update on this?

**Comment by micahriggan** [comment]
https://github.com/bitpay/bitcore/pull/1692

**Comment by osagga** [comment]
Awesome! can't wait to test it out!

**Comment by osagga** [comment]
@micahriggan The confirmations looks good, I just have a small problem on the way confirmations are computed. 

According to this:
https://github.com/bitpay/bitcore/blob/e01d9fbbfec5517a4f71eaf0c4e18c7fc8a5ab67/packages/bitcore-node/src/providers/chain-state/internal/internal.ts#L176

I think the right way to do it would be `tipHeight - txHeight + 1` since simply subtracting will not count the block that the transaction is at as one confirmation. The argument here is that if the transaction is in a block that's at least one confirmation. Let me know what do you think
