### ISSUE TITLE
V8 doesn't show BCH network prefix in addresses

### ISSUE THREAD

**Issue by osagga** [bitpay/bitcore#1668]
It seems that after this commit a9622e2c786063bb72ffcf353dedbb4ae83e9773, the BCH addresses wouldn't show the network in the address (the bool `stripCash` is set to `true`), for example:
it should show `"bchreg:xxxxxx"`, but now it shows `"xxxxx"`. 

This behavior is inconstant with the address format BCH node (`bitcoin-abc`) returns when asking for a new address. Why?

**Comment by micahriggan** [comment]
The network is encoded in the address, so we're not storing it

**Comment by osagga** [comment]
Yeah that's a good point, thanks for the clarification.
