### ISSUE TITLE
Is bitpay developing bitcore?

### ISSUE THREAD

**Issue by educob** [bitpay/bitcore#1689]
I am getting into bitcore and every piece of info and code seems to come from bitpay?

Is bitpay the developer of bitcore?
I thought bitpay was behind bcoin.

Thanks.

**Comment by DanielRHayes** [comment]
Hello,

Yes, BitPay did develop bitcore, however we did not develop bcoin.

**Comment by educob** [comment]
Thanks for answering. 
Who developed bcoin? 
I just installed bitcore trying to get wallets into mongodb but they get saved as files.
Could you please tell me how to get the wallets into mongodb?

In the new v8 version will the blocks go into mongodb. 
I am developing a meteor-vue reactive application and if bitcore had blocks, address balances, txs, etc in mongodb my job would be much easier. Should I install v8 version?
Thanks.

**Comment by DanielRHayes** [comment]
[Purse.io](https://purse.io/) developed bcoin.  Yes in the v8 branch everything is stored in MongoDB, I would use that instead of the LevelDB versions.

**Comment by educob** [comment]
Thanks. You have been very helpful.

**Comment by educob** [comment]
I finally managed to install v8.
