### ISSUE TITLE
Is Bitcore using Bitcoin Core 0.12.1?

### ISSUE THREAD

**Issue by CodersBrothers** [bitpay/bitcore#1787]
I supose that Bitcore is using Bitcoin Core 0.12.1, checking this line https://github.com/bitpay/bitcore/blob/master/scripts/build-deb#L87 

Now Bitcoin Core is in 0.17, How secure is to use a so old version?

It is possible to use a own Bitcoin Core instalation and connect bitcore to this as a config params?

**Comment by SwenVanZanten** [comment]
It isn't possible.
Bitpay added address indexes into bitcoin https://github.com/bitpay/bitcoin
it should really be updated.

**Comment by skddc** [comment]
Version 8 (branch v8.0.0) is already compatible with normal bitcoin core nodes. No need for the forked version anymore. They're just not updating the current stable version anymore. All work is currently happening in the v8 branch, which already works pretty well.

**Comment by SwenVanZanten** [comment]
Awesome thank you, taking a look at it

**Comment by matiu** [comment]
branch 8.0.0 is not master. Closing this issue.
