### ISSUE TITLE
[v8] 'limit' option fails when using '/address/<address>/txs' endpoint 

### ISSUE THREAD

**Issue by osagga** [bitpay/bitcore#1793]
This endpoint fails when setting the limit value
```
 curl -s localhost:3000/api/BCH/testnet/address/bchtest:qzt88wjhncxtkr9cvg2n46e4nmk2yy2n85u00d50cj/txs?limit=10
Failed to parse: { find: "coins", filter: { chain: "BCH", network: "testnet", address: "bchtest:qzt88wjhncxtkr9cvg2n46e4nmk2yy2n85u00d50cj" }, limit: "10", returnKey: false, showRecordId: false, lsid: { id: UUID("a3d667f1-818e-4307-be70-a4d619f230f0") }, $db: "bitcore" }. 'limit' field must be numeric.
```

For some reason the value on limit is being interpreted as a string rather than a number.

**Comment by osagga** [comment]
This is a result of this change  #1789

**Comment by micahriggan** [comment]
That change should convert a string to a number...

**Comment by osagga** [comment]
@micahriggan This fixes it for me https://github.com/cwcrypto/bitcore-node/commit/e8d2b7b5db6491105b7bcf03b4a410ab1e733f0c

**Comment by osagga** [comment]
Oh sorry I didn't pull that commit into my fork, my bad, you're right!

**Comment by micahriggan** [comment]
No worries! Thanks for keeping an eye out.

**Comment by libin777** [comment]
> 设置限制值时，此端点失败
> 
> ```
>  curl -s localhost:3000/api/BCH/testnet/address/bchtest:qzt88wjhncxtkr9cvg2n46e4nmk2yy2n85u00d50cj/txs?limit=10
> Failed to parse: { find: "coins", filter: { chain: "BCH", network: "testnet", address: "bchtest:qzt88wjhncxtkr9cvg2n46e4nmk2yy2n85u00d50cj" }, limit: "10", returnKey: false, showRecordId: false, lsid: { id: UUID("a3d667f1-818e-4307-be70-a4d619f230f0") }, $db: "bitcore" }. 'limit' field must be numeric.
> ```
> 由于某种原因，限制值被解释为字符串而不是数字。

Excuse me, when I synced bch insight, I stopped when I synced to 545957. I want to upgrade my bitcore-node. Do you know how to upgrade, or what is the step? Thank you very much.
