### ISSUE TITLE
How can I  build and configure it to support bitcoin cash?

### ISSUE THREAD

**Issue by wangjunbao2018** [bitpay/bitcore#1796]
I wanna start up a node to support bitcoin cash, how can I do it? Thx

**Comment by osagga** [comment]
Have you tried to install `bitcore` from the `v8.0.0` branch of this repo?

**Comment by wangjunbao2018** [comment]
> Have you tried to install `bitcore` from the `v8.0.0` branch of this repo?

Yes, I did like this.  I  installed bitcore from the v8.0.0 branch of this repo based on the wiki.
And I found this in directory :  

cat /Users/apple/.bitcore/data/bitcoin.conf
```
server=1
whitelist=127.0.0.1
txindex=1
addressindex=1
timestampindex=1
spentindex=1
zmqpubrawtx=tcp://127.0.0.1:28332
zmqpubhashblock=tcp://127.0.0.1:28332
rpcallowip=127.0.0.1
rpcuser=bitcoin
rpcpassword=local321
```

But I don't know how it works?

**Comment by osagga** [comment]
@wangjunbao2018 Try following the guide https://github.com/bitpay/bitcore/issues/1801#issuecomment-449112811, it should work without the `git checkout v8.0.0` since master is `v8` now.
