### ISSUE TITLE
bitcore-node v8 BCH get address balance return to an error

### ISSUE THREAD

**Issue by ww8912188** [bitpay/bitcore#1853]
It seems get address balance API does not work properly on BCH testnet:

GET /api/BCH/testnet/address/qr534ym6x8ytczeecremlyry5ccl67rkcgw30u3yxk/balance
will return to below error on my side:

```
{
    "name": "MongoError",
    "message": "exception: $projection requires at least one output field",
    "errmsg": "exception: $projection requires at least one output field",
    "code": 16403,
    "ok": 0
}
```

BTW, I have not finished syncing the whole testnet blockchain when try this API, not sure that's the root cause.

**Comment by micahriggan** [comment]
You might need to pull v8 again, I get the following from our node

https://api.bitcore.io/api/BCH/testnet/address/qr534ym6x8ytczeecremlyry5ccl67rkcgw30u3yxk/balance

```
{"confirmed":223,"unconfirmed":0,"balance":223}
```

**Comment by ww8912188** [comment]
@micahriggan thanks for the quick response, update repo do solve the issue above.
