### ISSUE TITLE
'Not connected to peer' when running BCHABC with bitcore-node v8

### ISSUE THREAD

**Issue by keefertaylor** [bitpay/bitcore#1875]
I can't get a bitcore-node and a BitcoinABC daemon to talk to each other. 

I've done the following: 

Install BitcoinABC:
```shell
sudo add-apt-repository ppa:bitcoin-abc/ppa
sudo apt-get update
sudo apt-get install bitcoind
```

Install Bitcore v8:
```shell
sudo npm -g --unsafe-perm=true install bitcore@beta
```

My `bitcoin.conf` looks like: 
```
whitebind=127.0.0.1:8333
txindex=1
addressindex=1
timestampindex=1
spentindex=1
maxconnections=100
rpcuser=keefer
rpcpassword=keefer
rpcclienttimeout=30
rpcport=8332
rpcconnect=127.0.0.1
rpcbind=127.0.0.1
rpcallowip=127.0.0.1
```

And my `bitcore.config.json`:
```
{
	"bitcoreNode": {
		"pruneSpentScripts": true,
		"chains": {
			"BCH": {
				"mainnet": {
					"chainSource": "p2p",
					"trustedPeers": [{
						"host": "127.0.0.1",
						"port": 8333
					}],
					"rpc": {
						"host": "127.0.0.1",
						"port": 8332,
						"username": "keefer",
						"password": "keefer"
					}
				}
			}
		}
	}
}
```

Then I can start both services with:
```
bitcoind -conf=bitcoin.conf  -printtoconsole
bitcore-node -c bitcore.config.json 
```

This results in a bitcoind daemon happily printing it's syncing status to the command line (great!) but the bitcore-node program periodically errors with: 
```
warn: Not connected to peer 127.0.0.1 {"chain":"BCH","network":"mainnet"}
```

I can't figure out what's wrong here and nothing obvious is sticking out. Any idea what I'm messing up?

**Comment by micahriggan** [comment]
We haven't updated the npm package for v8, I recommend cloning from master until we start doing regular publishing

I think your config looks right, I think I have a specific line for port in my bch config

**Comment by micahriggan** [comment]
This previous comment might be helpful for the setup
https://github.com/bitpay/bitcore/issues/1801#issuecomment-449112811

**Comment by micahriggan** [comment]
Bitcoin core and ABC both don't respond to bitcore p2p messages until after they fully sync. Actually that's only partially true, if you start bitcore, and then start ABC after it, it's likely to connect to bitcore and service some requests intermittently, but generally it waits until it's fully synced.

**Comment by micahriggan** [comment]
Parent chain and forkHeight are optional config values that make syncing bch faster if you've already synced btc.

**Comment by keefertaylor** [comment]
> Bitcoin core and ABC both don't respond to bitcore p2p messages until after they fully sync. Actually that's only partially true, if you start bitcore, and then start ABC after it, it's likely to connect to bitcore and service some requests intermittently, but generally it waits until it's fully synced.

Ah. That explains my issue. Sorry for not being familiar with the impl details. I assumed they would gossip blocks to each other as they got them.

> Parent chain and forkHeight are optional config values that make syncing bch faster if you've already synced btc.

Makes sense, thank you.
