### ISSUE TITLE
insight-api -- obsolete? web sockets/docs missing in bitcore?

### ISSUE THREAD

**Issue by dmorris99** [bitpay/bitcore#1905]
Hi, 

I understand that https://github.com/bitpay/insight-api has been replaced by bitpay/bitcore -- but I can't see any documentation at all on what (if anything?!) replaces the websockets API that existed in insight-api. 

Is the by-design (i.e. no WS support in bitpay/bitcore) or is it a matter of hacking through the code to figure out what changes, if any, there are to endpoints or similar?

Thanks in advance!

**Comment by justinkook** [comment]
Hello!

The insight-api websockets documentation is being worked on!

**Comment by dmorris99** [comment]
Thanks Justin.

Also, regarding the docs (let me know if I should raise in separate
thread) -- is there a single "official" list of blockchains that
Insight/Bitpay can run against, with the necessary configs? I see it can
run on BCH network, and I'm also using Insight-Lite API project for LTC,
which seems to be a fork or clone of bitpay Insight.  I suspect with
suitable configs the core bitpay/bitcore can run against a few other
BTC-derived chains. Would be very, very useful to have these listed in once
place with config files.

**Comment by osagga** [comment]
@dmorris99 Yes, `bitcore`can easily work with other BTC-derived chains. Check my repo here https://github.com/osagga/bitcore for a `bitcore` that supports LTC in addition to BTC and BCH.

**Comment by parikshitsharma70** [comment]
I'm looking for an endpoint which was offered previously on insight-api : 
Unspent Outputs for Multiple Addresses
url : /insight-api/addrs/[:addrs]/utxo

Is this not possible to call this endpoint without wallet creation in bitcore v8?
