### ISSUE TITLE
v8 Insight not showing transactions

### ISSUE THREAD

**Issue by jamespharvey20** [bitpay/bitcore#1921]
I'm running branch `v8.0.0`, most recent commit 5dfeb9 (Jan 9.)

I have v8 bitcoin-node running `npm start`.  It is fully synced, and is properly periodically updating to new blocks as they come in through `bitcoind`.

Once it was synced, in insight, I ran `npm start`.  I'm able to connect to its website.  I can go to the blocks page and see them.  I can click into one, and see the block header.  If I then click on the number given for Transaction Count, as it's colored as a link and changes the mouse cursor as one, I'd expect to bring up the transactions, but it does nothing.

Likewise, if I click Transactions, it changes the URL to `http://10.0.0.2:4200/BTC/transactions`.  It still shows the Chain/Blocks...GBP/CNY area on the left, but the right area shows:

    Page Not Found
    404

Is this just a bug that needs a fix, or is the only thing that v8 insight can currently do is show blocks?

-----

Bonus Bug 1 - Blocks page currently shows tip as `559090`.  When in insight I ran `npm start`, that was the current block.  It's been running for about 110 minutes, and since then bitcoin-node has updated to `559105`.  Going to another part of its website and back to Blocks, and it still shows tip is `559090`.  Only if I actually reload (F5) the page does it bring in new blocks.

Bonus Bug 2 - I couldn't see a supported way to run insight on anything other than `localhost:4200`.  I was figuring there must be able to be an entry in `bitcore.config.json` for that, but couldn't find anything in insight's source looking for it.  I wound up editing `insight/package.json` and changed it to (this works, just figuring there should be a more user friendly way, or maybe it's there and just missing documentation for it):

    "start": "./node_modules/.bin/ng serve --host 0.0.0.0",

**Comment by micahriggan** [comment]
Try insight-previous, the current insight is an active wip

**Comment by jamespharvey20** [comment]
Thanks, quite relieved!
