### ISSUE TITLE
how to create bitcoincash address with bitcore-lib

### ISSUE THREAD

**Issue by sukeerthi117** [bitpay/bitcore#1929]

**Comment by DesWurstes** [comment]
Is this what you're looking for: https://github.com/bitpay/bitcore/blob/master/packages/bitcore-lib-cash/lib/address.js#L640

**Comment by sukeerthi117** [comment]
yes i am trying with bitcore-lib-cash but it is generating bitcoin address

**Comment by sukeerthi117** [comment]
Now i am able to create address and privatekey of bit coincash address but
when i am passing it to transation object it is giving error

/home/ahex/Desktop/tokenize.node/node_modules/bitcore-explorers/node_modules/bitcore-lib/node_modules/bs58/lib/bs58.js:51
    if (!(c in ALPHABET_MAP)) throw new Error('Non-base58 character')
                              ^

Error: Non-base58 character
    at Object.decode
(/home/ahex/Desktop/tokenize.node/node_modules/bitcore-explorers/node_modules/bitcore-lib/node_modules/bs58/lib/bs58.js:51:37)
    at Function.Base58.decode
(/home/ahex/Desktop/tokenize.node/node_modules/bitcore-explorers/node_modules/bitcore-lib/lib/encoding/base58.js:48:26)
    at Function.Base58Check.decode
(/home/ahex/Desktop/tokenize.node/node_modules/bitcore-explorers/node_modules/bitcore-lib/lib/encoding/base58check.js:45:31)
    at Function.Address._transformString
(/home/ahex/Desktop/tokenize.node/node_modules/bitcore-explorers/node_modules/bitcore-lib/lib/address.js:279:35)
    at Address._classifyArguments
(/home/ahex/Desktop/tokenize.node/node_modules/bitcore-explorers/node_modules/bitcore-lib/lib/address.js:107:20)
    at new Address
(/home/ahex/Desktop/tokenize.node/node_modules/bitcore-explorers/node_modules/bitcore-lib/lib/address.js:73:19)
    at /home/ahex/Desktop/tokenize.node/node_modules/bitcore


My code:

const explorers = require('bitcore-explorers')

const insight = new explorers.Insight('https://test-bch-insight.bitpay.com')
const bch = require('bitcore-lib-cash');


const privateKey =
"c53e08e77a292d1bf46aa2ef1cc7db94ce04449292562451cf204b3b29ae6b9a"
var address ="qqmrvwmyludwj05grf9g69enlhpfzn2gzcrznru8k3"


insight.getUnspentUtxos(address, function (error, utxos) {
if (error) {
console.error(error)
return
}else{
console.log('===================',utxos)
}
})

**Comment by DesWurstes** [comment]
Maybe you could call `insight.getUnspentUtxos` with `bch.Address.fromString("qqmrvwmyludwj05grf9g69enlhpfzn2gzcrznru8k3").toLegacyAddress()` rather than just `address`.

**Comment by sukeerthi117** [comment]
yes it is working


Thank You

**Comment by DesWurstes** [comment]
You're welcome! :)
