### ISSUE TITLE
How to monitor whole wallet balance using only xpub (watch mode)

### ISSUE THREAD

**Issue by sulliwane** [bitpay/bitcore#1935]
Hello,

I was wondering if there was an easy way to monitor a wallet balance using only the wallet xpub key (I'd like to implement a simple watch service) **without having to maintain my own bitcore node**.

I looked at this => https://github.com/bitpay/bitcore/tree/master/packages/bitcore-wallet-client#apiseedfromextendedpublickeyxpubkey-source-entropysourcehex-opts-optsaccount-optsderivationstrategy 

Any recommendation? Many thanks!

**Comment by micahriggan** [comment]
Hello,

Checkout the wallet-client package, it should have a wallet-create,
wallet-import, and wallet-balance script. You can use those three to create
a wallet on api.bitcore. From there you can just call wallet.getBalance
from a script and our bitcore node will respond to your balance request

**Comment by sulliwane** [comment]
Hi @micahriggan ,

many thanks for your feedback. Here is what I just tried:

```js
const Bitcore = require('bitcore-wallet-client');

const BWS_INSTANCE_URL = 'https://bws.bitpay.com/bws/api';

const bitcore = new Bitcore({
  baseUrl: BWS_INSTANCE_URL,
  verbose: false,
});
bitcore.importFromExtendedPublicKey(
  xpubkey,
  '???',
  '???',
  {},
  console.log,
);
```

I copied `xpubkey` from copay wallet parameters:
![screenshot from 2019-01-23 18-45-48](https://user-images.githubusercontent.com/1733686/51626115-2115fa80-1f3f-11e9-8818-4e6edf05a8ac.png)

But I get this error `Invalid Backup.`

I don't quite understand what these two variables are supposed to be: `source` & `entropySourceHex`

Would you mind clarifying for me? Thank you.

Note: I don't have access to xprivkey. Only semi-public information like xpubkey.

**Comment by sulliwane** [comment]
thank you for your answer, closing for now.
