### ISSUE TITLE
V8(node) No confing option to disable the API rate limiter

### ISSUE THREAD

**Issue by osagga** [bitpay/bitcore#1944]
I think there should be a `config` option that allows to disable the rate limiter

**Comment by micahriggan** [comment]
That sounds good to me!

Want to pop a disabled property on 

https://github.com/bitpay/bitcore/blob/69903046aebcce9c8fb929a34776426866dd70c4/packages/bitcore-node/src/types/Config.d.ts#L16

and then modify the middleware to call next when disabled is true, here

https://github.com/bitpay/bitcore/blob/69903046aebcce9c8fb929a34776426866dd70c4/packages/bitcore-node/src/routes/middleware.ts#L80

**Comment by osagga** [comment]
@micahriggan I made this commit here a189170fcf221589918202afccdbc809e75e2dbf do you think its good for a PR to this repo?
