### ISSUE TITLE
[insight-previous] API_PREFIX can't be set to `localhost:3000`

### ISSUE THREAD

**Issue by osagga** [bitpay/bitcore#1966]
When setting `API_PREFIX` to `localhost:3000/api` the webpage attempts the following

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:3000/api/BTC/mainnet/block?limit=15. (Reason: CORS request did not succeed).
```

It seems that the insight webpage doesn't translate `localhost` to the Insight's host IP instead, as showing in the following functions

https://github.com/bitpay/bitcore/blob/34facd65e2a9e52b205270405d1018181830dca2/packages/insight-previous/src/providers/api/api.ts#L39-L46

Is this expected? Is there a way I can launch `insight-previous` in `prod` and set the API prefix to `localhost`?

**Comment by micahriggan** [comment]
So you want to build the static files, and host insight, but have the page point to localhost, as in the machine hosting insight?

If you're hosting insight at www.myinsight.com, then try to set the API_PREFIX to that.

Otherwise what will happen, is that anyone visiting insight will have to be running bitcore-node on their machine.

If that were the case, then they could run

```
npm run insight-previous
```

**Comment by micahriggan** [comment]
```
ENV=prod CHAIN=BTC NETWORK=mainnet API_PREFIX=http://localhost:3000/api npm run ionic:build
npm run serve
```

This may do what you want

**Comment by osagga** [comment]
@micahriggan Yeah but running insight-prev using `npm start` does not run it in `prod` env. Do you know how can I run it in `prod` but also have it point to a local node? Other than setting the prefix to an exposed node address?

https://github.com/bitpay/bitcore/blob/34facd65e2a9e52b205270405d1018181830dca2/packages/insight-previous/package.json#L31

**Comment by osagga** [comment]
I figured I would use just use the ip of the current machine I'm running the node and insight on. Closing this for now.
