### ISSUE TITLE
Unconfirmed transaction and tx id on bitpay insights

### ISSUE THREAD

**Issue by bhageshvar** [bitpay/bitcore#1985]
I have some trouble with bitpay insights on the insights it shows my transaction as unconfirmed 
https://insight.bitpay.com/tx/1e9b29a58c3f7467afa29996a31a835db244088eb2f74f5d107c70311606be8e

Couldnt find this transaction valid in any other blockchain explorers. Is it possible to recover this btc?

**Comment by micahriggan** [comment]
If you cannot find this transaction in a block explorer, it's likely that it wasn't mined, and also likely it didn't make it into the mempool. If you restore your wallet from your 12 words, or whatever backup you have, then I imagine you'll still have the same btc that you had before this transaction.
