### ISSUE TITLE
lerna ERR! npm run compile stderr: sh: ./node_modules/.bin/tsc: No such file or directory

### ISSUE THREAD

**Issue by yangliulnn** [bitpay/bitcore#1988]
* OS: macOS 10.14.2
* node: v10.14.2
* npm: 6.4.1

``` bash
➜  bitcore git:(master) ✗ npm i

> @8.0.0 postinstall /Users/leo/Desktop/bitcore
> npm run bootstrap && npm run compile


> @8.0.0 bootstrap /Users/leo/Desktop/bitcore
> lerna bootstrap

lerna notice cli v3.6.0
lerna info Bootstrapping 14 packages
lerna info Installing external dependencies
lerna info Symlinking packages and binaries
lerna info lifecycle @bitpay/insight-previous@8.0.0~postinstall: @bitpay/insight-previous@8.0.0

> @bitpay/insight-previous@8.0.0 postinstall /Users/leo/Desktop/bitcore/packages/insight-previous
> ./node_modules/.bin/webdriver-manager update --gecko false

webdriver-manager: using local installed version 12.1.1
[10:30:57] I/config_source - curl -o/Users/leo/Desktop/bitcore/packages/insight-previous/node_modules/webdriver-manager/selenium/standalone-response.xml https://selenium-release.storage.googleapis.com/
[10:30:57] I/config_source - curl -o/Users/leo/Desktop/bitcore/packages/insight-previous/node_modules/webdriver-manager/selenium/chrome-response.xml https://chromedriver.storage.googleapis.com/
[10:30:58] I/update - chromedriver: file exists /Users/leo/Desktop/bitcore/packages/insight-previous/node_modules/webdriver-manager/selenium/chromedriver_2.46.zip
[10:30:58] I/update - chromedriver: unzipping chromedriver_2.46.zip
[10:30:58] I/update - chromedriver: setting permissions to 0755 for /Users/leo/Desktop/bitcore/packages/insight-previous/node_modules/webdriver-manager/selenium/chromedriver_2.46
[10:30:58] I/update - chromedriver: chromedriver_2.46 up to date
[10:30:58] I/update - selenium standalone: file exists /Users/leo/Desktop/bitcore/packages/insight-previous/node_modules/webdriver-manager/selenium/selenium-server-standalone-3.141.59.jar
[10:30:58] I/update - selenium standalone: selenium-server-standalone-3.141.59.jar up to date
lerna success Bootstrapped 14 packages

> @8.0.0 compile /Users/leo/Desktop/bitcore
> lerna run compile

lerna notice cli v3.6.0
lerna info Executing command in 2 packages: "npm run compile"
lerna info run Ran npm script 'compile' in 'bitcore-client' in 4.2s:

> bitcore-client@8.0.0 compile /Users/leo/Desktop/bitcore/packages/bitcore-client
> npm run clean && ./node_modules/.bin/tsc


> bitcore-client@8.0.0 clean /Users/leo/Desktop/bitcore/packages/bitcore-client
> rm -rf ./ts_build

lerna ERR! npm run compile exited 1 in 'bitcore-node'
lerna ERR! npm run compile stdout:

> bitcore-node@8.0.1 compile /Users/leo/Desktop/bitcore/packages/bitcore-node
> npm run tsc


> bitcore-node@8.0.1 tsc /Users/leo/Desktop/bitcore/packages/bitcore-node
> npm run clean && ./node_modules/.bin/tsc


> bitcore-node@8.0.1 clean /Users/leo/Desktop/bitcore/packages/bitcore-node
> rm -rf build


lerna ERR! npm run compile stderr:
sh: ./node_modules/.bin/tsc: No such file or directory
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! bitcore-node@8.0.1 tsc: `npm run clean && ./node_modules/.bin/tsc`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the bitcore-node@8.0.1 tsc script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/leo/.npm/_logs/2019-02-13T02_31_05_701Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bitcore-node@8.0.1 compile: `npm run tsc`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bitcore-node@8.0.1 compile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/leo/.npm/_logs/2019-02-13T02_31_05_730Z-debug.log

lerna ERR! npm run compile exited 1 in 'bitcore-node'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @8.0.0 compile: `lerna run compile`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @8.0.0 compile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/leo/.npm/_logs/2019-02-13T02_31_05_771Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @8.0.0 postinstall: `npm run bootstrap && npm run compile`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @8.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/leo/.npm/_logs/2019-02-13T02_31_05_814Z-debug.log
```

**Comment by micahriggan** [comment]
@yangliulnn Just saw this, is this still happening?

**Comment by yangliulnn** [comment]
@micahriggan Switch node to v8.15.0, it works.
Thanks.

**Comment by micahriggan** [comment]
Okay, I'll look into how to get it working on node 10,because it used to.

**Comment by datgrog** [comment]
Got the same error in "same" mac env.
Got pyenv local 2.7.10 and nvm use v8.15.0 but still same error output after `npm i` under bitcore release 8.1.0, how did you make it works ?

**Comment by zming** [comment]
I Got the same error, my env:
OS:  CentOS Linux release 7.5.1804 (Core)
npm: 6.4.1
node: v8.15.0
mongodb: 4.0.9
bitcore: master

when run 'npm run node', I got this error:
[root@aming bitcore]# npm run node

> @8.1.0 node /usr/local/bitcore
> cd packages/bitcore-node && npm start


> bitcore-node@8.3.0 start /usr/local/bitcore/packages/bitcore-node
> npm run tsc && node build/src/server.js


> bitcore-node@8.3.0 tsc /usr/local/bitcore/packages/bitcore-node
> npm run clean && ./node_modules/.bin/tsc


> bitcore-node@8.3.0 clean /usr/local/bitcore/packages/bitcore-node
> rm -rf build

sh: ./node_modules/.bin/tsc: 没有那个文件或目录
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! bitcore-node@8.3.0 tsc: `npm run clean && ./node_modules/.bin/tsc`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the bitcore-node@8.3.0 tsc script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-04-24T09_18_31_348Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bitcore-node@8.3.0 start: `npm run tsc && node build/src/server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bitcore-node@8.3.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-04-24T09_18_31_414Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @8.1.0 node: `cd packages/bitcore-node && npm start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @8.1.0 node script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-04-24T09_18_31_489Z-debug.log

**Comment by micahriggan** [comment]
Make sure you've run npm from the bitcore directory

**Comment by zming** [comment]
yes, I'm sure then I had run 'npm install ' from the bitcore directory, and get some waring like that
[root@aming bitcore]# pwd
/usr/local/bitcore
[root@aming bitcore]# npm install
npm WARN lifecycle @8.1.0~postinstall: cannot run in wd @8.1.0 npm run bootstrap && npm run compile (wd=/usr/local/bitcore)
npm WARN eslint-config-airbnb-base@12.1.0 requires a peer of eslint@^4.9.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-import@2.12.0 requires a peer of eslint@2.x - 4.x but none is installed. You must install peer dependencies yourself.
npm WARN @8.1.0 No repository field.
npm WARN @8.1.0 No license field.

audited 1492539 packages in 18.621s
found 377 vulnerabilities (49 moderate, 328 high)
  run `npm audit fix` to fix them, or `npm audit` for details
