### ISSUE TITLE
(insight-prev) currency unit is not set to the current blockchian

### ISSUE THREAD

**Issue by osagga** [bitpay/bitcore#1991]
When I go to the following url: `http://localhost:8200/#/BTC/regtest/address/mxdVpA5dzGNeDZnQ16GhzyDvgy2yM1oaS4 `

on local running node, I notice that the currency unit shown is `NULL` as shown below
![image](https://user-images.githubusercontent.com/5073889/52792133-a2d9df00-3038-11e9-98c5-5ede5ad9893b.png)

It doesn't seem that the unit is extracted from the blockchain I'm looking at, this feature used to work correctly before. 

The currency also doesn't change when I change networks using the coin selector (top right).

**Comment by osagga** [comment]
@rastajpa @cmgustavo Can you please help with this? I'm running `insight-prev` in `prod` mode, could that be the reason? The currency used to be auto-set, but now it doesn't seem to be extracted from the url.

**Comment by cmgustavo** [comment]
Are you running your own `bitcore-node`? You need it to get the list of available chains: `api/status/enabled-chains`

**Comment by micahriggan** [comment]
@osagga are you running with only one chain/network enabled? I've noticed a bug in the chain/network selection when I run only one enabled

**Comment by osagga** [comment]
@cmgustavo, yes I'm running my own node, and the endpoint `api/status/enabled-chains` returns the current chains as follows (you can test my setup here: https://bitcore-testnet-vpc-0215-2213.commonwealthcrypto.net:5000):
![image](https://user-images.githubusercontent.com/5073889/52964552-8c04f680-3370-11e9-97f8-40579c0bb9a9.png)

@micahriggan I have BTC, BCH and LTC available.
I also noticed that insight always defaults to `BTC` on `mainnet` even if I set the value of `BLOCKCHAIN` and `NETWORK` otherwise
https://github.com/bitpay/bitcore/blob/96eda6fd943bfab987268b8cac59a5975b373186/packages/insight-previous/package.json#L28

Note that I'm running insight on `prod`, so maybe this is a bug just in `prod` environment.

**Comment by rastajpa** [comment]
@osagga thanks to reporting this. We will work on fix this bug soon.

**Comment by osagga** [comment]
Thanks @rastajpa, this problem seems to be fixed by the PR #2009. Closing this for now
