### ISSUE TITLE
npm install failed when npm run bootstrap && npm run compile

### ISSUE THREAD

**Issue by zhiquan911** [bitpay/bitcore#2010]
npm install 
-----------------

bitcore@fcb3668cf2a6:~/bitcore$ npm install
npm WARN package.json @8.0.0 No repository field.
npm WARN package.json @8.0.0 No license field.

> @8.0.0 postinstall /home/bitcore/bitcore
> npm run bootstrap && npm run compile

> @8.0.0 bootstrap /home/bitcore/bitcore
> lerna bootstrap

/home/bitcore/bitcore/node_modules/lerna/node_modules/@lerna/cli/node_modules/yargs/lib/command.js:22
    globalMiddleware.push(...middlewares)
                          ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/bitcore/bitcore/node_modules/lerna/node_modules/@lerna/cli/node_modules/yargs/lib/argsert.js:2:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

npm ERR! Linux 4.4.0-117-generic
npm ERR! argv "/home/bitcore/.nvm/versions/node/v4.9.1/bin/node" "/home/bitcore/.nvm/versions/node/v4.9.1/bin/npm" "run" "bootstrap"
npm ERR! node v4.9.1
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE
npm ERR! @8.0.0 bootstrap: `lerna bootstrap`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @8.0.0 bootstrap script 'lerna bootstrap'.
npm ERR! This is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     lerna bootstrap
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/bitcore/bitcore/npm-debug.log

npm ERR! Linux 4.4.0-117-generic
npm ERR! argv "/home/bitcore/.nvm/versions/node/v4.9.1/bin/node" "/home/bitcore/.nvm/versions/node/v4.9.1/bin/npm" "install"
npm ERR! node v4.9.1
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE
npm ERR! @8.0.0 postinstall: `npm run bootstrap && npm run compile`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @8.0.0 postinstall script 'npm run bootstrap && npm run compile'.
npm ERR! This is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run bootstrap && npm run compile
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/bitcore/bitcore/npm-debug.log

**Comment by micahriggan** [comment]
That sounds like your node.js doesn't support spread syntax

https://node.green/ shows which versions are compatible with that, you'll have to upgrade to a higher version.

I'm on v8.15.0

**Comment by zhiquan911** [comment]
Thank you very much！The problem has been solved.
