### ISSUE TITLE
Release 8.1.0 -> lerna ERR! npm run compile stderr: sh: ./node_modules/.bin/tsc: No such file or directory

### ISSUE THREAD

**Issue by datgrog** [bitpay/bitcore#2037]
Same as `https://github.com/bitpay/bitcore/issues/1988`, I'm unable to `npm i` on bitcore `8.1.0` but its working on `8.0.0` with node 8.15.0

**Comment by micahriggan** [comment]
can you give me the output of 
```
ls -al node_modules/.bin
```

**Comment by datgrog** [comment]
Weirdly since `npm i` worked on 8.0.0,  both git checkout on 8.1.0 or a released's downloaded zip `npm i` works at it should ...

**Comment by micahriggan** [comment]
0_o .    So, it didn't install, then you were able to install on the 8.0.0 branch, then switching back to 8.1.0 you were able to install again? That's a weird one. Does it fail to install on 8.1.0 if you

```
rm -rf node_modules
rm -rf packages/*/node_modules
```

**Comment by datgrog** [comment]
Exactly, I'll try that tomorrow and keep you updated, thanks for the fast reply
