### ISSUE TITLE
Get all tx by address

### ISSUE THREAD

**Issue by Alexadar** [bitpay/bitcore#2072]
Hi guys! Im new here
Is it possible through this api get transaction txin and txo by tx hash?
I see there is no API methods for it, but im sure there is some workaround?
I need to show all incoming and outgoing transactions on my website, with values and addresses?
If no, is it possible to query DB somehow to get this data?

Appreciate!

**Comment by penghap** [comment]
https://github.com/bitpay/bitcore/blob/40b1d39d29482d9cf4ac15737a3949943e7ea2a4/packages/bitcore-node/src/routes/api/tx.ts#L80
 may can get transaction txin and txo by tx hash.

I add `addresses` in transactions.  it possible to query transaction by address. But it is testing, Hope this helps you. 
[https://github.com/imTouch/bitcore/tree/feature/tx-addresses](https://github.com/imTouch/bitcore/tree/feature/tx-addresses)

**Comment by Alexadar** [comment]
> [bitcore/packages/bitcore-node/src/routes/api/tx.ts](https://github.com/bitpay/bitcore/blob/40b1d39d29482d9cf4ac15737a3949943e7ea2a4/packages/bitcore-node/src/routes/api/tx.ts#L80)
> Line 80 in [40b1d39](/bitpay/bitcore/commit/40b1d39d29482d9cf4ac15737a3949943e7ea2a4)
>  router.get('/:txid/coins', (req, res, next) => { 
> 
> may can get transaction txin and txo by tx hash.
> I add `addresses` in transactions. it possible to query transaction by address. But it is testing, Hope this helps you.
> https://github.com/imTouch/bitcore/tree/feature/tx-addresses

Yes, it will thanks.

Actually im looking to api what will get all incoming and ountgoing transactions for address.
Right now i use curl -v localhost:3000/api/BTC/mainnet/address/15VjRaDX9zpbA8LVnbrCAFzrVzN7ixHNsC/ and it seems its working. Will use your solution as well, thanks!
