### ISSUE TITLE
Problem installing bitcore on Linux

### ISSUE THREAD

**Issue by siarhei-bazhko** [bitpay/bitcore#2110]
After `npm install` got this:
![image](https://user-images.githubusercontent.com/32072534/55563693-132ee380-56ff-11e9-84d6-e36623479bab.png)

**Comment by micahriggan** [comment]
Hello! I've gotten this before as well, wondering if the package-lock file has been corrupted by a merge. Try 

`rm -rf packages/bitcore-build/package-lock.json` and it should fix it

**Comment by bozhkosergei** [comment]
> Hello! I've gotten this before as well, wondering if the package-lock file has been corrupted by a merge. Try
> 
> `rm -rf packages/bitcore-build/package-lock.json` and it should fix it

thank you! it works now

**Comment by MitchellCash** [comment]
Had the same problem and also confirm @micahriggan suggestion solved my issue. Good to get a clean `package-lock.json` merged if that is the best solution.

**Comment by orangecstsne04** [comment]
Thanks. Will work on fixing error.

**Comment by micahriggan** [comment]
A new package-lock has been merged in, this should be fixed.

**Comment by MitchellCash** [comment]
@micahriggan great! I pulled down a fresh clone of the repo and confirm this issue is resolved for me.
