### ISSUE TITLE
Get block by height

### ISSUE THREAD

**Issue by monsterbitar** [bitpay/bitcore#2153]
There currently seems to be missing a very basic function, looking up a block by the blockheight.

I suggest that you add another conditional for the curreny block/ request that checks if the requested information is a number for a valid blockheight and if so, return the block information for that block.

**Comment by osagga** [comment]
If you're talking about the API, there does exist an endpoint that does exactly that. Although not explicitly documented here (maybe make a PR that fixed the docs): https://github.com/bitpay/bitcore/blob/master/packages/bitcore-node/docs/api-documentation.md#get-block

But `blockId` can be either a blockhash, or a block height, check the implementation here:
https://github.com/bitpay/bitcore/blob/353d857d7d0dcf9b1c9433257d901a1813530c21/packages/bitcore-node/src/routes/api/block.ts#L38-L53

To test this out, check this url: https://api.bitcore.io/api/BTC/mainnet/block/573330
This one takes in a hash for the same block: https://api.bitcore.io/api/BTC/mainnet/block/00000000000000000026eb3bda7421ccd5db801e645435090746f72e4f859c61

**Comment by monsterbitar** [comment]
While this wasn't well documented, it appears to work just fine. One call less I need to do with a separate 3rd party.

Thank you.
