### ISSUE TITLE
Prune Blockchain after Bicore-node v8 Sync Complete

### ISSUE THREAD

**Issue by solaris-rig** [bitpay/bitcore#2158]
What will be the effect if I prune the blockchain once the v8 sync?

**Comment by micahriggan** [comment]
Are you talking about the spentScript pruning in bitcore's config, or a bitcoind thing?

**Comment by solaris-rig** [comment]
bitcoind setting. also i have problem connecting to bitcoind if I set the maxconnextions, any advice

**Comment by upklio** [comment]
I am interested to know how insight will function after pruning the stored blockchain.
