### ISSUE TITLE
Works incorrectly with legacy addresses in livenet

### ISSUE THREAD

**Issue by SergeyMell** [bitpay/bitcore#2176]
I have q address `bitcoincash:qq3xznahr223r0plh636ca77tuuxy5nrdcpz9ep9qq` and correspondent legacy address `148nYqVFhRudF3awru4eoYKFxeT4pyYQHq` in livenet
```
bitcore.Address.isValid('bitcoincash:qq3xznahr223r0plh636ca77tuuxy5nrdcpz9ep9qq') // returns true
bitcore.Address.isValid('148nYqVFhRudF3awru4eoYKFxeT4pyYQHq') // returns false
```
However, for testnet everything works ok for both kinds of addresses:
```
bitcore.Address.isValid('bchtest:qzunnlw9cnwjsvv0mq95yq7ugvqrcs6nasyp0cmwj7') // returns tru
bitcore.Address.isValid('mxQLmrBQsj9trMGg5kTwVbmeGetMA6gzhb') // returns tru
```

**Comment by matiu** [comment]
We dont support "BTC" legacy addresses for BCH, we support the "Copay" address type (starting with  C/H).

So, bitcoincash:qq3xznahr223r0plh636ca77tuuxy5nrdcpz9ep9qq and CKbg7sqKaUtA9BVNYePaP3wHamfUfxuWZq will work.

For Testnet, there is no "Copay" address type, so m/n starting address are supported.
