### ISSUE TITLE
Is there a way to include the coin data when fetching transactions through the new bitcore API?

### ISSUE THREAD

**Issue by thehenrytsai** [bitpay/bitcore#2178]
Is there a way to include the coin data when fetching transactions through the new bitcore API?

I need to fetch the coin data for every single transaction and parse them, and the only way I have been able to do so it to fetch the transactions in the block, then fetch each individual coin data via thousands and thousands of REST API calls, which is inefficient and unreliable due to the sheer number of request.

**Comment by micahriggan** [comment]
You may have better luck with running your own bitcore-node and using the database if you're trying to do something data intensive

**Comment by thehenrytsai** [comment]
We do run our own bitcore node and tried go straight to the bitcore MongoDB, but perf still sucked. We ended up going directly to BCoin APIs. As a feedback though, if the new bitcore node API on node v10+ can't do this efficiently, then it is definitely a regression in features in comparison to the old "extension" model.
