### ISSUE TITLE
do we have a option to disable rateLimiter?

### ISSUE THREAD

**Issue by ww8912188** [bitpay/bitcore#2186]
For bitcore-node v8, do we have a option to disable rate limiter?

**Comment by micahriggan** [comment]
```
  "bitcoreNode": {
    "services": {
      "api": {
        "rateLimiter": {
          "disabled": true,
        }
      }
    },
```

You should be able to do that from the config

You can also whitelist an ip
```
  "bitcoreNode": {
    "services": {
      "api": {
        "rateLimiter": {
             "whitelist": ['::ffff:127.0.0.1', '::1', 'someotherip']
        }
      }
    },
```

**Comment by ww8912188** [comment]
it works as desired, thanks Micahriggan.

**Comment by ww8912188** [comment]
Hi 
```
"rateLimiter": {
          "disabled": true
}
```

**Comment by tima-t** [comment]
"bitcoreNode": {
    "services": {
      "api": {
        "rateLimiter": {
          "disabled": true,
        }
      }
    },

Remove the come after **"disabled": true,**
Don't know why, but this was an issue for the node module and I spent a few hours to find it :)

Right one:
   "bitcoreNode": {
    "services": {
      "api": {
        "rateLimiter": {
          "disabled": true
        }
      }
    },
