### ISSUE TITLE
Not connected to peer: 192.168.11.11:8332  | Chain: BCH | Network: mainnet

### ISSUE THREAD

**Issue by christroutner** [bitpay/bitcore#2198]
# Overview

I've read through a lot of similar Issues in this repository. Let me start by saying that I am trying to point Bitcore Node at a *fully synced* BCH full node. It appears a lot of the problems people have are trying to connect Bitcore Node to a full node without the full node being synced. That's not the case here.

I've tried hard to isolate the problem to something that I am doing. Steps to reproduce are as follows:

1. Start with a fresh install of Ubuntu 18.04.
2. Install Node.js v10+ LTS
3. Install MongoDB v3.6.3
4. Git clone the `master` branch of this bitcore repository.
5. npm install
6. Verify I can communicate with the fully synced BCH full node over RPC
7. Create `bitcore.config.json` in the root directory (contents below).
8. `npm run node`

Everything starts up, but the Bitcore Node hangs and repeats this line:

`Not connected to peer: 192.168.11.11:8332  | Chain: BCH | Network: mainnet`

## bitcore.config.json
```JSON
{
  "bitcoreNode": {
    "services": {
      "api": {
        "wallets": {
          "allowCreationBeforeCompleteSync": true
        }
      }
    },
    "chains": {
      "BCH": {
        "mainnet": {
          "chainSource": "p2p",
          "trustedPeers": [
            {
              "host": "192.168.11.11",
              "port": 8332
            }
          ],
          "rpc": {
            "host": "192.168.11.11",
            "port": 8332,
            "username": "bitcoin",
            "password": "password"
          }
        }
      }
    }
  }
}
```

## bitcoin.conf

Here is the `bitcoin.conf` file for my BCH (ABC v0.19.4) full node:
```JSON
# Network-related settings:
testnet=0

# Listening mode, enabled by default except when 'connect' is being used
listen=1

server=1
rpcuser=bitcoin
rpcpassword=password
rpcallowip=0.0.0.0/0

# Listen for RPC connections on this TCP port:
rpcport=8332
rpcworkqueue=64
rpcthreads=14
rpctimeout=30

txindex=1
```

**Comment by micahriggan** [comment]
P2P communication happens over a different port than RPC. To configure the p2p port, put 
`port=8333` in your bitcoin.conf and your bitcore config should be

```
"trustedPeers": [
            {
              "host": "192.168.11.11",
              "port": 8333
            }
          ],
```

**Comment by christroutner** [comment]
Great! That's what I was missing. Didn't realize that p2p port and RPC ports were different ports.

**Comment by micahriggan** [comment]
Awesome! Glad it is working :)

**Comment by christroutner** [comment]
@GitCash send $5 to @micahriggan

**Comment by GitCash** [comment]
Hey **micahriggan**, user **christroutner** tipped you **10706 bits** in Bitcoin Cash ( ~ **$5** ).

*[Click here to claim it!](https://gitcash.io/claim/micahriggan)*

You can also add the "thumbs down" reaction to **christroutner**'s comment above to prevent future tips.
