### ISSUE TITLE
bitcore-node only available on localhost

### ISSUE THREAD

**Issue by BoGnY** [bitpay/bitcore#2221]
I'm not able to use api function using external ip `curl -v 213.136.84.196:3000/api/BTC/mainnet/block/tip` because it works only with localhost `curl -v localhost:3000/api/BTC/mainnet/block/tip`

I've trie disable iptables yet.
Any idea??

**Comment by osagga** [comment]
Are you using a cloud service or something? make sure the ports are open, try to run any other example servers and check if you can access it externally, I don't think this is a problem with bitcore

**Comment by BoGnY** [comment]
Sorry, my fault...
With about 15 vps, I've used wrong external ip of another vps -.-
