### ISSUE TITLE
How to delete testnet chain from mongodb

### ISSUE THREAD

**Issue by solaris-rig** [bitpay/bitcore#2228]
can someone advice on how to drop the BTC TESTNET chain from mongodb. My ssd almost full.

**Comment by micahriggan** [comment]
You can do a remove query on blocks, transactions and coins

**Comment by solaris-rig** [comment]
Would you mind giving me an example? Im afraid im gonna remove mainnet data.

**Comment by micahriggan** [comment]
From a mongo client connected to bitcore database:

db.blocks.remove({chain: 'BTC', network: 'testnet'})

db.transactions.remove({chain: 'BTC', network: 'testnet'})

Same query for coins.

**Comment by solaris-rig** [comment]
ok... thanks a lot
