### ISSUE TITLE
Unhandled Rejection at: Error: Syncing Node Renewal Failure

### ISSUE THREAD

**Issue by christroutner** [bitpay/bitcore#2231]
Trying to sync Bitcore Node to a Bitcoin Cash testnet node. I'm consistently getting this error:

```
bitcore-node-testnet    | info: Starting API Service on port 3000
bitcore-node-testnet    | info: Starting Socket Service
bitcore-node-testnet    | info: This worker is now the syncing node for BCH testnet
bitcore-node-testnet    | info: 2019-06-09 00:41:19.951 UTC | Syncing 699 blocks | Chain: BCH | Network: testnet
bitcore-node-testnet    | Unhandled Rejection at: Error: Syncing Node Renewal Failure
bitcore-node-testnet    |     at P2pWorker.refreshSyncingNode (/home/safeuser/bitcore/packages/bitcore-node/build/src/services/p2p.js:376:23)
bitcore-node-testnet    |     at process._tickCallback (internal/process/next_tick.js:68:7)
bitcore-node-testnet    | Shutting down 62
bitcore-node-testnet    | info: Stopping P2P Manager
bitcore-node-testnet    | info: Stopping Event Service

```

**Comment by christroutner** [comment]
There was recently some bloxroute testing on testnet that generated several 32MB blocks. This may be the cause of the error.

**Comment by micahriggan** [comment]
That error happens when the node is blocking the event loop for too long while syncing, so it attempts to kill itself. Probably not dialed in for timing on your machine for 32 mb blocks

**Comment by christroutner** [comment]
Thanks for the insight @micahriggan. Is there a command-line flag I can pass to 'dial in the timing'? Got a link for more info?

**Comment by micahriggan** [comment]
We don't have it configurable, but it probably should be.

This is the line where the 5 minute time is established. I would adjust that number to however long it takes for your machine to process a 32MB block.

https://github.com/bitpay/bitcore/blob/master/packages/bitcore-node/src/services/p2p.ts#L417

The intent is to kill the node if something were to block the event loop for a large amount of time.

**Comment by christroutner** [comment]
Awesome. Exactly what I needed to know. Thanks!

**Comment by nyetwurk** [comment]
Shouldn't this stay open until that timeout is configurable via command line?
