### ISSUE TITLE
V8: broadcast raw tx via API not available

### ISSUE THREAD

**Issue by dalijolijo** [bitpay/bitcore#2234]
Is it possible to broadcast a raw transaction to blockchain via Bitcore Insight API?

If I try to broadcast with curl I get an error:
```sh
# curl --data "chain=BTX&network=mainnet&rawTx=02000000016ac3043549876ec53aa8bd4a0839c07f52211a6b880920418cbb20b54142f1cf000000006a473044022013bfe2132c843196c43993a3562868ed26b58b5667bc3f934216afcf1643b51102206d7676a5efca242255b4f9fbd1db41273164c82723b0e01f6a324e68971aacf80121035165d8ce5fa0890e14c76bdf22cdc8be9c5ee12080aad89f897cb2026b1aba2cffffffff02706f9800000000001976a914c7cb6d4f64bf68c37a052fb094f2e0ff385e8b0a88ac804a5d05000000001976a914bb89aec81ebb0812532c34d5ee997e7319012c5c88ac00000000" https://api.bitcore.cc/api/BTX/mainnet/tx/send
Expected type string, got null
```

BTW: I missing a description for API POST query like "/send" in the [API documentation](https://github.com/bitpay/bitcore/blob/master/packages/bitcore-node/docs/api-documentation.md).

**Comment by osagga** [comment]
Yes, the API endpoint is of type `POST` and requires a JSON object with the key `rawTx` and the value as the hex representation of the transaction. So in your case, using `curl`, it would be something like

```json
curl -d '{"rawTx":"02000000016ac3043549876ec53aa8bd4a0839c07f52211a6b880920418cbb20b54142f1cf000000006a473044022013bfe2132c843196c43993a3562868ed26b58b5667bc3f934216afcf1643b51102206d7676a5efca242255b4f9fbd1db41273164c82723b0e01f6a324e68971aacf80121035165d8ce5fa0890e14c76bdf22cdc8be9c5ee12080aad89f897cb2026b1aba2cffffffff02706f9800000000001976a914c7cb6d4f64bf68c37a052fb094f2e0ff385e8b0a88ac804a5d05000000001976a914bb89aec81ebb0812532c34d5ee997e7319012c5c88ac00000000"}' -H "Content-Type: application/json" -X POST https://api.bitcore.cc/api/BTX/mainnet/tx/send
```

You can check this code here to know the expected JSON object
https://github.com/bitpay/bitcore/blob/1c9066a18ebd10489b9e8dd68dab4b272f057ff9/packages/bitcore-node/src/routes/api/tx.ts#L98

Does that help?

**Comment by jeansouza** [comment]
Shouldn't that be presente in the API documentation?

**Comment by osagga** [comment]
Ideally, but its not there now, so maybe make a PR to add it?
