### ISSUE TITLE
Can It share the data directory with Omni ?

### ISSUE THREAD

**Issue by lhalcyon** [bitpay/bitcore#2244]
I already have a omni node to get USDT infomations. Now I want to know whether the __bitcore__ can share the data directory with omni . 

I need the friendly API of bitcore both on BTC mainnet and testnet :)

**Comment by micahriggan** [comment]
It can't share data with OMNI. Bitcore builds a mongodb database, and will duplicate the information present on a chain and store it structured in mongodb.

**Comment by lhalcyon** [comment]
I see .  Thank u :)
