### ISSUE TITLE
Transactions by address

### ISSUE THREAD

**Issue by jeansouza** [bitpay/bitcore#2259]
I need to get all the transactions of an address, but the endpoint `/api/BTC/mainnet/address/:address/txs` only returns outputs.

Is there a way to get the transactions of an address, with all the data returned by the endpoint `/api/BTC/mainnet/tx/:txid`?

Thanks!

**Comment by robinKdsglobal** [comment]
All inputs are from outputs，actually the endpoint `/api/BTC/mainnet/address/:address/txs` returns all transactions. It's output in 'mintTxid' transaction and input in 'spentTxid' transaction.

**Comment by jeansouza** [comment]
The thing is, I need all the data returned by `/api/BTC/mainnet/tx/:txid` (block info, for example), and I was hoping to get all that in a single request, because making more requests to each item will affect performance. In older versions of Bitcore, that I still use, I'm able to get the transactions by address, with all data, in a single request. But anyway, thanks for the reply.
