### ISSUE TITLE
I am confused about the deployment step. need help :(

### ISSUE THREAD

**Issue by lhalcyon** [bitpay/bitcore#2267]
First of all , I am intent to deploy a testnet bitcore .

I followed the doc  and did few steps below:
1. `git clone` the repo to my server
2. then I ran `npm install` and the terminal showed success.
3. I found docker-compose.test.yml , so I made a little change about user password stuff , then I ran `docker-compose -f xxx up -d` , and got mongo , ruimarinho/bitcoin-core container in docker ps .

May I ask ,  now I need to wait the bitcoin node sync complete or  run `npm run node`  ?

**Comment by micahriggan** [comment]
To sync testnet you'll want to have 
1. a bitcoin testnet node synced
2. a mongodb running
3. bitcore.config.json pointing to your testnet node
4. Npm install
5. npm run node

**Comment by lhalcyon** [comment]
Can I  use the docker-compose-test.yaml in the project to publish directly ?

**Comment by lhalcyon** [comment]
> @lhalcyon Hi..were you able to run testnet?..i have done npm install..ran mongo service..need a config file for testnet to run node..and need to know how to create a trusted peer.

haha . The latest release do not work properly .  I manage it with old version of third party. Here is the [link](https://hub.docker.com/r/m00re/bitcore) on DockerHub  .
