### ISSUE TITLE
Insight : Cannot find module "bech32"

### ISSUE THREAD

**Issue by sillyghost** [bitpay/bitcore#2348]
Hey,
Trying to run the insight explorer for a fork , it shows the following errror when on the site - Cannot find module "bech32".

I also get this error in the console while it starts - 
11:40:22]  Failed to open the browser: Command failed: xdg-open "http://localhost:8200" /bin/sh: 1: xdg-open: not found

**Comment by micahriggan** [comment]
Try running npm install in the insight folder. There's an issue where symlinks aren't getting processed correctly, so bitcore-lib doesn't work unless you pull it from npm

**Comment by sillyghost** [comment]
Great thanks , that solved it :)
