### ISSUE TITLE
Get Unspent Transaction Outputs by Address discrepancy.

### ISSUE THREAD

**Issue by kraikov** [bitpay/bitcore#2420]
There is discrepancy in the unspent TXs returned by 

```https://api.bitcore.io/api/BTC/testnet/address/mjszQZsfTUAHg6hv98p6g53f9KsqbKZMNM/?unspent=true```

and 

```https://blockstream.info/testnet/api/address/mjszQZsfTUAHg6hv98p6g53f9KsqbKZMNM/utxo```

Any ideas why?

**Comment by lazy-ape** [comment]
Bitcore API has a limit on the count of the result. Maybe you can try this :
`https://api.bitcore.io/api/BTC/testnet/address/mjszQZsfTUAHg6hv98p6g53f9KsqbKZMNM/?unspent=true&limit=1000`

**Comment by kraikov** [comment]
@lazy-ape thank you!
