### ISSUE TITLE
Regression: 80% of sync speed lost from PR 2403

### ISSUE THREAD

**Issue by jamespharvey20** [bitpay/bitcore#2459]
On 324944c (2019-10-02 13:27:14), I was getting around 12-15 blocks/min.

Upgraded to d12f725 (2019-10-12 01:51:38) and started only getting 2-3 blocks/min.

Bisected to find it starts from #2403, specifically 2833a00.  Although the first block happens quickly, it drops to 3-4 blocks/min.  By the time you get to d12f725, it starts and continues at 2-3.

I understand #2403 is to reduce memory usage, and of course anytime that happens, performance can suffer as a trade-off.

If you're synced and always running, 2-3 blocks/min is obviously fine.  But, if you don't have bitcore running all the time (or are doing an initial sync) this is quite a hit.

With this being such a performance hit, maybe an option could be added to allow keeping an entire block's data in memory all at once, even if it's defaulted to off?

Interestingly, the slowing-down-commit's parent afc96cd I was seeing extreme speeds like 40-50 blocks/min.  I'm wondering if there could be an option to allow this too, although I'm not sure what the risk is for not "await[ing] the bulkWrite".  Don't know if it risks data not being available when required, or data loss during crash, or anything like that.  But, I at least am not seeing any bad effects from the short while it ran at this speed during the bisecting.

I also understand there is a large amount of variance in performance.  I'm only paying attention to huge changes like the 80% I'm consistently seeing.

EDIT: I've never synced testnet.  If the big issue is a/several 32MB block(s) on testnet, perhaps each block's size could be examined when syncing it, and if it's small (<2MB) higher memory usage wouldn't be a problem, but if it's large, the lower memory footprint method could be used on it?  To date, the largest live block size appears to be < 1.3MB.  Of course, someday block sizes will likely grow.

**Comment by micahriggan** [comment]
Thanks for the report, I think we can make it a bit faster. Right now the batch size used is sort of arbitrary, so I'll mess with that. 

As for not awaiting that bulk write, we do need the mints to be saved, during the spending phase, but that's the only real requirement.

**Comment by jamespharvey20** [comment]
I just did some trials with `[packages/bitcore-node] npm run benchmark`.

Looks like #2461 brings performance back to where it was, thanks!  Even if the still 5% performance degradation on 1MB blocks isn't variance (doesn't appear to be after a few runs), that's close enough for me.  And, I see on your system, there's no significant difference at all.

By the way, am I correct that the benchmark creates its own benchmark chain, so its measurements are only affected by the code and the machine it's running on, and unaffected by the live chain state and block height in mongodb?  So, the benchmark results aren't slowed down as the chain grows and inevitably slows down live chain syncing?

On 324944c:

    Benchmark for 80 (1 MB) blocks completed after 51.188 s
    1.5628662967883098 MB/s
    0.63985 Seconds/Block
    Benchmark for 5 (32 MB) blocks completed after 107.299 s
    1.4911602158454411 MB/s
    21.4598 Seconds/Block

On d12f725 (current master):

    Benchmark for 80 (1 MB) blocks completed after 144.07 s
    0.5552856250433817 MB/s
    1.800875 Seconds/Block
    Benchmark for 5 (32 MB) blocks completed after 237.03 s
    0.6750200396574273 MB/s
    47.406 Seconds/Block

On d12f725 (current master) with bd4ebae:

    Benchmark for 80 (1 MB) blocks completed after 144.11 s
    0.5551314967732981 MB/s
    1.801375 Seconds/Block
    Benchmark for 5 (32 MB) blocks completed after 238.458 s
    0.6709776983787501 MB/s
    47.6916 Seconds/Block

On d12f725 (current master) with bd4ebae and a0ed9dd:

    Benchmark for 80 (1 MB) blocks completed after 53.811 s
    1.486684878556429 MB/s
    0.6726375 Seconds/Block
    Benchmark for 5 (32 MB) blocks completed after 106.14 s
    1.5074429998115697 MB/s
    21.228 Seconds/Block
    Benchmark for 1 (64 MB) blocks completed after 25.675 s
    2.49269717624148 MB/s
    25.675 Seconds/Block
