### ISSUE TITLE
Test with Bitcoin Core pull-tester / regression test mode

### ISSUE THREAD

**Issue by jgarzik** [bitpay/bitcore#255]
Each pull request to https://github.com/bitcoin/bitcoin/ is tested by an automated tester, which supplies many test cases not covered by https://github.com/bitcoin/bitcoin/tree/master/src/test

This utilizes "-regtest" mode of bitcoind, a special mode that permits less-than-difficulty-1 blocks to be valid -- thereby permitting the creation of tests that simulate multiple-block conditions like reorgs.  Basically, blocks are instantly confirmed, in -regtest mode.

bitcore should
* have a pull tester robot, for each new commit, just like Bitcoin Core
* pass all the tests that Bitcoin Core has in the pulltester

Passing all these tests will require someone to implement full block chain validation in bitcore, e.g. https://en.bitcoin.it/wiki/Protocol_rules

Today, bitcore only passes the basic in-tree Bitcoin Core tests, not the more advanced pulltester tests.

**Comment by braydonf** [comment]
This is likely most relevant with https://github.com/bitpay/bitcore-node now, the regtest feature is being used for the bindings with the CI tester. Since we're using Bitcoin Core code as a library, would it still be necessary since this is already tested?

**Comment by posita** [comment]
> This is likely most relevant with https://github.com/bitpay/bitcore-node now, the regtest feature is being used for the bindings with the CI tester. Since we're using Bitcoin Core code as a library, would it still be necessary since this is already tested?

I asked this question [here](https://github.com/bitpay/insight-api/issues/297#issuecomment-126768483), but didn't get any response. [W]hat's the strategy for [`insight`](https://github.com/bitpay/insight) (the UI) then? What will the stack look like?

```
+--------------+
|   insight    |        +-----------------------------+
+------v-------+        |           insight           |         ___
| insight-api  |        +------v-------+------v-------+        |__ \
+------v-------+  -or-  | insight-api  > bitcore-node |  -or-    / /
| bitcore-node |        +------v-------+------v-------+         |_|
+------v-------+        |          bitcoind           |         (_)
|   bitcoind   |        +-----------------------------+
+--------------+
```

Or are `insight`/`insight-api` going to be EOL'ed?

**Comment by braydonf** [comment]
Responded there.
