### ISSUE TITLE
ETH Node Sync

### ISSUE THREAD

**Issue by PeterRogers123** [bitpay/bitcore#2571]
So i have managed to setup bitcore to run very smoothly with my parity node.
The Problem i am facing at the moment is that when bitcore is up to date on my nodes blocks it enters a idle state and does not come out of it to get new blocks as they come in.

The message displayed is {"message":"ETH:ROSPEN up to date.","level":"info"}

Once that message is displayed the new blocks dont get detected as they come in.
The only way to resolve this is to restart bitcore which is not a viable option.

Has any body run into this issue before when using bitcore with parity?

**Comment by micahriggan** [comment]
Are you using websockets in the config

**Comment by PeterRogers123** [comment]
Here is the current config:
{
  "bitcoreNode": {
    "services": {
      "api": {
        "wallets": {
          "allowCreationBeforeCompleteSync": true
        }
      }
    },
    "chains": {
      "ETH": {
        "ROSPEN": {
          "chainSource": "p2p",
          "provider": {
            "host": "10.0.0.12",
            "port": 8545
          },
 	  "rpc": [
            {
              "host": "10.0.0.12",
              "port": 8545
            }
          ]
        }
      }
    }
  }
}

**Comment by PeterRogers123** [comment]
Any update on this?

**Comment by micahriggan** [comment]
My config looks like this 
```
      "ETH": {
        "mainnet": {
          "chainSource": "p2p",
          "trustedPeers": [
            {
              "host": "127.0.0.1",
              "port": 30303
            }
          ],
          "provider": {
            "host": "127.0.0.1",
            "protocol": "ws",
            "port": 9546
          }
        },
        "dev": {
          "chainSource": "p2p",
          "trustedPeers": [
            {
              "host": "127.0.0.1",
              "port": 30303
            }
          ],
          "provider": {
            "host": "127.0.0.1",
            "protocol": "ws",
            "port": 9546
          }
        }
      },
```

You have to use websockets for the block events to come through

**Comment by PeterRogers123** [comment]
This resolved the issue! Great work! Thanks!

**Comment by micahriggan** [comment]
Thanks for commenting :) 

I'll look into adding an interval to check for new blocks if you're using the http protocol.
