### ISSUE TITLE
Example of persisting a transaction end-to-end?

### ISSUE THREAD

**Issue by cappslock** [bitpay/bitcore#2578]
Hi, I'm extremely new to bitcoin & blockchain so it's likely this is a newbie question where I'm missing some basic understanding, if so, I'd appreciate a nudge in the right direction.

Anyways, I'm trying to evaluate whether I can use the various libraries in the monorepo to create a wallet and send/receive bitcoin _without_ using the actual Bitcore server. The docs and example have been helpful in illustrating how to create a wallet and generate a transaction, but I'm not clear on how to actually _persist_ this to the blockchain. I imagine it's done with the p2p class, but I haven't been able to find anything that illustrates how this is done.

Any advice would be appreciated. Thank you.

**Comment by micahriggan** [comment]
You can use RPC to broadcast a transaction to a bitcoin node, or use bitcore-client, or something that posts the transaction to our bitcore-node at api.bitcore.io

You can also broadcast using the p2p class and creating a broadcast message with your raw transaction

**Comment by cappslock** [comment]
Thanks for the reply. Is the API public? Is there an example of any of these things in the codebase I can reference somewhere?

**Comment by micahriggan** [comment]
# P2p
You can connect to a pool of p2p nodes

https://github.com/bitpay/bitcore/blob/master/packages/bitcore-node/src/modules/bitcoin/p2p.ts#L45

Then you can make the message with something like this 

https://github.com/bitpay/bitcore/blob/master/packages/bitcore-p2p/test/messages/commands/index.js#L49

And then you would send it with 

https://github.com/bitpay/bitcore/blob/master/packages/bitcore-node/src/modules/bitcoin/p2p.ts#L154

# Bitcore Api
If you want to use our bitcore api, you could use this method on bitcore-client, or just post to the endpoint with request

https://github.com/bitpay/bitcore/blob/master/packages/bitcore-client/src/wallet.ts#L268
https://github.com/bitpay/bitcore/blob/master/packages/bitcore-client/src/client.ts#L158


If you want to see some examples of creating and signing transactions you can checkout crypto-wallet-core to see how we make and sign txs for all the currencies in the wallet
https://github.com/bitpay/bitcore/tree/master/packages/crypto-wallet-core/src/transactions

# Rpc 
If you have a mainnet node, and you want to send your transaction via 
https://github.com/bitpay/bitcore/blob/master/packages/bitcore-node/src/rpc.ts#L89

**Comment by cappslock** [comment]
Thank you, this is extremely helpful.
