### ISSUE TITLE
How to get raw transaction (hex) by txid

### ISSUE THREAD

**Issue by cy92830** [bitpay/bitcore#2626]
For bitcoin, when we use `getrawtransaction`, we can get `hex` of transaction by txid.
But in bitcore-node, we cannot find that field.
Is there any way to get raw transaction (hex) by txid?

**Comment by micahriggan** [comment]
not currently, but I see how that could be useful

**Comment by osagga** [comment]
@cy92830 note that until this feature is supported on the main repo, you can use apply this [commit](https://github.com/cwcrypto/bitcore-1/commit/078115bcf9f5e95295d08e61ab8e5690897d902f) to your own fork to get the raw transactions as part of the `/tx/` endpoint

**Comment by ChristianOConnor** [comment]
Hey I would really love this feature too. Is it live yet? Is there any way to get the raw transaction in hexidecimal now?

**Comment by cy92830** [comment]
You can follow the [commit](https://github.com/cwcrypto/bitcore-1/commit/078115bcf9f5e95295d08e61ab8e5690897d902f) to build one. It works.
