### ISSUE TITLE
bitcore-wallet-service MongoError + Checksum mismatch exception error

### ISSUE THREAD

**Issue by Ahmed18** [bitpay/bitcore#2637]
hello guys,
i updated my bitcore from a very old version 3.1.3 to the new bitcore v8
everything working fine .. the bitcoind, bitcore node and sync 100% completed.

but when i tried to open the bitcore-wallet-service i am receiving these errors in the log file:

`(node:25079) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): MongoError: Index with name: address_1 already exists with different options`

the second error is: 
`
../bitcore/packages/bitcore-lib/lib/encoding/base58check.js:57
throw new Error("Checksum mismatch");
`

and i have another question i modified the config.js to connect to my local node at url: 'http://localhost:3000' but it is connecting to url: 'https://api.bitcore.io', ?

**Comment by justinkook** [comment]
Hi!

It seems like you have wrong indexes on the BWS database. 
You can try to drop the indexes using this command for a temporary fix:
```
db.getCollection(‘addresses’).dropIndex('address_1 ')
```

Also you have to change `blockchainexplorer.ts` to point to `http://localhost:3000` as well!

https://github.com/bitpay/bitcore/blob/master/packages/bitcore-wallet-service/src/lib/blockchainexplorer.ts

**Comment by micahriggan** [comment]
For the index issue, you can drop that index in mongo, and the code will re-create it with the new options
```
mongo
use bws
db.dropIndex("address_1")
```
restart the project


For the base58 one, that might be related to some validation failing with network matching. Which chain and network are you using?

For the bws config you'd actually need to change a few other places. I reccomend searching the codebase for api.bitcore. There are like 3 or 4 places I think that would need to be changed.

**Comment by Ahmed18** [comment]
thanks guys for your replies.
the mongo problem has been fixed also the connection to local node.

but the base58 is not fixed this is the complete error log: 
`info V8 connecting socket at:http://localhost:3000 
info Read operations set to secondaryPreferred 
info Using message broker server at http://localhost:3380 
info Connected to wallets V8 (btc/mainnet) @ http://localhost:3000 

../bitcore/packages/bitcore-lib/lib/encoding/base58check.js:57
    throw new Error("Checksum mismatch");
          ^
Error: Checksum mismatch
    at Function.Base58Check.decode (../bitcore/packages/bitcore-lib/lib/encoding/base58check.js:57:11)
    at Function.PrivateKey._transformWIF (../bitcore/packages/bitcore-lib/lib/privatekey.js:196:50)
    at PrivateKey._classifyArguments (../bitcore/packages/bitcore-lib/lib/privatekey.js:108:25)
    at new PrivateKey (../bitcore/packages/bitcore-lib/lib/privatekey.js:48:19)
    at getAuthPayload (../bitcore/packages/bitcore-wallet-service/src/lib/blockchainexplorers/v8.ts:483:27)
    at Socket.<anonymous> (../bitcore/packages/bitcore-wallet-service/src/lib/blockchainexplorers/v8.ts:512:9)
    at Socket.Emitter.emit (../bitcore/packages/bitcore-wallet-service/node_modules/component-emitter/index.js:133:20)
    at Socket.emit (../bitcore/packages/bitcore-wallet-service/node_modules/socket.io-client/lib/socket.js:138:10)
    at Socket.onconnect (../bitcore/packages/bitcore-wallet-service/node_modules/socket.io-client/lib/socket.js:335:8)
    at Socket.onpacket (../bitcore/packages/bitcore-wallet-service/node_modules/socket.io-client/lib/socket.js:232:12)
    at Manager.<anonymous> (../bitcore/packages/bitcore-wallet-service/node_modules/component-bind/index.js:21:15)
    at Manager.Emitter.emit (../bitcore/packages/bitcore-wallet-service/node_modules/component-emitter/index.js:133:20)
    at Manager.ondecoded (../bitcore/packages/bitcore-wallet-service/node_modules/socket.io-client/lib/manager.js:345:8)
    at Decoder.<anonymous> (../bitcore/packages/bitcore-wallet-service/node_modules/component-bind/index.js:21:15)
    at Decoder.Emitter.emit (../bitcore/packages/bitcore-wallet-service/node_modules/component-emitter/index.js:133:20)
    at Decoder.add (../bitcore/packages/bitcore-wallet-service/node_modules/socket.io-parser/index.js:251:12) `

my chain is BTC and network livenet .. i removed the bch and eth from the config.ts file and from the blockchainexplorer.ts because i needs only BTC.
 also my  bitcore.config.json contains only BTC and connected to bitcoin v0.19.0.1

my old wallet was multi-sign wallet.

**Comment by Ahmed18** [comment]
OK guys this problem comes from socketApiKey parameter in the config.ts .. you must provide hexa encoded number not 'socketApiKey'

**Comment by smk-windsor** [comment]
@Ahmed18 may I ask how are you generating the Hexa encoded number?

**Comment by micahriggan** [comment]
I think you can do 
```
new BitcoreLib.PrivateKey().toString()
```

You just want a random privatekey as a hex string

**Comment by smk-windsor** [comment]
@micahriggan thanks for the prompt response. If you don't mind I had a follow-up question, clearly, I was doing it wrong in regards to generating the socketApiKey. But it did not really fix my issue so maybe I can be a little more specific

I am getting the following error from logs/bcmonitor.log, this makes me assume it is the reason my email notifications don't fire. Since the onIncomingPayments never triggers ie I never see it in the log. Now I am testing on testnet but I assume it should work regardless of network. I could be way off too so just hoping you might be able to help.

```
{"message":"Error joining room Authentication failed BTC/mainnet","level":"error"}
{"message":"Error joining room Authentication failed BTC/testnet","level":"error"} 
```

**Comment by micahriggan** [comment]
Ah, you need to have the public key in bitcore-node

https://github.com/bitpay/bitcore/blob/master/packages/bitcore-node/src/services/socket.ts#L71

https://github.com/bitpay/bitcore/blob/master/packages/bitcore-node/src/config.ts#L82

So you'll need to set config.socket.bwsKeys to an array that includes your public key.

You can get your public key from your privateKey.

Something like this:
```
new BitcoreLib.PrivateKey(privKey).publicKey.toString()
```

**Comment by smk-windsor** [comment]
Lol I did explore the bitcore-node and actually saw that but I was under the impression that you don't need to run your own node hence we kept it pointing at `https://api.bitcore.io`, in fact, this was going to be the last option ie run our own node. It made me wonder if we had to get a specific public key from `https://api.bitcore.io`.

So to clarify we have to run our own node essentially?

**Comment by micahriggan** [comment]
For that room, it's for all wallet events, so that's more of an admin type room.

Joining a room for a specific set of wallets would be a good feature for your use case, where you want to run your own bws, but not your own bitcore node.

**Comment by smk-windsor** [comment]
Ideally, it would have been great to avoid running a node at present. But we also want to be able to get notifications for incoming payments and probably other types of notifications listed in the email/push services. 

The key is these wallets (users) have the option to add and remove themselves from notifications so the 'specifics set of wallets' is dynamic and ever-changing. Which makes me think based on your reply we need to join an admin type room (to catch all wallets events) and thus we must run a node? please confirm my thinking? at the end of the day if we need to run the node because of our needs it's not the end of the world
