### ISSUE TITLE
double spent tx problem

### ISSUE THREAD

**Issue by rlaace423** [bitpay/bitcore#2648]
Hello, I'm using bitcore-node for my project. It works well, but I found something while processing **bitcoin testnet** data.

There's two txs,
- 840a8fbec9eb4a40ca5e4433f2f04245352171febeec2f4728b4fdc626a794fd
- b36334f3087fb38d448a98ced8102ca01092d2e4e7130e53d9faa7bd6acaad84

And finally, The latter one accepted.

- 840a.. (https://live.blockcypher.com/btc-testnet/tx/840a8fbec9eb4a40ca5e4433f2f04245352171febeec2f4728b4fdc626a794fd/)

- b363.. (https://live.blockcypher.com/btc-testnet/tx/b36334f3087fb38d448a98ced8102ca01092d2e4e7130e53d9faa7bd6acaad84/)

But in my mongodb transactions collection, blockHeight value for 840a... is not -3, just -1.

So, how can I determine which tx was double spent?

Here's mongodb data for tx 840a.. which is rejected by blockchain.
![image](https://user-images.githubusercontent.com/5516480/71424295-a10a8e80-26d3-11ea-9eb8-7da097394722.png)

And Here's for tx b363.. which is accepted.
![image](https://user-images.githubusercontent.com/5516480/71424316-cc8d7900-26d3-11ea-9fd4-817d6b3ba3d2.png)

**Comment by rlaace423** [comment]
@micahriggan Could you suggest any idea?

**Comment by micahriggan** [comment]
Hi @rlaace423, that sounds like something isn't working correctly to me.

The logic for invalidating the transaction is here https://github.com/bitpay/bitcore/blob/b0bee2856d36280c47f27a9eff0fccdde2fdecf6/packages/bitcore-node/src/models/transaction.ts#L592

I do know that there are cases where the invalidation is multiple levels deep, like TX1 gets invalidated, but a TX spending it's outputs doesn't get removed from the mempool.

Currently theres a worker you could run, to try to clean up those instances
https://github.com/bitpay/bitcore/blob/master/packages/bitcore-node/src/services/pruning.ts
