### ISSUE TITLE
How to convert to WIF?

### ISSUE THREAD

**Issue by ekkis** [bitpay/bitcore#2658]
how would I convert the output of `code.toHDPrivateKey()` to a WIF?

**Comment by maektwain** [comment]
As provided in the document example 

```
To export and import a private key, you can do the following:

// encode into wallet export format
var exported = privateKey.toWIF();

// instantiate from the exported (and saved) private key
var imported = PrivateKey.fromWIF('L3T1s1TYP9oyhHpXgkyLoJFGniEgkv2Jhi138d7R2yJ9F4QdDU2m');
```

**Comment by maektwain** [comment]
As I researched I don't you think you can do this for the HDPrivate Keys. Since they work differently , maybe if your goal is to provide and export and import mechanism of wallets or PK, then use seeds to generate such HD keys and use keys to regenerate them .

**Comment by ekkis** [comment]
good enough.  thanks for researching it.  I'll call it no and close
