### ISSUE TITLE
How does bitcore handle transactions in orphan block situation?

### ISSUE THREAD

**Issue by sjlee1125** [bitpay/bitcore#2659]
I know orphan blocks can occur naturally when two miners produce blocks at similar times.
in bitcore-node, How does this handled?
for example, when orphan block occur in node, does bitcore change blockHeight in transactions table?

**Comment by micahriggan** [comment]
https://github.com/bitpay/bitcore/blob/ae536af87a135b7b7d749d517a369be67abebea6/packages/bitcore-node/src/models/block.ts#L141

When that happens the old block information is deleted, and the new block is processed.

**Comment by sjlee1125** [comment]
Thank you micahroggan!
