### ISSUE TITLE
After update, bitcore won't start

### ISSUE THREAD

**Issue by rlaace423** [bitpay/bitcore#2689]
Hi, I'm using bitcore for syncing Ethereum mainnet.

Today I updated my bitcore source.
* git tags before : prod-300-g6aa513017
* git tags after : prod-877-g02dbed753

 After updating & rebuilding, I started bitcore node again, but I won't syncing anymore.

But in mongo, It uses almost 100% of CPU resources and lots of OPs for updating transactions are found. 

In my thought, when starting bitcore with latest source, now It runs "pruneMempool" for transactions which were not performed before. But for ethereum mainnet, there's tons of transaction.. so it takes too much time to wait.

How can I skip this stage? 

![image](https://user-images.githubusercontent.com/5516480/72729361-598ff900-3bd2-11ea-95cf-484c5239b01f.png)

**Comment by micahriggan** [comment]
Hello, could you run bitcore-node in debug so we can see what it's stuck on?

`cd packages/bitcore-node && npm run debug`

**Comment by rlaace423** [comment]
@micahriggan Thank you for your answer. 

First, current bitcore status is behind about 25,000 blocks.

Here's debug messages you ask.
![image](https://user-images.githubusercontent.com/5516480/72776804-c6e56d80-3c56-11ea-94e9-b75ec37693c9.png)

With this messages, it adds transactions in mongo. But before source update, It just starts block syncing with messages below.
![image](https://user-images.githubusercontent.com/5516480/72777214-3d369f80-3c58-11ea-930c-1ce0e1980882.png)

Why these two have differences?

**Comment by rlaace423** [comment]
@micahriggan For your information,

In previous version, It starts syncing with such debug messages below.
![image](https://user-images.githubusercontent.com/5516480/72777476-1f1d6f00-3c59-11ea-9532-977d0a363605.png)

In the middle of messages, you can find Syncing log.
![image](https://user-images.githubusercontent.com/5516480/72777526-46743c00-3c59-11ea-915d-6d24892183bc.png)
