### ISSUE TITLE
husky error

### ISSUE THREAD

**Issue by ktnoc** [bitpay/bitcore#2725]
Hello, 

Tried to sync on a very slow node back on jan30, compile was straightforward, but cloning and installing today gives me this : 

    husky > Setting up git hooks
    ENOENT: no such file or directory, mkdir 'node_modules/husky/.git/hooks'
    husky > Failed to install

Seems husky was added recently on package.json. Any fix ?

**Comment by ktnoc** [comment]
seems reverting to 808f24c8a7bef606e34dc0e14bd516ce674cab95 makes it temporarily.

**Comment by micahriggan** [comment]
When you ls -al does it have a .git folder? Sounds like you may have downloaded a zip file

**Comment by ktnoc** [comment]
nope, direct git clone from master branch

**Comment by micahriggan** [comment]
Okay, hmm, husky is supposed to be installed as a Dev tool when you do npm install.

It sounds like there's no hooks folder when it tries to install, but I'm not sure why that should matter. Perhaps husky is not able to create that hooks folder for you

**Comment by ktnoc** [comment]
Yup, that's the issue here, from several other githubs, it seems the git version matters / installing manually solves it, but not the case here.

**Comment by micahriggan** [comment]
https://github.com/typicode/husky/issues/242#issuecomment-506267603

Seems like there is a git version dependency

**Comment by ktnoc** [comment]
Yes, they point at git v < 2.4, am on 2.7.4 here

**Comment by ktnoc** [comment]
2.4.0 seems fine, not 3.1.0 :)
