### ISSUE TITLE
ETH ropsten duplicate tx

### ISSUE THREAD

**Issue by rlaace423** [bitpay/bitcore#2726]
Hello, I'm using bitcore for building ethereum full node. 
And I found weird situation.

After Syncing up to latest blocks, some incoming pending transactions are stored twice.
At first, their blockHeight are -1, and after block confirmation, only first one's blockHeight changes and seconde one is still -1 forever.

And I found issues https://github.com/bitpay/bitcore/pull/2563.

Will it be fixed if I upgrade bitcore?
I'm using bircore which version is **prod-272-g9aeb809**.

Always, thank you @micahriggan  :)

**Comment by micahriggan** [comment]
Hi, I think we encountered that as well!
Let me see if I can find the commit

**Comment by micahriggan** [comment]
https://github.com/bitpay/bitcore/blob/77b7e73e67aedceda1ac38690fca7fbae905eb83/packages/bitcore-node/src/modules/ethereum/p2p.ts#L67

We used to do an async action, before caching, which could cause multiple calls of processTransaction if you receive it twice over the subscription

**Comment by rlaace423** [comment]
Upgrading to current latest branch works! Thank you.
