### ISSUE TITLE
[bitcore-lib question] How to sign transcation with multiple inputs?

### ISSUE THREAD

**Issue by elis-k** [bitpay/bitcore#2774]
I know this is not an issue but i think someone can help with this, just a small question.

Im trying to sign a transcation with multiple inputs, these inputs are all child addresses derived from the extended key.

So can i sign all the inputs using the extended private key, or do i have to sign each input using the correlating private key of each address?

Yeah im not really familiar with how bitcoin system works, still trying to learn though.

Here is my code in node.js, using bitcore-lib

```
var seed = bip39.mnemonicToSeedSync(mnemonic).toString('hex');
var root = bitcore.HDPrivateKey.fromSeed(seed, bitcore.Networks.mainnet);
var extended = root.derive("m/44'/0'/1'");  
var privateKey = extended.privateKey;

explore.getUnspentOutputs(extended.xpubkey,options.blockchain_explorer).then((data)=>{

      //This will return an unspent output from a derived address which is extended.derive("m/0/0");*
      var utxos = data.unspent_outputs.map(function(txo){
            return {
                  "txId": txo.tx_hash_big_endian,
                  "outputIndex" : txo.tx_index,
                  "script" : txo.script,
                  "satoshis" : txo.value

            }
      });
      //Trying to sign a transcation with extended private key where input is from a derived child
      //I get error some inputs aren't signed
      //But i think it works if i sign with the derived child privateKey 


      var tx = bitcore.Transaction()
                  .from(utxos)
                  .to(options.myAddress, 5000)
                  .change(options.changeAddress)
                  .fee(options.fee)
                  .sign(privateKey)
                  .serialize();

 });
```

**Comment by elis-k** [comment]
It was as i thought, input should be signed by correlating private key, extended private key wont work to sign all inputs. I managed to do it by using an array of privateKeys when signing.
You have done a great job with these libraries, a good documentation is missing though.

**Comment by jahvi** [comment]
@el1s7 do you still have any code examples on how you did this? Running into the same issue myself trying to sign inputs
