### ISSUE TITLE
Add support for OP_REVERSEBYTES to bitcore-lib-cash

### ISSUE THREAD

**Issue by rkalis** [bitpay/bitcore#2829]
In the May 2020 Bitcoin Cash hardfork the new `OP_REVERSEBYTES` opcode (188) was added (https://github.com/bitcoincashorg/bitcoincash.org/blob/master/spec/2020-05-15-op_reversebytes.md).

Could support for this opcode be added to the Script part of bitcore-lib-cash?

**Comment by micahriggan** [comment]
Thanks @rkalis I think we'd like to add that

**Comment by matiu** [comment]
PR are welcomed! Maybe @bitjson  :)

**Comment by rkalis** [comment]
I just opened PR #2831 for this. Let me know if it needs any changes.

**Comment by bitjson** [comment]
Nice work @rkalis! 🚀
