### ISSUE TITLE
Get Wallet UTXOS `includeSpent` args ignored

### ISSUE THREAD

**Issue by datgrog** [bitpay/bitcore#2919]
The api route call `streamWalletUtxos` which ignores args by overriding it to `{}`
https://github.com/bitpay/bitcore/blob/19a25106c9e4d8cb4a131684f02473ef36e5f7d8/packages/bitcore-node/src/providers/chain-state/internal/internal.ts#L434
So later when the execution goes in the `if` below there is no chance the condition to be evaluated to  `false`.
```
if (args.includeSpent !== 'true') {
    query.spentHeight = { $lt: SpentHeightIndicators.pending };
}
```
Is this intended ?

**Comment by micahriggan** [comment]
[I believe that syntax should only override args if it's undefined.](https://zaiste.net/posts/javascript-destructuring-assignment-default-values/)

If you're noticing a problem with using that, then maybe we're not passing args down from a higher level

**Comment by datgrog** [comment]
I'm sorry it's all good, thanks for this link!
