### ISSUE TITLE
Insight package: Cannot connect to local nodes on testnet

### ISSUE THREAD

**Issue by liorko87** [bitpay/bitcore#2944]
Hi,

I have a local blockchain network based on bitcoin that runs on my local machine.
I updated the `bitcore.config.json` file to support my nodes.

When I'm trying to see the blocks at the browser at `localhost:8200`, I'm receiving this error:
```
Error: connect ECONNREFUSED 127.0.0.1:3000
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
```

I'm starting the Insight client by: `npm run insight NETWORK=testnet`

**Comment by batlobsteroboepulsar** [comment]
were you able to solve this issue? i am currently running bitcoind as a separate daemon and would like to keep my configuration the same if possible as opposed to starting up a bitcore-node image as well, i just wanted to run insight alongside of it.

**Comment by liorko87** [comment]
Hey, I left this and will return to it in a short time.
In the current architecture, you cannot do it.
The bitcore-node acts as the server that receive the RPC result from the bitcoind server.
