### ISSUE TITLE
Document about npm run node

### ISSUE THREAD

**Issue by jackyxie** [bitpay/bitcore#2968]
As I'm not know much about js. Is there any document about how to configure some params before execute `npm run node`. Such specific other ip address of mongodb and so no?

**Comment by jackyxie** [comment]
set linux env DB_HOST solved it.

**Comment by micahriggan** [comment]
https://github.com/bitpay/bitcore/blob/73a2b8fff3ba6d92132ea78e0329d6ccd6575825/packages/bitcore-node/src/config.ts#L58

You can also provide that in the config file
