### ISSUE TITLE
Another node is the primary syncing node

### ISSUE THREAD

**Issue by jackyxie** [bitpay/bitcore#2973]
I stop and start `npm run node`, and get message like this:

```{"message":"Another node is the primary syncing node","level":"info"}```

What does it mean, and what to do next?

**Comment by defusevenue** [comment]
I'm also having the same issue. Is there any way to promote nodes?

**Comment by jackyxie** [comment]
> I'm also having the same issue. Is there any way to promote nodes?

@defusevenue Wait for several minutes, and it will be normal soon.

**Comment by defusevenue** [comment]
> 
> 
> > I'm also having the same issue. Is there any way to promote nodes?
> 
> @defusevenue Wait for several minutes, and it will be normal soon. It maybe some initial preparing work to be done before start syncing data.

Thanks for the reply. I did find another solution. After looking through the source code I found out it checks the `state` collection to see if there is an active sync. If you delete the document inside the collection and restart the node it'll work again. Seems like it happens if Bitcore isn't shutdown properly.

**Comment by jackyxie** [comment]
@defusevenue did you have a fast restore from this situation?

**Comment by gusbru** [comment]
To delete the document located inside the `state` collection, follow the steps:

1. First enter on the machine where the `Bitcore` was running.
1. Start the MongoDB CLI: `mongo --port 27017`
1. List the databases: `show dbs`
1. locate the `bitcore` db
1. `use bitcore`
1.`show collections`
1. locate `state` collection and check its content: `db.state.find()`
1. You should see one entry. Delete it: `db.state.deleteOne({_id: ObjectId('XXXXXXXXX')})`

Hope it helps

**Comment by martindale** [comment]
> To delete the document located inside the `state` collection, follow the steps:
> 
> 1. First enter on the machine where the `Bitcore` was running.
> 2. Start the MongoDB CLI: `mongo --port 27017`
> 3. List the databases: `show dbs`
> 4. locate the `bitcore` db
> 5. select db: `use bitcore`
> 6. display the collections: `show collections`
> 7. locate `state` collection and check its content: `db.state.find()`
> 8. You should see one entry. Delete it: `db.state.deleteOne({_id: ObjectId('XXXXXXXXX')})`
> 
> Hope it helps

Thanks, this worked for me!

**Comment by danielclough** [comment]
### A quick way to remove the `state` collection's `ObjectId` in case of a crash.

```bash
# Make ObjectId variable
STATE_OBJECT_ID=$(mongo --shell --eval "db=db.getSiblingDB('bitcore');db.state.find();" | grep ObjectId | cut -d "," -f 1 | cut -d '"' -f4)
# Delete ObjectId
mongo --shell --eval "db=db.getSiblingDB('bitcore');db.state.deleteOne({_id: ObjectId(\"${STATE_OBJECT_ID}\")})"
```
