### ISSUE TITLE
Who can share full node data of mongodb?

### ISSUE THREAD

**Issue by jackyxie** [bitpay/bitcore#2988]
As sync of bitcoin block data, it's very slow after block height about 180000. Is there anyone who can share the data which sync to mongodb ?

**Comment by alstjd0921** [comment]
```
Syncing... | Chain: BTC | Network: mainnet |    9.89 blocks/min | Height:  470243
Syncing... | Chain: BTC | Network: testnet |   35.24 blocks/min | Height: 1581321
```

If my computer can maintain this speed (but pace will get slower and slower), it will take 12+x days to get full sync db.
We need someone who can share synced data via torrent or some way.

**Comment by jackyxie** [comment]
Finally, it has finished. Take a long long time to sync data to mongodb.

**Comment by ssg502** [comment]
can you share the mongodb to me? i need it

**Comment by amirulmus** [comment]
up. can share to me too ?
