### ISSUE TITLE
security question: addr handling

### ISSUE THREAD

**Issue by amitiuttarwar** [bitpay/bitcore#3140]
Hi! I'm proposing some changes to `addr` handling in Bitcoin Core, and trying to ensure there will not be negative consequences for other clients on the network. For more information about the changes, please see my [mailing list post](https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2021-April/018784.html). The crux is that, if the changes are accepted, bitcoin core would stop sending `addr` messages to inbound peers who don't "indicate interest" aka initiate an addr-related message (addr, addrv2, getaddr, or sendaddrv2). 

**I'd like to ensure that bitcore clients will initiate an addr related message to outbound peers. I've looked in the code and its possible my proposed change to bitcoin core would cause issues for bitcore clients. Can someone help confirm my understanding?**

For this concern to be relevant, a fundamental question is: do bitcore nodes rely on decentralized address discovery (aka sending `addr` p2p messages) to identify nodes to connect to? If no, this concern is irrelevant. I found [this snippet](https://github.com/bitpay/bitcore/blob/0099da9bece2f15202341b20dde48b37485b976f/packages/bitcore-p2p/lib/pool.js#L325) of code which suggests to me that the node uses DNS seeds to get addresses. Is this the sole technique, or just the one for bootstrapping?

If decentralized address discovery is used, then the next question is: do bitcore nodes initiate any addr messages to outbound connections? 

Here are some relevant code snippets I have found 
1. A "todo" to self advertise when constructing a `version` message ([link](https://github.com/bitpay/bitcore/blob/0099da9bece2f15202341b20dde48b37485b976f/packages/bitcore-p2p/lib/peer.js#L205)) 
2. It looks like a function is defined to send a `getaddr` message [here](https://github.com/bitpay/bitcore/blob/0099da9bece2f15202341b20dde48b37485b976f/packages/bitcore-p2p/lib/messages/commands/getaddr.js#L14), but I'm unable to find where this is invoked. I'm very unfamiliar with javascript, so I might just be misunderstanding the code. 
3. I looked the code in `bitcore/packages/bitcore-p2p/lib/peer.js` and can't seem to find anywhere that 
would send an `addr` or `getaddr` message.

None of these components demonstrate to me exactly what the address expectations & behavior is. Since my ability to follow this code is minimal, I'd really appreciate some help identifying if this is a point of concern.  

Thanks in advance!
Amiti

**Comment by adamjonas** [comment]
Noting that I emailed @nitsujlangston (05-24), @kajoseph (05-27), and @gabrielbazan7 (05-28) asking for a response to this inquiry but haven't yet received a reply.

**Comment by micahriggan** [comment]
Bitcore node typically has a dedicated bitcoin node, or a group of them, and the addresses are passed in via config.

I don't believe this change will impact bitcore node

**Comment by amitiuttarwar** [comment]
@micahriggan awesome! thank you!
