### ISSUE TITLE
litecoin P2SH-P2WPKH address start with M not worked

### ISSUE THREAD

**Issue by cy92830** [bitpay/bitcore#3179]
For litecoin address (P2SH-P2WPKH), balance not work
MR5Hu9zXPX3o9QuYNJGft1VMpRP418QDfW
but address start with 3 works

**Comment by losh11** [comment]
Litecoin uses the M prefix for P2SH, decoding for the 3 prefix is not recommended to avoid confusion with bitcoin addresses.
