### ISSUE TITLE
Support SPV

### ISSUE THREAD

**Issue by ryanxcharles** [bitpay/bitcore#322]
Simplified Payment Verification (SPV) allows one to write light nodes.

**Comment by braydonf** [comment]
- Filter messages have been added to bitcore-p2p: https://github.com/bitpay/bitcore-p2p/blob/master/lib/messages/commands/filterload.js
- Filtered block types have been added: https://github.com/bitpay/bitcore/blob/master/lib/block/merkleblock.js

Should be possible to implement a lightweight client using these.
