### ISSUE TITLE
Error "pathspec '4.0' did not match any file(s) known to git."

### ISSUE THREAD

**Issue by gtshk** [bitpay/bitcore#3224]
Hi there,

I tried to install bitcore in Ubuntu 20.04, but it happened some issues.
Is it support the latest version of nodejs?
![test](https://user-images.githubusercontent.com/87638622/126582764-0886f390-2bee-4a49-a72e-4791d9c73f29.JPG)

**Comment by sandrocsimas** [comment]
Hi @gtshk, how did you solved this problem? The same happens here.

**Comment by JasonCoombs** [comment]
`npm install gulp`

That's it. problem solved on Mac OS.
