### ISSUE TITLE
bitcore-lib-cash does not appear compatible with react-native

### ISSUE THREAD

**Issue by hyetigran** [bitpay/bitcore#3241]
I'm attempting to use the bitcore-lib-cash package in my expo managed react-native ios app. Using yarn as the package manager.

When I go to start my app with 'expo start', I'm getting the following error:

```
Unable to resolve module crypto from /Users/.../node_modules/bitcore-lib-cash/lib/crypto/hash.js: crypto could not be found within the project.

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
  1 | 'use strict';
  2 |
> 3 | var crypto = require('crypto');
    |                       ^
  4 | var BufferUtil = require('../util/buffer');
  5 | var $ = require('../util/preconditions');
  6 |
```

**Comment by hyetigran** [comment]
This error is due to react-native packager not using the Node runtime environment and therefore missing certain standard libraries such as 'crypto', 'buffer', etc.

To get around this issue I used the ['rn-nodeify'](https://www.npmjs.com/package/rn-nodeify) solution and wrote about it [here](https://dev.to/hyetigran/unable-to-resolve-module-crypto-1gek).

**Comment by larcho** [comment]
Would making a port of this to React Native make sense? Would be nice to have a natively compatible version that supports React Native out of the box.
