### ISSUE TITLE
Make bitcore full node

### ISSUE THREAD

**Issue by ryanxcharles** [bitpay/bitcore#325]
Making a full node with bitcore would have many uses, most especially for testing purposes (see https://github.com/bitpay/bitcore/issues/255 ), and also eventually would strengthen the overall bitcoin community by (eventually, once we were confident it were 100% protocol-equivalent with bitcoin core) providing an alternative to bitcoin core.

**Comment by braydonf** [comment]
A beta has been released with a full node leveraging Bitcoin Core: https://github.com/bitpay/bitcore-node/releases/tag/v0.2.0-beta.1
