### ISSUE TITLE
Modularize bitcore

### ISSUE THREAD

**Issue by ryanxcharles** [bitpay/bitcore#326]
Bitcore is monolithic and inappropriately large for many applications. Although it is possible to use bitcore in small pieces (by compiling only desired components for the browser, or lazy loading modules in node), it would be more compatible with the npm ecosystem to use distinct modules for each component.

These modules might be:

* bitcore-buffer (buffer library equal to Buffer in node but with pure js versions for the browser)
* bitcore-bignum (bignum library with pure js and openssl versions)
* bitcore-point (elliptic curve crypto with pure js and openssl versions)
* bitcore-curve (secp256k1 curve params)
* bitcore-hash (hash functions with pure js and openssl versions)
* bitcore-key (private/public keys, signing, encryption)
* bitcore-address (addresses, private key import format, base58)
* bitcore-tx (Transaction + TransactionBuilder)
* bitcore-wallet (collections of private keys - maybe include copay multisig wallet logic?)
* bitcore-sin (SINs)
* bitcore-peer (network connections - node-only)
* bitcore-script (and script interpreter)
* bitcore-bip32
* bitcore-electrum
* bitcore-armory

...and then of course "bitcore" would include all of these in one monolithlic library (where you would still have the ability using browserify to compile only the pieces you want).

Besides making it easier to use the individual components of bitcore, this would also make it easier to make updates to individual bitcore components without having to release a whole new bitcore. It was mentioned by @martindale ( https://github.com/bitpay/bitcore/issues/255 ) that express recently did this ( https://github.com/visionmedia/express/wiki/Migrating-from-3.x-to-4.x ).

**Comment by yemel** [comment]
I agree with @eordano @braydonf on `bitcore-uri` and `bitcore-hdkeys` being included on this repo. Both seems kind of core of most bitcoin apps, in any case we should be coherent and include/extract both of them.

I don't see the need for `bitcore-hdpm` (bip45).
I believe `bitcore-identity` and `bitcore-bitauth` are different things. @martindale have some comment's about this.

I'm thinking that maybe the `README.md` of each submodule should have the documentation of the module. Or should we have a base template for README and link to `/docs/XXX` with the files to build `bitcore.io/guide`?

**Comment by maraoz** [comment]
@braydonf @eordano I think `bitcore-uri` and `bitcore-hdkeys` should go in separate repos. Rationale:
- Both are BIPs. I like the idea of having only the core in `bitcore`, and moving BIPs to submodules
- They are independent files, no other classes use them (try `git grep HDPrivateKey` and such)
- We wouldn't add any big complexity in separating it (`require('bitcore').URI` vs `require('bitcore-uri')`), and we'll gain the well-known benefits of modularization.

@yemel: on BIP45, I was thinking moving https://github.com/bitpay/copay/blob/master/js/models/HDPath.js to a bitcore submodule. It'd help other developers adopt the BIP.

**Comment by braydonf** [comment]
Rationale for BIPS as submodules may not work, for example BIP21, BIP72 and BIP73 all belong together as they are dealing with URI, and think it should be organized by features instead.

**Comment by braydonf** [comment]
The biggest rationale I can see for modularization is that I think that this is more established pattern:
```javascript
var PaymentProtocol = require('bitcore-paymentprotocol')`
```
Than doing the following:
```javascript
var PaymentProtocol = require('bitcore/lib/paymentprotocol');
``` 
However I think that the monolithic approach has some advantages as testing all of the code, and interoperability is more efficient. Perhaps we could have a repository that would run tests for all Bitcore modules, we probably should anyways.

**Comment by maraoz** [comment]
I see... I hadn't thought of automatic testing of all submodules. That may be a big problem...

**Comment by braydonf** [comment]
As for documentation we should be able to group the modules together and copy the docs and generate the api reference for each. Here is how they can be organized together:
https://gist.github.com/braydonf/85ee1339b4b047b84613
