### ISSUE TITLE
regtest network problem 

### ISSUE THREAD

**Issue by Johnsavadkuhi** [bitpay/bitcore#3277]
can't create privatekey on regtest network  
please provide a good way please 

i have a problem like this : 

i have created a regtest nework on my computer then  i get a privatekey like this : 
privkey : cTCA2cCtBhSBjYv2T47Cria1xGByPVVi8rfe7jZp235zTruxEXxm 
and that address : 
bcrt1qasdf6jqmxav2ljum56gxy00j8we2uxyrzd2fdc

i want to create that regtest address with bitcore-lib  but it couldn't make the same address  

please let me know what is the problem

**Comment by kajoseph** [comment]
```
const bitcoreLib = require('bitcore-lib'); // This can be imported a number of ways as well, e.g. through crypto-wallet-core

const privKey = bitcoreLib.PrivateKey.fromString('cTCA2cCtBhSBjYv2T47Cria1xGByPVVi8rfe7jZp235zTruxEXxm');
const address = privKey.publicKey.toAddress('regtest', 'witnesspubkeyhash');

console.log(address.toString());
```

Just make sure you don't use that private key on mainnet. :)
