### ISSUE TITLE
Installed BitcoinCore and no BTC in wallet after a week

### ISSUE THREAD

**Issue by scottreg** [bitpay/bitcore#3323]
Hi Everyone,
I have tried to find an answer to this but no luck so far so I'm asking here.

I installed Bitcoin Core a week ago and it's running smoothly as far as I can tell. Mostly out of the box settings. Currently, 18 inbound connections and 10 outbound. The number of transactions appear to be increasing nicely too. Bitcoin Core has been running for around a week now but no BTC have yet to be deposited into the Bitcoin Core wallet that I created. I figured running it for a week would be plenty of time to see some BTC rewards.

Could someone point me to the article(s) that explains how to fix it or just tell me what this noob did wrong?
Many thanks!

**Comment by bplunkert** [comment]
It looks like this question is about [Bitcoin Core](https://github.com/bitcoin/bitcoin). This repo is bitcore, not Bitcoin Core.
