### ISSUE TITLE
OpenEthereum is deprecated, we need Geth support

### ISSUE THREAD

**Issue by tonik-ru** [bitpay/bitcore#3385]
OpenEthereum is deprecated, they even didn't release Gray Glacier upgrade. BitPay faced this issue yesterday also.
right now we can't use Geth, because of a missing trace_block method, its mandatory for seeing "internal" transactions.
so what are your plans for this?

**Comment by kajoseph** [comment]
We are currently working on adding Geth support and optimizing sync times, both for ETH and for Polygon
