### ISSUE TITLE
Handle BIP32 edge cases correctly

### ISSUE THREAD

**Issue by ryanxcharles** [bitpay/bitcore#341]
See related PR in bitcoinjs-lib: https://github.com/bitcoinjs/bitcoinjs-lib/pull/174

**Comment by eordano** [comment]
https://github.com/oleganza/CoreBitcoin/issues/16#issuecomment-49606369

**Comment by braydonf** [comment]
@ryanxcharles @eordano Is this still relevant?

**Comment by braydonf** [comment]
Closing this, as I think these issues cover the case: 
- https://github.com/bitpay/bitcore-lib/issues/94
- https://github.com/bitpay/bitcore-lib/issues/93
