### ISSUE TITLE
Merge. Which client do you recommend? Erigon? Geth?

### ISSUE THREAD

**Issue by tonik-ru** [bitpay/bitcore#3428]
Tomorrow merge will happen. which client should we use?
Erigon is on alpha stage. Is it stable for production?
Geth support is not implemented yet.
so what do you recommend? what are you using in BitPay?

**Comment by kajoseph** [comment]
I would recommend using Geth with this PR that adds support for Geth traces:
 https://github.com/bitpay/bitcore/pull/3407

Geth will still run with Bitcore without the PR, but the traces won't be saved to the db.

**Comment by tonik-ru** [comment]
i see, thank you.
1. this pr was not merged, why? it brings new issues? is it stable enough for production?
2. what do you use internally in BitPay?

**Comment by kajoseph** [comment]
1. It has now been merged. We've tested it pretty extensively.
2. Geth
