### ISSUE TITLE
Insight does not correctly present transaction b10c007c…792b4d41

### ISSUE THREAD

**Issue by Xekyo** [bitpay/bitcore#3430]
The first transaction that used P2TR outputs (notably before activation of the soft fork), [b10c007c60e14f9d087e0291d4d0c7869697c6681d979c6639dbd960792b4d41](https://bitpay.com/insight/BTC/mainnet/tx/b10c007c60e14f9d087e0291d4d0c7869697c6681d979c6639dbd960792b4d41) is shown to have one input and two outputs, although it actually has four inputs:

![image](https://user-images.githubusercontent.com/4060799/190226649-e00405be-a5f7-4c64-abd8-901f67376568.png)

For reference, [mempool.space](https://mempool.space/tx/b10c007c60e14f9d087e0291d4d0c7869697c6681d979c6639dbd960792b4d41) shows:
![image](https://user-images.githubusercontent.com/4060799/190226876-e0bb582c-7cc1-4bed-80e2-1cad3bcd1c6c.png)

It does look like bech32m addresses and P2TR outputs are correctly indexed starting from activation, as other transactions I've tested (e.g. [3777…35c8](https://bitpay.com/insight/BTC/mainnet/tx/37777defed8717c581b4c0509329550e344bdc14ac38f71fc050096887e535c8) look correct to me.

**Comment by kajoseph** [comment]
Thanks for bringing this to our attention! We will look into this

**Comment by kajoseph** [comment]
@Xekyo This fix has been merged and deployed.

![image](https://user-images.githubusercontent.com/32603939/193641687-7792990b-d4d5-4858-a534-9a95cd35211d.png)

**Comment by Xekyo** [comment]
Hi @kajoseph, I was just looking at the transaction again. It's good that the addresses are now shown, but I notice that the last three inputs are compounded into one line, and other than I expected, even when expanding the details, the three inputs still are shown as one. While the latter three inputs all spend funds associated with the same address, this causes e.g. the arrow in the front to only link to the details of [input 1](https://bitpay.com/insight/BTC/mainnet/tx/b48a59fa9e036e997ba733904f631b1a64f5274be646698e49fd542141ca9404?detailsIdx=1&fromVout=false). 
![image](https://user-images.githubusercontent.com/4060799/193670464-b7cf8327-8f4f-4c89-bef0-8132bd87ef60.png)

I was wondering whether that is intentional, or whether the detailed view should reveal that there were four inputs even when some of them spend funds associated with the same address:
![image](https://user-images.githubusercontent.com/4060799/193671157-b1e8bfb9-5d98-4322-9eda-2eea93e8663f.png)

**Comment by kajoseph** [comment]
@Xekyo The inputs have been unrolled. We also fixed the input confirmations, added some tx metadata, and removed the script field since it wasn't being populated anyway (I'd like to add it back in in a future iteration)

**Comment by Xekyo** [comment]
Thanks looking good.
