### ISSUE TITLE
Bug: Following link to output in child transaction marks output instead of input as selected

### ISSUE THREAD

**Issue by Xekyo** [bitpay/bitcore#3468]
Problem:
In the transaction overview, when clicking the link on an output to the child transaction, the “Selected” pill appears on an output of the child transaction rather than the spent input we came from.

Expected outcome:
When clicking on an output, the corresponding **input** in the child transaction should be marked as “Selected”.

Instruction to replicate:
![image](https://user-images.githubusercontent.com/4060799/198059197-5a5e42ae-1587-44fa-a4fb-3db619851e61.png)
![image](https://user-images.githubusercontent.com/4060799/198059870-9f56d9a8-940f-43df-9132-5e88d99f594c.png)

Transaction used in example: [d3a0f72349b…e08e6465e90e](https://bitpay.com/insight/BTC/mainnet/tx/d3a0f72349b127e80d025b4afc987bcd0bc3d37824b07fa8d552e08e6465e90e?detailsIdx=0&fromVout=false)

**Comment by kajoseph** [comment]
This has finally been deployed
