### ISSUE TITLE
Implement bitcore-stealth module

### ISSUE THREAD

**Issue by ryanxcharles** [bitpay/bitcore#353]
* Peter Todd on the mailing list http://sourceforge.net/p/bitcoin/mailman/message/31813471/
* Entire thread http://sourceforge.net/p/bitcoin/mailman/bitcoin-development/thread/20140106120338.GA14918%40savin/#msg31813471
* ByteCoin https://bitcointalk.org/index.php?topic=5965.0
* Gregory Maxwell http://snowdenandthefuture.info/PartIII.html
* Peter Todd http://www.mail-archive.com/bitcoin-development@.../msg03612.html
* Bitcoin Wiki https://en.bitcoin.it/w/index.php?title=Maximum_transaction_rate&oldid=36983B
* Jeff Garzik https://github.com/bitcoin/bitcoin/pull/1809

**Comment by braydonf** [comment]
Has been implemented, however may still need work:
- https://github.com/bitpay/bitcore-stealth

As well as:
- https://github.com/ryanxcharles/fullnode
