### ISSUE TITLE
qustion

### ISSUE THREAD

**Issue by mraksoll4** [bitpay/bitcore#3546]
What commit is working ? and at what version of node ?
I try latest from master with node 18 , and it not work.

**Comment by mraksoll4** [comment]
i was try fresh install at latest nodejs 18 , there many deprecated warnings , and error when try run insight, broken charts if try fix that, it give blank white page.

OS ubuntu.

**Comment by kajoseph** [comment]
The connection string to point to your node is in [constants.ts](https://github.com/bitpay/bitcore/blob/master/packages/insight/src/utilities/constants.ts#L2)

As far as the errors, I was just able to pull down a clean bitcore with node v18.14.2, npm v9.5.0, run `npm i` and `npm run build` without any issue.

**Comment by mraksoll4** [comment]
try run insight from freash install.

**Comment by kajoseph** [comment]
Yes, I did it with a fresh install. It worked fine for me

**Comment by mraksoll4** [comment]
the it strage why it was lose react ^18 depend :/

**Comment by mraksoll4** [comment]
how to run bitcore node at full debug level see why it disconect from peer ?
