### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'fromWIF')

### ISSUE THREAD

**Issue by ProximaCA** [bitpay/bitcore#3678]
my code
import bitcoin from 'bitcoinjs-lib';

const TESTNET = bitcoin.networks.testnet;
const privateKeyWIF = '...';

const keyPair = bitcoin.ECPair.fromWIF(privateKeyWIF, TESTNET);

**Comment by kajoseph** [comment]
It appears you're using a different project. `bitcoinjs-lib` != 'bitcore-lib`
