### ISSUE TITLE
check that Transaction doesn't generate outputs < dust threshold

### ISSUE THREAD

**Issue by madshell** [bitpay/bitcore#371]
TransactionBuilder let you generate transactions which are rejected when being sent with bitcoind. Error is: **TX rejected (code -22)** 

This happens when remainderOut value is tiny like "0.00001800" (~ $0.01). **I think TransactionBuilder should throw an exception like when unspent coins are insufficient.**

Meanwhile, I will personally share this 0.00001800 BTC dust between other outputs but this implies to calculate the minimum out value allowed. This topic explains how to do that and I think it could be great to include it in Bitcore : http://bitcoin.stackexchange.com/questions/14244/why-is-a-transaction-with-outputs-of-less-than-0-00005460-rejected

**Comment by eordano** [comment]
Closed by https://github.com/bitpay/bitcore/pull/916
