### ISSUE TITLE
Error when run packages/insight/: npm run start

### ISSUE THREAD

**Issue by Sotatek-MinhNguyen11** [bitpay/bitcore#3723]
![Screenshot from 2024-04-15 16-39-47](https://github.com/bitpay/bitcore/assets/146687333/c0aeae15-6f47-449e-9cc1-68eff007940a)
Help me to solve it!

**Comment by kajoseph** [comment]
Seems like your npm modules are not installed correctly. Insight is the only submodule that requires you to run `npm install` from the submodule (insight) directory instead of at the top level.
