### ISSUE TITLE
npm run node error

### ISSUE THREAD

**Issue by arianDGI** [bitpay/bitcore#3741]
**error when running npm run node for bitcore-node (ws protocol):**

info :: 2024-05-26T07:51:19.953Z :: 2024-05-26 09:51:19.953 GMT+2 | Connected to peer: 127.0.0.1:18332 | Chain: BTC | Network: testnet

/bitcore/packages/bitcore-node/node_modules/bitcore-lib/lib/encoding/bufferwriter.js:31
  assert(bufferUtil.isBuffer(buf));
  ^
AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert(bufferUtil.isBuffer(buf))
  
   at BufferWriter.write (/home/user/Projects/bitcore/packages/bitcore-node/node_modules/bitcore-lib/lib/encoding/bufferwriter.js:31:3)
    at VersionMessage.Message.toBuffer.Message.serialize (/home/user/Projects/bitcore/packages/bitcore-node/node_modules/bitcore-p2p/lib/messages/message.js:34:6)
    at Peer.sendMessage (/home/user/Projects/bitcore/packages/bitcore-node/node_modules/bitcore-p2p/lib/peer.js:201:29)
    at Peer._sendVersion (/home/user/Projects/bitcore/packages/bitcore-node/node_modules/bitcore-p2p/lib/peer.js:211:8)
    at Socket.<anonymous> (/home/user/Projects/bitcore/packages/bitcore-node/node_modules/bitcore-p2p/lib/peer.js:149:10)
    at Socket.emit (node:events:531:35)
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1591:10)

**Comment by gitzhou** [comment]
same here

```
# npm run node

> node
> cd packages/bitcore-node && npm start


> bitcore-node@10.0.39 start
> npm run tsc && node build/src/server.js


> bitcore-node@10.0.39 tsc
> npm run clean && tsc


> bitcore-node@10.0.39 clean
> rm -rf build

(node:1295752) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
(Use `node --trace-deprecation ...` to show where the warning was created)
info :: 2024-06-10T14:44:31.950Z :: Starting Event Service
info :: 2024-06-10T14:44:31.956Z :: Starting P2P Manager
info :: 2024-06-10T14:44:31.957Z :: Starting BTC p2p worker
(node:1295752) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
info :: 2024-06-10T14:44:32.023Z :: 2024-06-10 14:44:32.220 UTC | Connected to peer: 127.0.0.1:18333 | Chain: BTC | Network: testnet

/root/bitcore/packages/bitcore-lib/lib/encoding/bufferwriter.js:31
  assert(bufferUtil.isBuffer(buf));
  ^
AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert(bufferUtil.isBuffer(buf))

    at BufferWriter.write (/root/bitcore/packages/bitcore-lib/lib/encoding/bufferwriter.js:31:3)
    at VersionMessage.Message.toBuffer.Message.serialize (/root/bitcore/packages/bitcore-p2p/lib/messages/message.js:34:6)
    at Peer.sendMessage (/root/bitcore/packages/bitcore-p2p/lib/peer.js:201:29)
    at Peer._sendVersion (/root/bitcore/packages/bitcore-p2p/lib/peer.js:211:8)
    at Socket.<anonymous> (/root/bitcore/packages/bitcore-p2p/lib/peer.js:149:10)
    at Socket.emit (node:events:529:35)
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1540:10)
root@ubuntu-s-4vcpu-8gb-sgp1-01-testnet:~/bitcore# Error: write EPIPE
    at process.target._send (node:internal/child_process:872:20)
    at process.target.send (node:internal/child_process:745:19)
    at sendHelper (node:internal/cluster/utils:28:15)
    at send (node:internal/cluster/child:249:10)
    at EventEmitter.cluster._setupWorker (node:internal/cluster/child:54:3)
    at initializeClusterIPC (node:internal/process/pre_execution:526:13)
    at prepareExecution (node:internal/process/pre_execution:103:5)
    at prepareMainThreadExecution (node:internal/process/pre_execution:40:10)
    at node:internal/main/run_main_module:11:19
Error: write EPIPE
    at process.target._send (node:internal/child_process:872:20)
    at process.target.send (node:internal/child_process:745:19)
    at sendHelper (node:internal/cluster/utils:28:15)
    at send (node:internal/cluster/child:249:10)
    at EventEmitter.cluster._setupWorker (node:internal/cluster/child:54:3)
    at initializeClusterIPC (node:internal/process/pre_execution:526:13)
    at prepareExecution (node:internal/process/pre_execution:103:5)
    at prepareMainThreadExecution (node:internal/process/pre_execution:40:10)
    at node:internal/main/run_main_module:11:19
```

**Comment by arianDGI** [comment]
> same here when running bitcoin testnet3
> 
> ```
> # npm run node
> 
> > node
> > cd packages/bitcore-node && npm start
> 
> 
> > bitcore-node@10.0.39 start
> > npm run tsc && node build/src/server.js
> 
> 
> > bitcore-node@10.0.39 tsc
> > npm run clean && tsc
> 
> 
> > bitcore-node@10.0.39 clean
> > rm -rf build
> 
> (node:1295752) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
> (Use `node --trace-deprecation ...` to show where the warning was created)
> info :: 2024-06-10T14:44:31.950Z :: Starting Event Service
> info :: 2024-06-10T14:44:31.956Z :: Starting P2P Manager
> info :: 2024-06-10T14:44:31.957Z :: Starting BTC p2p worker
> (node:1295752) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
> info :: 2024-06-10T14:44:32.023Z :: 2024-06-10 14:44:32.220 UTC | Connected to peer: 127.0.0.1:18333 | Chain: BTC | Network: testnet
> 
> /root/bitcore/packages/bitcore-lib/lib/encoding/bufferwriter.js:31
>   assert(bufferUtil.isBuffer(buf));
>   ^
> AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
> 
>   assert(bufferUtil.isBuffer(buf))
> 
>     at BufferWriter.write (/root/bitcore/packages/bitcore-lib/lib/encoding/bufferwriter.js:31:3)
>     at VersionMessage.Message.toBuffer.Message.serialize (/root/bitcore/packages/bitcore-p2p/lib/messages/message.js:34:6)
>     at Peer.sendMessage (/root/bitcore/packages/bitcore-p2p/lib/peer.js:201:29)
>     at Peer._sendVersion (/root/bitcore/packages/bitcore-p2p/lib/peer.js:211:8)
>     at Socket.<anonymous> (/root/bitcore/packages/bitcore-p2p/lib/peer.js:149:10)
>     at Socket.emit (node:events:529:35)
>     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1540:10)
> root@ubuntu-s-4vcpu-8gb-sgp1-01-testnet:~/bitcore# Error: write EPIPE
>     at process.target._send (node:internal/child_process:872:20)
>     at process.target.send (node:internal/child_process:745:19)
>     at sendHelper (node:internal/cluster/utils:28:15)
>     at send (node:internal/cluster/child:249:10)
>     at EventEmitter.cluster._setupWorker (node:internal/cluster/child:54:3)
>     at initializeClusterIPC (node:internal/process/pre_execution:526:13)
>     at prepareExecution (node:internal/process/pre_execution:103:5)
>     at prepareMainThreadExecution (node:internal/process/pre_execution:40:10)
>     at node:internal/main/run_main_module:11:19
> Error: write EPIPE
>     at process.target._send (node:internal/child_process:872:20)
>     at process.target.send (node:internal/child_process:745:19)
>     at sendHelper (node:internal/cluster/utils:28:15)
>     at send (node:internal/cluster/child:249:10)
>     at EventEmitter.cluster._setupWorker (node:internal/cluster/child:54:3)
>     at initializeClusterIPC (node:internal/process/pre_execution:526:13)
>     at prepareExecution (node:internal/process/pre_execution:103:5)
>     at prepareMainThreadExecution (node:internal/process/pre_execution:40:10)
>     at node:internal/main/run_main_module:11:19
> ```

interesting, do you get it on regtest? i am still trying to find a fix

**Comment by gitzhou** [comment]
> > same here when running bitcoin testnet3
> > ```
> > # npm run node
> > 
> > > node
> > > cd packages/bitcore-node && npm start
> > 
> > 
> > > bitcore-node@10.0.39 start
> > > npm run tsc && node build/src/server.js
> > 
> > 
> > > bitcore-node@10.0.39 tsc
> > > npm run clean && tsc
> > 
> > 
> > > bitcore-node@10.0.39 clean
> > > rm -rf build
> > 
> > (node:1295752) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
> > (Use `node --trace-deprecation ...` to show where the warning was created)
> > info :: 2024-06-10T14:44:31.950Z :: Starting Event Service
> > info :: 2024-06-10T14:44:31.956Z :: Starting P2P Manager
> > info :: 2024-06-10T14:44:31.957Z :: Starting BTC p2p worker
> > (node:1295752) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
> > info :: 2024-06-10T14:44:32.023Z :: 2024-06-10 14:44:32.220 UTC | Connected to peer: 127.0.0.1:18333 | Chain: BTC | Network: testnet
> > 
> > /root/bitcore/packages/bitcore-lib/lib/encoding/bufferwriter.js:31
> >   assert(bufferUtil.isBuffer(buf));
> >   ^
> > AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
> > 
> >   assert(bufferUtil.isBuffer(buf))
> > 
> >     at BufferWriter.write (/root/bitcore/packages/bitcore-lib/lib/encoding/bufferwriter.js:31:3)
> >     at VersionMessage.Message.toBuffer.Message.serialize (/root/bitcore/packages/bitcore-p2p/lib/messages/message.js:34:6)
> >     at Peer.sendMessage (/root/bitcore/packages/bitcore-p2p/lib/peer.js:201:29)
> >     at Peer._sendVersion (/root/bitcore/packages/bitcore-p2p/lib/peer.js:211:8)
> >     at Socket.<anonymous> (/root/bitcore/packages/bitcore-p2p/lib/peer.js:149:10)
> >     at Socket.emit (node:events:529:35)
> >     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1540:10)
> > root@ubuntu-s-4vcpu-8gb-sgp1-01-testnet:~/bitcore# Error: write EPIPE
> >     at process.target._send (node:internal/child_process:872:20)
> >     at process.target.send (node:internal/child_process:745:19)
> >     at sendHelper (node:internal/cluster/utils:28:15)
> >     at send (node:internal/cluster/child:249:10)
> >     at EventEmitter.cluster._setupWorker (node:internal/cluster/child:54:3)
> >     at initializeClusterIPC (node:internal/process/pre_execution:526:13)
> >     at prepareExecution (node:internal/process/pre_execution:103:5)
> >     at prepareMainThreadExecution (node:internal/process/pre_execution:40:10)
> >     at node:internal/main/run_main_module:11:19
> > Error: write EPIPE
> >     at process.target._send (node:internal/child_process:872:20)
> >     at process.target.send (node:internal/child_process:745:19)
> >     at sendHelper (node:internal/cluster/utils:28:15)
> >     at send (node:internal/cluster/child:249:10)
> >     at EventEmitter.cluster._setupWorker (node:internal/cluster/child:54:3)
> >     at initializeClusterIPC (node:internal/process/pre_execution:526:13)
> >     at prepareExecution (node:internal/process/pre_execution:103:5)
> >     at prepareMainThreadExecution (node:internal/process/pre_execution:40:10)
> >     at node:internal/main/run_main_module:11:19
> > ```
> 
> interesting, do you get it on regtest? i am still trying to find a fix

Not yet, but I tried it on bitcoin signet, and it works well.

**Comment by arianDGI** [comment]
@gitzhou 

i found the fix, it's related to the new update where they added alias mapping for networks and stuff. so you define it like this in bitcore.config.json: 
![image](https://github.com/bitpay/bitcore/assets/62656398/256f8659-d417-4ec5-a4ab-666dc89032d2)

and then you specify it as "testnet3" instead of just "testnet" like older versions (in that same config file)

**Comment by gitzhou** [comment]
Hi @arianDGI, much appreciated! It works well now with the following config

![CleanShot-20240612005851](https://github.com/bitpay/bitcore/assets/1585505/3deb70d3-e0e6-480f-92c1-131e6e038068)

**Comment by gitzhou** [comment]
Hi @arianDGI , when specifying "testnet3" instead of just "testnet", what's the API endpoint address you're using?

visiting either `/api/BTC/testnet/block/tip` or `/api/BTC/testnet3/block/tip` it both responses errors `This node is not configured for the network testnet on chain BTC`
