### ISSUE TITLE
Security contact unresponsive

### ISSUE THREAD

**Issue by ChALkeR** [bitpay/bitcore#3825]
Hey

There is an issue in `bitcore-lib` (and the other `bitcore-lib-*` packages in this repo)

I sent an email about this lib to your security contact listed in https://github.com/bitpay/bitcore/tree/master/packages/bitcore-lib#security 11 days ago and received no response (I tried pinging it again, to no avail)

It seems like you redirect security reports there to generic support zendesk:
<img width="322" alt="image" src="https://github.com/user-attachments/assets/9c497fd4-a297-4063-896d-1b17f43fd6cc">
<img width="543" alt="image" src="https://github.com/user-attachments/assets/ded0f31c-50cc-4f9a-9f4c-f9bd4f9f10f1">

Trying other means to privately contact you also failed

Can you enable security reports here so I can share the vulnerability details in a non-public way?

GitHub doc how to do that: https://docs.github.com/en/code-security/security-advisories/working-with-repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository#enabling-or-disabling-private-vulnerability-reporting-for-a-repository

**Comment by nitsujlangston** [comment]
Private vulnerability reporting has been enabled

**Comment by ChALkeR** [comment]
@nitsujlangston Great, thanks!

Filed two reports
