### ISSUE TITLE
bundle.js does not define Buffer

### ISSUE THREAD

**Issue by adnia** [bitpay/bitcore#540]
Hello,

I have absolutely no experience with node.js, but I stumbled upon your browser bundle. I tried to adapt the ECIES example such that it hopefully worked in the browser (this is what I need for my application).

The code is given at the end of the post.
Firebug complains that Buffer is not defined, as it seems to be a node.js construct.

However, I could not simply use a string instead as I either get "INVALID: pkcs#5 padding only works for multiples of a byte", or, when I change the string length, get only garbled decrypted output.

Is there a quick way to fix this? Are there other known pitfalls regarding the browser bundle?

Kind regards,
adnia

_Edit:_ I used https://github.com/bitpay/bitcore/blob/master/browser/bundle.js as bitcore.js

```
<html>
    <head>
        <script src="bitcore.js"></script>
        <script type="text/javascript">
            var run = function() {
                bitcore = typeof(bitcore) === 'undefined' ? require('bitcore') : bitcore;
                console.log('ECIES: Elliptic Curve Integrated Encryption Scheme');
                console.log('A way of encrypting with a public key and decrypting with a private key.');
                var key = bitcore.Key.generateSync();
                console.log('Private key: ' + key.private.toString('hex'));
                console.log('Public key: ' + key.public.toString('hex'));
        /* Crash happens here */
                var message = new Buffer('This is a message to be encrypt');
                console.log('Message: "' + message.toString() + '"');
                var encrypted = bitcore.ECIES.encrypt(key.public, message);
                console.log('Encrypted (with public key): ' + encrypted.toString('hex'));
                var decrypted = bitcore.ECIES.decrypt(key.private, encrypted);
                console.log('Decrypted (with private key): "' + decrypted.toString() + '"');
            };
            // This is just for browser & mocha compatibility
            if (typeof module !== 'undefined') {
                module.exports.run = run;
                if (require.main === module) {
                    run();
                }
            } else {
                run();
            }
        </script>
    </head>
</html>
```

**Comment by gkucmierz** [comment]
@maraoz regarding your commit.
Is there a Buffer constructor in "bitcore-lib" or do I need to depend on "bitcore" library?
Your example is decrypting message directly from encrypted Buffer and I am trying do decrypt message from base64 encoded string.
I am using base64-js lib and it is returning to me new Uint8Array which is not compatible with your library.
How can I deal with that?

**Comment by gkucmierz** [comment]
Ok for the time being I am taking this constructor from your encrypt method, after empty string encryption.
```js
  const Buffer = ECIES().privateKey(privkey).publicKey(pubkey).encrypt('').constructor;
```
And then I am wraping my buffer using yours and it looks like it is working.
```js
new Buffer(myBuffer)
```

But please let me know what is the right solution in this case.

**Comment by stevedekorte** [comment]
I'm running into the same problem as gkucmierz. Is there a non hack (.constructor) solution?

**Comment by dabura667** [comment]
Buffer has an encoding arg and supports base64.

var buffObj = new Buffer(base64String, "base64")

This works

**Comment by dabura667** [comment]
http://stackoverflow.com/questions/14573001/nodejs-how-to-decode-base64-encoded-string-back-to-binary

Actually it depends on your NodeJS version used when browserifying.

Buffer.from(b64String, "base64") is for >=6.0.0
