### ISSUE TITLE
implemenent BIP38 wallet encryption with passphrase

### ISSUE THREAD

**Issue by maraoz** [bitpay/bitcore#605]

**Comment by bilthon** [comment]
Any news about this feature?

**Comment by maraoz** [comment]
No plans to implement it soon. Maybe you could adapt https://github.com/bitcoinjs/bip38 code to bitcore style and submit a PR? :)

**Comment by braydonf** [comment]
Bitcore should be compatible with https://github.com/bitcoinjs/bip38 so that sounds like the way to go (and no need to duplicate the work):

```js
var Bip38 = require('bip38');
var bitcore = require('bitcore');
var privateKey = bitcore.PrivateKey(bitcore.Networks.testnet) // new random key
var privateKeyWif = privateKey.toWIF();
var address = privateKey.toAddress().toString();
var bip38 = new Bip38();
var encrypted = bip38.encrypt(privateKeyWif, "super-secret", address);
console.log(encrypted)
````

**Comment by bilthon** [comment]
@braydonf this actually only works with the livenet. Using the testnet as your example returns a wrong decrypted WIF address. Also it would be a lot simpler and thus better to just go by something like this:

```javascript
var privateKey = bitcore.PrivateKey(bitcore.Networks.testnet)
var encrypted = privateKey.bip38Encrypt("super-secret")
```

I could take some spare time to try to integrate this into bitcore, but before I do any work I would like to get more feedback on my proposal.
