### ISSUE TITLE
implement BIP62 new rules against tx malleability 

### ISSUE THREAD

**Issue by maraoz** [bitpay/bitcore#608]
- [ ] Canonically encoded ECDSA signatures 
- [ ] Non-push operations in scriptSig
- [ ] Push operations in scriptSig of non-standard size type
- [ ] Zero-padded number pushes 
- [x] Inherent ECDSA signature malleability
- [ ] Superfluous scriptSig operations .
- [ ] Inputs ignored by scripts

source: https://github.com/bitcoin/bips/blob/master/bip-0062.mediawiki#New_rules

**Comment by braydonf** [comment]
The [low S value](https://github.com/bitcoin/bips/blob/master/bip-0062.mediawiki#Low_S_values_in_signatures) has been implemented: https://github.com/bitpay/bitcore/blob/master/lib/crypto/ecdsa.js#L200

**Comment by maraoz** [comment]
updated issue description with task list

**Comment by braydonf** [comment]
Signatures should also be strict DER encoding: https://github.com/bitcoin/bips/blob/master/bip-0062.mediawiki#der-encoding
