### ISSUE TITLE
add browserling or some similar tool

### ISSUE THREAD

**Issue by maraoz** [bitpay/bitcore#682]

**Comment by braydonf** [comment]
Results from attempting to add automated browser tests:
- Browserling/testling hooks were timing out
- Browserstack credentials need to be encrypted and thus will only run on Travis CI for pull requests coming from the same repository. When this was attempted IE connections via karma-browserstack-launcher would disconnect in the middle of the test.
- Running karma-ie-launcher and karma-safari-launcher locally was also experiencing the same disconnection problems, and some odd behavior with running tests multiple times in Safari.

For the time being, I think think the best option is to periodically run these tests in Safari and IE by opening `test/index.html` and solving the issues that might appear.

**Comment by maraoz** [comment]
I'll give a try to testling before we give up on this

**Comment by braydonf** [comment]
Also wondering if there may be better results with Sauce and zuul.

**Comment by maraoz** [comment]
Will try Sauce too then. 
AFAICT, travis will only support Firefox and PhantomJS. If we want more browsers, we'll have to use another tool

**Comment by maraoz** [comment]
zuul seems to be a good option. Still sorting out a little problem https://github.com/defunctzombie/zuul/issues/122
