### ISSUE TITLE
Support merge avoidance

### ISSUE THREAD

**Issue by ryanxcharles** [bitpay/bitcore#69]
Although bitcoin is naturally pseudonymous, it is very easy to leak personal financial information. A strategy to increase privacy is to never merge two outputs together. Instead, when sending a payment, send to many different addresses instead. This is called "merge avoidance". To my knowledge, this concept was first introduced by Justus Ranvier:

http://bitcoinism.blogspot.com/2013/07/reclaiming-financial-privacy-with-hd.html

And named by Mike Hearn:

https://medium.com/p/7f95a386692f

**Comment by braydonf** [comment]
Interesting, this likely applies more to these or similar repos now:
- https://github.com/bitpay/bitcore-wallet-service
