### ISSUE TITLE
add Transaction.getSending/ReceivingAddress()

### ISSUE THREAD

**Issue by maraoz** [bitpay/bitcore#692]
See: https://github.com/bitpay/bitcore/blob/master/lib/Transaction.js#L630

**Comment by braydonf** [comment]
Think link above 404s, updated: https://github.com/bitpay/bitcore/blob/v0.1/lib/Transaction.js#L630

This would be more accessible than writing:
```js
transaction.inputs[0].script.toAddress()
```
