### ISSUE TITLE
Support CoinJoin

### ISSUE THREAD

**Issue by ryanxcharles** [bitpay/bitcore#73]
In order to increase privacy, CoinJoin is a strategy for combining transactions with other parties. We should support this in bitcore. Info here:

https://bitcointalk.org/index.php?topic=279249.0

**Comment by braydonf** [comment]
As far as I am aware, most progress in this area is at: https://github.com/JoinMarket-Org/joinmarket 

Possible paths forward in relation to bitcore (and not directly related with this repo):
- Service for bitcore-node (https://github.com/bitpay/bitcore-node)
- Added to bitcore-wallet-service (https://github.com/bitpay/bitcore-wallet-service)
