### ISSUE TITLE
Add a peer limit to peer discovery

### ISSUE THREAD

**Issue by maraoz** [bitpay/bitcore#733]
Add a peer limit to peer discovery. Having it hardcoded at 1000 hits the ulimit in most OS's and is generally unnecessary. 32 is a reasonable default.

**Comment by braydonf** [comment]
The version one branch looks to have a limit at 12: https://github.com/bitpay/bitcore/blob/v0.1/lib/PeerManager.js#L253

The pool now has a configurable value and defaults to 8 active connections: https://github.com/bitpay/bitcore-p2p/blob/master/lib/pool.js#L85
