### ISSUE TITLE
Support colored coins

### ISSUE THREAD

**Issue by ryanxcharles** [bitpay/bitcore#74]
Info: https://docs.google.com/document/d/1AnkP_cVZTCMLIzw4DvsW6M8Q2JC0lIzrTLuoWu2z1BE/edit

Further resources, thanks @maraoz:

* https://github.com/bitcoinx/colored-coin-tools/wiki/the-next-gen-colored-coin-client
* https://github.com/bitcoinx/ngcccbase
* https://groups.google.com/forum/#!msg/bitcoinx/pON4XCIBeV4/IvzwkU8Vch0J
* https://groups.google.com/d/topic/bitcoinx/g5V5EDqInn8/discussion
* http://chromawallet.com/
* https://github.com/bitcoinx/colored-coin-tools/wiki/colored_coins_intro
* http://letstalkbitcoin.com/e80-beyond-bitcoin-uncut/#.UwIiUWRDtn8

**Comment by braydonf** [comment]
As similar to https://github.com/bitpay/bitcore/issues/73, possible paths forward (and not directly related with this repo):

- Color coin service for bitcore-node (https://github.com/bitpay/bitcore-node)
- Support added into bitcore-wallet-service (https://github.com/bitpay/bitcore-wallet-service)
