### ISSUE TITLE
Add a jshint analizer bot

### ISSUE THREAD

**Issue by maraoz** [bitpay/bitcore#815]
Like travis but for jshint checks. What do you think?

**Comment by maraoz** [comment]
someone research the cost of doing this and close if it will take more than 4 hours. Otherwise, implement it :)

**Comment by yemel** [comment]
Ok, I'll do the research

**Comment by yemel** [comment]
I did the research and there is no free hosted solution that checks for code style and support PR comments on open-source projects.

The best services I found are: codeclimate.com and codacy.com. I contacted them and both told me they have that feature on the roadmap.

I'm closing the issue, we may reopen it in the future.

**Comment by paulblei** [comment]
@yemel just to let you know that Codacy https://www.codacy.com now has this feature allowing you to auto-comment on every issue found on the PR page. Ex: https://github.com/paypal/squbs/pull/86 
Let me know if you have questions
