### ISSUE TITLE
bitcore.crypto.Hash.sha256 returns a SlowBuffer

### ISSUE THREAD

**Issue by yemel** [bitpay/bitcore#819]
Old bitcore code that returns a Buffer:
```
return new Buffer(crypto.createHash('sha256').update(data).digest('binary'), 'binary');
```

Current implementation that returns a SlowBuffer:
```
return crypto.createHash('sha1').update(buf).digest();
```

Could this be a performance problem? IMO we shouldn't expose SlowBuffers instances on the API.

**Comment by braydonf** [comment]
No longer the case with Node.js 4
