### ISSUE TITLE
implement bitcore-identity submodule

### ISSUE THREAD

**Issue by maraoz** [bitpay/bitcore#825]
this will add SIN support.
see: https://github.com/bitpay/bitcore/pull/529

**Comment by maraoz** [comment]
whoever grabs this issue should analize if bitauth conforms to this protocol: https://en.bitcoin.it/wiki/Identity_protocol_v1
and decide if we should do this module or just stick with bitauth for identity management.

**Comment by braydonf** [comment]
BitAuth implements a portion of the identity protocol, only Type 2 and not Type 1. However I don't think the transactions defined on the wiki would be accepted in the network currently.

**Comment by maraoz** [comment]
Yes, we only need to support type 2, but I'm not sure if bitauth implements
type 2. We need to check it :)

**Comment by braydonf** [comment]
Type 2 is supported, see: https://github.com/bitpay/bitauth/blob/master/lib/bitauth.js#L72
