### ISSUE TITLE
Add Meteor Support

### ISSUE THREAD

**Issue by html5cat** [bitpay/bitcore#852]
Haven't played with this lib, but looks very promising!
@dandv, do you think you could apply your magic here like you did with [Bootstrap Material Design](https://github.com/FezVrasta/bootstrap-material-design/pull/291)?

**Comment by joshuarossi** [comment]
this looks really amazing, is it still going to be included?

**Comment by braydonf** [comment]
Moved to: https://github.com/bitpay/bitcore-lib/issues/65
