### ISSUE TITLE
Improve Transaction errors when Input information is missing

### ISSUE THREAD

**Issue by yemel** [bitpay/bitcore#868]
- Create a transaction from a raw data
- Methods: `tx.isFullySigned()` throws a hardly understandable error

```
var tx = new bitcore.Transaction('0100000001eda87083.....');
tx.isFullySigned();

Abstract Method Invokation: Input#isFullySigned
Error
    at Error.bitcore.Error.AbstractMethodInvoked (/Users/yemeljardi/code/bitcore/lib/errors/index.js:67:39)
    at Input.isFullySigned (/Users/yemeljardi/code/bitcore/lib/transaction/input/input.js:136:9)
    at /Users/yemeljardi/code/bitcore/lib/transaction/transaction.js:661:18
    at Function.map (/Users/yemeljardi/code/bitcore/node_modules/lodash/dist/lodash.js:3508:27)
    at Transaction.isFullySigned (/Users/yemeljardi/code/bitcore/lib/transaction/transaction.js:660:18)
```

Same happens with `tx.isValidSignature()`:

```
var tx = new bitcore.Transaction('0100000001eda87083.....');
tx.isFullySigned();

TypeError: Cannot read property 'inputIndex' of undefined
    at Transaction.isValidSignature (/Users/yemeljardi/code/bitcore/lib/transaction/transaction.js:667:31)
```

Expected behaviour: throw a `NotEnoughInformation`-like exception and explain the error.

**Comment by benjaminmcdonald** [comment]
Still getting this cryptic message 

## Copied from the example on the homepage
var privateKey = new bitcore.PrivateKey('L1uyy5qTuGrVXrmrsvHWHgVzW9kKdrp27wBC7Vs6nZDTF2BRUVwy');
var utxo = {
  "txId" : "115e8f72f39fad874cfab0deed11a80f24f967a84079fb56ddf53ea02e308986",
  "outputIndex" : 0,
  "address" : "17XBj6iFEsf8kzDMGQk5ghZipxX49VXuaV",
  "script" : "76a91447862fe165e6121af80d5dde1ecb478ed170565b88ac",
  "satoshis" : 50000
};

var transaction = new bitcore.Transaction()
  .from(utxo)
  .to('1Gokm82v6DmtwKEB8AiVhm82hyFSsEvBDK', 15000)
  .sign(privateKey);


> transaction.isFullySigned()
true
> transaction.isValidSignature()
bitcore.js:9893 Uncaught TypeError: Cannot read property 'inputIndex' of undefined(…)

**Comment by braydonf** [comment]
The first argument of `isValidSignature` is expected to be a signature, and thus the error. However, the method is missing jsdocs and a precondition for the argument.
