### ISSUE TITLE
block message fields (lib/block.js) 

### ISSUE THREAD

**Issue by jimmyscratchlab** [bitpay/bitcore#879]
lib/block.js
{
    magicnum:
    size:
    header: 
    txsvi: 
    txs: 
 }

https://en.bitcoin.it/wiki/Protocol_Specification#block
block message payload
{
version:
prevHash:
merkle_root:
timestamp:
bits:
nonce:
txn_count:
info.txns:
}

**Comment by braydonf** [comment]
Block Hashing Algorithm (https://en.bitcoin.it/wiki/Block_hashing_algorithm) describes the properties as a part of the header (e.g. block.header.bits), please see more info on the [bitcore docs](http://bitcore.io/guide/block.html#Block_Header). The associated validation functions are similarly located:
- block.header.validTimestamp()
- block.header.validProofOfWork()

**Comment by jimmyscratchlab** [comment]
This function don't work!

Block._fromBufferReader = function _fromBufferReader(br) {
var info = {};
info.magicnum = br.readUInt32LE();
info.size = br.readUInt32LE();
info.header = BlockHeader.fromBufferReader(br);
info.txsvi = Varint(br.readVarintBuf());
var txslen = info.txsvi.toNumber();
info.txs = [];
for (var i = 0; i < txslen; i++) {
info.txs.push(Transaction().fromBufferReader(br));
}
return info;
};

Please correct it----->

Block._fromBufferReader = function _fromBufferReader(br) {
  var info = {};//read(32)
info.version =  br.readUInt32LE();
info.prevHash= br.read(32);//console.log(info.prevHash.toHex());
info.merkle_root= br.read(32);
info.timestamp= br.readUInt32LE();
info.bits =br.readUInt32LE();
info.nonce =br.readUInt32LE(); 
info.txn_count  = Varint(br.readVarintBuf()).toNumber();
info.txns  = [];
for (var i = 0; i < info.txn_count; i++) {
    info.txns.push(Transaction().fromBufferReader(br));
} 

 /*info.magicnum = br.readUInt32LE();
  info.size = br.readUInt32LE();
  info.header = BlockHeader.fromBufferReader(br);
  info.txsvi = Varint(br.readVarintBuf());
  var txslen = info.txsvi.toNumber();
  info.txs = [];
  for (var i = 0; i < txslen; i++) {
    info.txs.push(Transaction().fromBufferReader(br));
  }
*/

  return info;
};

 It can work!!!

**Comment by braydonf** [comment]
I believe this is related to this issue: https://github.com/bitpay/bitcore/pull/938

The `magicnum` and `size` are not relevant here, and are used when storing blocks in `.dat` files in [network format](https://en.bitcoin.it/wiki/Data_directory#Files)

**Comment by braydonf** [comment]
Fixed in https://github.com/bitpay/bitcore/pull/938
