### ISSUE TITLE
Invalid Output Script Buffer Handling

### ISSUE THREAD

**Issue by braydonf** [bitpay/bitcore#880]
Output:
```
{ _satoshis: <BN: 0>,
  _scriptBuffer: <Buffer 6a 15 41 53 43 52 49 42 45 53 50 4f 4f 4c 52 45 50 4c 45 4e 49 53 48> }
var s = new Script(tx.outputs[i]._scriptBuffer)
```
Results in an Error:
```
buffer.js:582
    throw new RangeError('Trying to access beyond buffer length');
```

Edit: Perhaps a `valid` method could be added to easily check the state before using the script?

**Comment by eordano** [comment]
Hmm, we should change `inspect` so you don't use `._scriptBuffer` and instead use `.script` to do what you're trying to achieve (`new Script(output._scriptBuffer)` should be discouraged as you can just do `output.script`)

**Comment by braydonf** [comment]
Perhaps a `Script.isValidBuffer` would be helpful here.
