### ISSUE TITLE
Confusing use of output._satoshis vs output.satoshis

### ISSUE THREAD

**Issue by braydonf** [bitpay/bitcore#881]
`output._satoshis` is a BN, and `output.satoshis` is a Number. One appears to be used for internal usage and hence the underscore, however a number should be sufficient since the maximum number of satoshis is 2100000000000000 which can accurately be represented without BN.

**Comment by eordano** [comment]
Hmmm, this one is on me:
* When refactoring tx input, I wanted to move away from big numbers
* When decoding a tx output, the value in there may be a negative 1, and bufferreader was reading this as 2^64-1
* At the moment, I didn't wanted to modify buffer reader (and probably break something) but I needed this transaction with the weird output to decode and encode correctly, so I made a wrapper around the big number that should always return a `Number` (the `satoshis` value).

**Comment by braydonf** [comment]
I'm thinking we should rename to `_satoshisBN` and `satoshis` since it's straight from a buffer in some cases.
