### ISSUE TITLE
Unmet dependency when loading in Meteor

### ISSUE THREAD

**Issue by Levino** [bitpay/bitcore#886]
Hey guys,

I try to get the Bitcore version 0.8.5 running in Meteor (server side). Unfortunatly I get the following errors:

```
npm WARN unmet dependency /home/levin/coding/coynows/meteor/packages/npm-container/.npm/package-new-huj1gl/node_modules/bitcore/node_modules/elliptic requires
hash.js@'^0.2.0' but will load
npm WARN unmet dependency /home/levin/coding/coynows/meteor/packages/npm-container/.npm/package-new-huj1gl/node_modules/bitcore/node_modules/hash.js,
npm WARN unmet dependency which is version 0.3.2
npm ERR! Error: Problems were encountered
npm ERR! Please correct and try again.
npm ERR! invalid: elliptic@0.15.12 /home/levin/coding/coynows/meteor/packages/npm-container/.npm/package-new-huj1gl/node_modules/bitcore/node_modules/elliptic
npm ERR! invalid: hash.js@0.3.2 /home/levin/coding/coynows/meteor/packages/npm-container/.npm/package-new-huj1gl/node_modules/bitcore/node_modules/hash.js
```

Is this Meteor specific or a general problem?

Thanks

Levin

**Comment by braydonf** [comment]
Also receiving these with `npm install bitcore`: 

```
npm WARN unmet dependency /var/www/bitpay/bitcore-tmp10/node_modules/bitcore/node_modules/elliptic requires hash.js@'^0.2.0' but will load
npm WARN unmet dependency /var/www/bitpay/bitcore-tmp10/node_modules/bitcore/node_modules/hash.js,
npm WARN unmet dependency which is version 0.3.2
```

**Comment by braydonf** [comment]
The package.json in elliptic specifies "^0.2.0" for hash.js, and the npm-shrinkwrap in bitcore is loading "0.3.2".

**Comment by braydonf** [comment]
This should fix the issue: https://github.com/bitpay/bitcore/pull/887

**Comment by Levino** [comment]
A new release would be nice. How to trigger this?

**Comment by braydonf** [comment]
To pull from the latest (before a release) you can [include a git url](https://docs.npmjs.com/files/package.json#git-urls-as-dependencies) in your package.json file "dependencies":
```javascript
 "bitcore": "bitpay/bitcore"
```
Or use the full git url:
```javascript
"bitcore": "git://github.com/bitpay/bitcore.git"
```

**Comment by ggutoski** [comment]
Meteor users [must link directly to a github tarball for a specific commit](https://github.com/meteor/meteor/issues/844).  For example:
```javascript
"bitcore": "https://github.com/bitpay/bitcore/tarball/5ae97a7146db96f675daedfdcef2fd4842037478/"
```
Thanks @Levino for discovering this problem three days before I did, and @braydonf for posting the solution mere hours before I needed it.
