### ISSUE TITLE
If Networks.defaultNetwork is set to testnet, 14 tests fail.

### ISSUE THREAD

**Issue by eordano** [bitpay/bitcore#890]
This means that either we have some code or tests that depend on the default network being livenet. The first one is dangerous, so we should fix all tests to be defaultNetwork-proof so we are sure that our code is strong against changes to defaultNetwork (which probably is)

**Comment by braydonf** [comment]
There may be some hardcoded values that are checking the network in the tests.

**Comment by braydonf** [comment]
Fixed in https://github.com/bitpay/bitcore/pull/905
