### ISSUE TITLE
G doesn't have precomputed values from elliptic for faster computation

### ISSUE THREAD

**Issue by braydonf** [bitpay/bitcore#895]
The `Point` wrapper when returning G from `getG` does not include the precomputed values that speed point multiplication, as pointed out by @ryanxcharles on https://github.com/bitpay/bitcore/pull/894 when changing this fixed a bug because different point multiplication was used. A solution is to return `ec.curve.g` from `Point.getG` or use `ec.curve.g` and `ec.curve.n` directly. Another would be to check types `instanceof` using the `elliptic.curve.base.BasePoint` directly and use `ec.curve.point` without the extended class in `crypto/point`, and move the added point validation function to `bitcore.PublicKey`.

**Comment by eordano** [comment]
Please reopen if this https://github.com/bitpay/bitcore/commit/0bcfec9f2f4b3a6cacc5791dd2e57c018cefe8b7 is not enough
