### ISSUE TITLE
Error Message Enhancements

### ISSUE THREAD

**Issue by braydonf** [bitpay/bitcore#912]
Error messages are repetitive, too long, and the main message of the error is half the way into the string.
```js
var a = new Address();
// bitcore.Error.InvalidArgument: Invalid Argument: TypeError: First argument is required, please include address data.
```
These could be readable, examples:
```js
// Bitcore Error: Invalid Argument: First argument is required, please include address data.
```
```js
// TypeError: First argument is required, please include address data.
```
```js
// First argument is required, please include address data.
```

**Comment by braydonf** [comment]
Also, it may be helpful to add a link in the error message, such as: http://bitcore.io/api/address.html

**Comment by yemel** [comment]
I like the option 2. I really like the idea of adding the documentations link on the error.
