### ISSUE TITLE
Encrypt travis tokens

### ISSUE THREAD

**Issue by yemel** [bitpay/bitcore#923]
Follow this docs: http://docs.travis-ci.com/user/encryption-keys/

Can we revoke the current token?

**Comment by braydonf** [comment]
Encrypted environments variables are not available on pull requests from external repositories, so Travis CI wouldn't not run on pull requests, likely.

**Comment by yemel** [comment]
Gotcha, you are right. Anyway we removed zulu tokens, so this issue is no longer valid.
