### ISSUE TITLE
Update bignum version to 0.9

### ISSUE THREAD

**Issue by mxmauro** [bitpay/bitcore#954]
Hi,

Bitcore currently points to bignum 0.6 instead of the latest 0.9

The problem with the old version is a bug where bignum calls "free" instead of "OpenSSL_free" making Windows version to crash on certain operations.

Regards,
Mauro.

**Comment by eordano** [comment]
Hi Mauro,

We've been working on a new release of bitcore, and we're no longer using bignum. We switched over to @indutny's bn.js, a library written from scratch. The 0.1 version is deprecated, and we suggest you move over to the newest version. I'll update the package anyways for the older version and see if we can make a small release.

Regards,
Esteban

**Comment by mxmauro** [comment]
Ahhh ok... thank you for the info update.

Regards,
Mauro.
