### ISSUE TITLE
separate bitcore-rpc into bitcoin-rpc and bitcore-rpc

### ISSUE THREAD

**Issue by maraoz** [bitpay/bitcore#962]
bitcoin-rpc should be similar to current bitcore-rpc, with better test coverage.

bitcore-rpc should be a wrapper that returns bitcore objects and a nicer API.

**Comment by braydonf** [comment]
First part is done and has 99% test coverage: https://github.com/bitpay/bitcoind-rpc

I think we should save bitcore-rpc for later, when there is more need, and more detailed use case.

**Comment by maraoz** [comment]
Spawned new issue for `bitcore-rpc`: https://github.com/bitpay/bitcore/issues/983
