### ISSUE TITLE
check standards for all submodules

### ISSUE THREAD

**Issue by maraoz** [bitpay/bitcore#972]
Check new error system, karma usage, gulp usage, README, docs, npm publish, bower register, .gitignore, and test `gulp browser` and `gulp release` for:

- [x] ~~bitcore-rpc~~ (not a bitcore module yet. See: https://github.com/bitpay/bitcoind-rpc) 
- [x] ~~bitcore-bloom~~ (not a bitcore module yet. Will be part of `bitcore-p2p`. See: https://github.com/bitpay/bloom-filter)
- [x] bitcore-p2p
- [x] bitcore-channel (@maraoz doing this)
- [x] bitcore-mnemonic
- [x] bitcore-payment-protocol (@maraoz doing this)
- [x] bitcore-ecies
- [x] bitcore-explorers (@yemel doing this)
- [x] bitcore

**Comment by braydonf** [comment]
Also, these modules need jsdocs:

    bitcore-p2p -> messages
    bitcore -> script/interpreter
    bitcore-ecies -> everything
    bitcore-payment-protocol -> everything

And each module will either need an /docs/index.md file, or we can possibly use the README.md for these purposes, however an /docs/index.md may be better.

**Comment by yemel** [comment]
All submodules has been checked and published.
