### ISSUE TITLE
Update EXCLUDE from all bower.json files

### ISSUE THREAD

**Issue by yemel** [bitpay/bitcore#973]
When installing a submodule, make sure bower only copies to `bower_components` the following files: `bitcore-XXX.js` `bitcore-XXX.min.js` and `README.md`

**Comment by braydonf** [comment]
If we had a map file wouldn't it also be good to include the originals, before browserified?

**Comment by braydonf** [comment]
Also the docs

**Comment by braydonf** [comment]
I believe this was handled in: https://github.com/bitpay/bitcore/issues/972
